### ISSUE TITLE
Extra Ribbon Options in Top Matter < Library Search>  etc.

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#101]
### This should be fixable via Primo View Configuration. not a real show stopper :watch:

![screen shot 2013-12-06 at 1 12 29 pm](https://f.cloud.github.com/assets/2441612/1694494/20ba09c2-5ea2-11e3-9223-dcdf38a73672.png)

**Comment by bassettsj** [comment]
Yeah this is not a CSS / JS issue. This just configuration. Select whatever
we want to show and it will show.
