### ISSUE TITLE
Advanced search styling - dropdowns, scrollbar

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#102]
A scrollbar is appearing at the bottom of the advanced search window that is partially obscuring the link to search WorldCat.  (Present in both Safari and Chrome)

Date dropdowns in advanced search are oddly aligned in Safari.  Look fine in Chrome.

Screenshot below shows both issues in Safari.

![datedropdownalignadvsearch](https://f.cloud.github.com/assets/4661920/1695482/b51515e8-5eb2-11e3-815e-6099e3952423.png)

**Comment by nestochan** [comment]
Scrollbar  :construction:

```
#exlidAdvancedSearchRibbon div.EXLSearchFieldRibbonPreFilters {
min-height: 12em;
overflow: hidden; <<<  this bit is defaulting to auto -- hidding gets rid of it.
}
```

```
@media (min-width: 992px)
#exlidAdvancedSearchTile #exlidAdvancedSearchRibbon div.EXLSearchFieldRibbonFormFieldsGroup2 .EXLAdvancedSearchFormDateRangeRow select, #exlidAdvancedSearchTile #exlidAdvancedSearchRibbon div.EXLSearchFieldRibbonFormFieldsGroup2 .EXLAdvancedSearchFormDateRangeRow input[type=text] {
margin-left: 2.083333333333333%;   <<<< disable this  will fix wonky off-grid alignment.
```

**Comment by bassettsj** [comment]
![screenshot 2013-12-09 10 46 43](https://f.cloud.github.com/assets/1218420/1706069/1f185030-60e9-11e3-8409-b084710e2dab.png)

**Comment by nestochan** [comment]
:muscle:

**Comment by jasf-** [comment]
Looking good!  Thanks!
