### ISSUE TITLE
Adding persistent URLs in SOS

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#103]
#### Adding persistent URLs in SOS

---

**Feature:** Add working Persistant URLs to local holdings Records in Primo (SOS)
  **Scenario:** We want to have a reliable way to link directly back to local holdings records
**Given:** When a search result is returned 
**And:**  And user is presented with a local record,
**Then:** A link is provided that refers back to the local record.
**And:**  Followed link goes out to external service that converts to DeepLink Syntax
**Then:**  Redirects back to Primo SOS as a DLSearch - resolving to record.

---

> > **Note:**  Below makes reference to an external intermediary system to get this working using php: We believe that the functionality lives in this Public GH repo:
> > https://github.com/BCLibraries/primo-services

we should take a look

---

From the Primo List serv as posted by Ben Florin.

> We made an intermediary service in PHP that translates some of the most common persistent URLs--direct links to records, direct links to collections, and direct links to a blank Aleph Search Page--to Primo Deep Link syntax. For example:
> 
> > http://library.bc.edu/F?func=direct&l_base=&doc_number=002876969
> >     http://library.bc.edu/F?func=find-b&local_base=BC_CATALOG&find_code=WLT&request=seamus+connolly
> >     http://library.bc.edu/F?func=find-b-0&local_base=BC_CATALOG
> 
> We also added a note to Primo to the effect of “Surprised? This is your new catalog!”—only more serious.
> 
> We’re in the process of moving our stuff to Github. I’ll try to get the redirect code up ASAP.

**Comment by nestochan** [comment]
:parking:   Adding persistent URLs in SOS  https://github.com/NEU-Libraries/scholar-onesearch/issues/103

 @jasf-

**Comment by nestochan** [comment]
:bulb:  perhaps adding bookmarklet type functionality by reusing code used to populate report a problem so that we can provide links like these...

http://onesearch.northeastern.edu/primo_library/libweb/action/dlDisplay.do?vid=NU&docId=TN_gale_ofa61348444
http://onesearch.northeastern.edu/primo_library/libweb/action/dlDisplay.do?vid=NU&docId=NEU_ALMA21156948240001401

example bookmarklet already in the wild:

```
javascript: if(location.search != ""){   x = location.search.substr(1).split("&");   
flag = false;   for(i=1; i<x.length; i++){     y = x[i].split("=");     
if(y[0] == "doc"){       flag = true;       
wres = window.open("",'','height=200,width=800');       
wres.document.write("<html><head><title>Primo Link Changer</title></head><body>Here is the link:<br/<br/>");       
wres.document.write("http://onesearch.northeastern.edu/primo_library/libweb/action/dlDisplay.do?vid=NU&docId="+y[1]);       
wres.document.write("</body></html>");       
break;     }   }   if(flag == false){     alert("Sorry, but this is not the right Primo window. Please try again");   } }
```

**Comment by bassettsj** [comment]
That seems like a great idea and could be implemented pretty quickly I think.

Maybe adding a new button to the tab bar or the share menu.
[ :link: ](http://onesearch.northeastern.edu/primo_library/libweb/action/dlDisplay.do?vid=NU&docId=NEU_ALMA21156948240001401)

**Comment by nestochan** [comment]
```
  var permalink = function(){
      var $results = $('#exlidResultsTable tr.EXLResult');
      $results.each(function(){
        var id = $(this).find('a.EXLResultRecordId').attr('id');
        //The Document ID
        var docid = id;
        var url = 'hhttp://onesearch.northeastern.edu/primo_library/libweb/action/dlDisplay.do?vid=NU&docId=' + id;

              var $link = $('<li><a class="permalink  btn btn-small btn-link" href="'
 + url + '" title="permalink." target="_blank"><i class="icon-comments-alt"></a
><li>');
        $(this).find('ul.EXLResultTabs').append($link);
      });
      $('a.permalink').tooltip();
    };
```

**Comment by bassettsj** [comment]
Look at you @nestochan You're getting good at this :clap:

**Comment by bassettsj** [comment]
- `.fa-link` icon
- in the results tab

**Comment by bassettsj** [comment]
- http://onesearch-test.northeastern.edu/primo_library/libweb/action/dlDisplay.do?doc=TN_crossref10.1097%2F00006534-200012000-00060
- http://onesearch-test.northeastern.edu/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=TN_crossref10.1097%2f00006534-200012000-00060&indx=22&recIds=TN_crossref10.1097%2f00006534-200012000-00060&recIdxs=1&elementId=&renderMode=poppedOut&displayMode=full&http://onesearch-test.northeastern.edu:80/primo_library/libweb/action/expand.do?dscnt=0&frbrVersion=&frbg=&scp.scps=scope%3A%28NEU%29%2Cprimo_central_multiple_fe&tab=default_tab&dstmp=1392754342181&srt=rank&gathStatTab=true&mode=Basic&dum=true&vl(freeText0)=face&vid=NUdev

**Comment by bassettsj** [comment]
http://onesearch-test.northeastern.edu/primo_library/libweb/action/display.do?recIds=TN_crossref10.1097%2f00006534-200012000-00060

**Comment by nestochan** [comment]
This feature will require additional development to open in a lightbox instead of opening in a new window.
transfering this out of milestone and placing in future dev.

permalink functionality has been added in Primo4.6.

**Comment by elizoller** [comment]
@nestochan is this the same as issue #130? Or do you mean having the permalink go to the "locations and status" tab not the "details and related links" tab?

**Comment by nestochan** [comment]
@elizoller I believe this to be a duplicate to #130 and predates the permalink functionality developed by exlibris- gonna close this.  

:black_joker:
