### ISSUE TITLE
Feature Request - > "repeat this search in the DPLA"

### ISSUE THREAD

**Issue by bassettsj** [NEU-Libraries/scholar-onesearch#105]
So... When can we get a "repeat this search in the DPLA" widget??  Just thinking.. EDS already offers one!!
@PatrickYott

**Comment by bassettsj** [comment]
What is EDS by the way?

**Comment by nestochan** [comment]
:question:  Ebsco Discover Service?
or some other thing:question:

**Comment by PatrickYott** [comment]
Bingo

Patrick M. Yott
Associate Dean for Digital Strategies and Services
Northeastern University Libraries
360 Huntington Ave, SL 327
Boston, MA 02115
p.yott@neu.edumailto:p.yott@neu.edu
617.373.4194

On Dec 10, 2013, at 11:03 AM, "nestochan" <notifications@github.com<mailto:notifications@github.com>> wrote:

[:question:] Ebsco Discover Service?
or some other thing[:question:]
