### ISSUE TITLE
Add database a-z link

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#106]
Add database A-Z link to top right corner of SOS 1.2. See attached screenshot for language and location specifics.

**Comment by winthropo** [comment]
![screen shot 2014-01-08 at 2 58 26 pm](https://f.cloud.github.com/assets/4663357/1872032/a25165e0-789f-11e3-936b-dedbe763136c.png)

**Comment by winthropo** [comment]
The new 'Databases A-Z' link should go to http://library.northeastern.edu/find/resources/databases

**Comment by bassettsj** [comment]
Hey @nestochan , this is a simple configuration change in the primo back office. Should I take care of that one now?

**Comment by jasf-** [comment]
Re:  the link above, is that the one we want?  Or is it http://library.northeastern.edu/find/resources/a-to-z-index?

**Comment by kmerguerian** [comment]
Reopening, the link URL has changed.  The old one is still working and forwarding to the new, but might as well update anyway to the correct URL. Not an urgent issue.   http://library.northeastern.edu/research/resources/a-to-z-index

**Comment by elizoller** [comment]
Updated on staging server NU and NUdev views and on production server NU view
