### ISSUE TITLE
'did you mean' functionality - expanded misspellings file

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#107]
Larger list of misspellings for 'did you mean' file.  Larger list has been implemented @ several other sites

**Comment by bassettsj** [comment]
Here is what we will probably use to get that effect: https://github.com/justinkelly/primo-misspell

**Comment by bassettsj** [comment]
also see issue #5

**Comment by nestochan** [comment]
:sob:  my apologies.. I misspoke in yesterday's meeting in saying that misspell_eng.txt was not "did you mean" 

meaning that the "did you mean" Job that works off the indexes was not this,
however, the "DYM" service does look at this file in addition to the generated indexes when making suggestion. 

So though it is not "DYM" alone, it IS and enhancement of the "DYM Service.
This is now complete and the up-to-date file has been put in place on the servers.

Closing ISSUE.
