### ISSUE TITLE
add more helpful info to details tab 

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#109]
Just a placeholder to track the issue - this is Sarah & Stephanie's bailiwick

**Comment by winthropo** [comment]
@jasf- can this be closed?

**Comment by jasf-** [comment]
Don't think so...

**Comment by sarahjeansweeney** [comment]
Here is a list of the fields that displayed in NUCat, but are not displaying in SOS:

Music No.
Other Title
Key Title
Note
Former Title
Time
Hours
Frequency
Publishing History
With
Dissertation
Bibliography
Credits
Performer
File Type
Summary
Cite As
Reproduction
System Requirements
Issued By
Indexes
Finding Aids
Provenance
Awards
Uniform Title
Related To
Issued With

For a more detailed description of the fields, with examples, go here: https://docs.google.com/spreadsheets/d/1QsSVRGag5xVO5P6yA7igrzVMzVLZRpbGFlni2Q-0pcU/edit?usp=sharing 

I think it's fairly easy to add these fields to the current display, it would just take some time.

**Comment by jasf-** [comment]
See library-help thread for submission #13589 for more.  Per that thread there is interest in displaying 500 field (note), 504 (bibliography), 505 (contents), 508(credits), 520 (summary), 590 (local note).
With version 4.9, it is now also possible to display table of contents.

All to be discussed at READ 5/28/15.

**Comment by winthropo** [comment]
sarah. you are so wrong. i disagree. with everything you said.

**Comment by jasf-** [comment]
From READ 05/28/15:  Why not turn most of 'em on, since they will be behind the Details tab and there's helpful info there?  Kristin will add these in Staging and we'll see how it looks.

**Comment by winthropo** [comment]
sarah, please ignore previous message from me. i was showing someone how (not) to use Git.

**Comment by kflachs** [comment]
500 note has been added to details tab and is in production...will add remaining items from list into staging

**Comment by kflachs** [comment]
Remaining fields (except 730 Uniform Title- how to label? where to place?) have been added into staging for review.

**Comment by jasf-** [comment]
We like it!  We're gonna keep all the new details aside from music notes and time.
