### ISSUE TITLE
style services tab (for holding pen)

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#110]
Style services tab to make it more scannable a la VCU. 
this css provides for:
- more spacing between entries
- indentation of entries
- styles links so they pop
- font appears more readable

**Comment by winthropo** [comment]
### screenshot for the VCU customization

![screen shot 2014-01-08 at 4 05 21 pm](https://f.cloud.github.com/assets/4663357/1872600/af669288-78a8-11e3-87f6-1afb7dc7252e.png)

**Comment by nestochan** [comment]
### Copy of Default mashup.css file from Primo Sandbox.

https://gist.github.com/nestochan/9398aacfda99fbb88120

**Comment by nestochan** [comment]
### Copy of VCU css customizations

https://gist.github.com/nestochan/b3045c346dbe6f41d2bd

**Comment by nestochan** [comment]
### copy of VCU css mashup

https://gist.github.com/nestochan/555253362e64e1e614cc

**Comment by nestochan** [comment]
Test VCUesque services CSS styling added to ALMA sandbox...

Beware of the caching  bug [ :bug: ]

:eyes: take a look :eyeglasses:

**Comment by nestochan** [comment]
:shipit: this has been deployed. 
cache clear required :put_litter_in_its_place:
