### ISSUE TITLE
style resolver page

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#111]
#### feature change: create a pared down css for use with the NEU Services Page

currently we are using customized NEU css. to style neu_services_page VIEW
we need a way to apply a substyle to:
- remove search box from view
- add report a problem link

Given: a search is done from an outside service like google scholar the resulting target takes you to the NEU services view.

Notes:
this is controlled from the views configuration in Primo.

![unknown](https://f.cloud.github.com/assets/4663357/1879325/59ffa7c6-7948-11e3-8b96-d017fc02afee.png)

**Comment by bassettsj** [comment]
How do you get to this view  by the way?

**Comment by jasf-** [comment]
Here's one way to get to this view:

Search Google Scholar for the title of that article E's showing in his screenshot 
On GS results page there will be a link on the right hand side 'GetIt@Northeastern'
Clicking that link takes you to the view

**Comment by bassettsj** [comment]
- [x] Adding a report a problem here. (pending)
- [x] Adding permalink
- [x] Remove searchbox from this view? (mangled by move to 4.6) break/fix
- [x] Remove green checkmark here for fultext availibilty (mangled by move to 4.6) break/fix

**Comment by kmerguerian** [comment]
Addition to this issue: The banner links to an incorrect view (when you click on Scholar OneSearch logo)

**Comment by kmerguerian** [comment]
Addition to this issue: remove the green check mark for Full Text Available since that is not always true. And yet it always appears.

**Comment by nestochan** [comment]
green checkmark (removed)
banner logo missing vid=NU (added)

**Comment by nestochan** [comment]
THIS SHOULD BE ALL SET.... May require cache reset --

`
browser refresh + shift-key
`
- [x] Adding a report a problem here. (pending)
- [x] ~~Adding permalink~~ (future release)
- [x] Remove searchbox from this view? (mangled by move to 4.6) break/fix
- [x] Remove green checkmark here for fultext availibilty (mangled by move to 4.6) break/fix
