### ISSUE TITLE
Can't scroll through SOS services menu using iOS7/mobileSafari

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#112]
Some content in 'view online" and "recommendations" tab for individual articles is larger than the ifame and on the iphone it can't be scrolled.
![photo](https://f.cloud.github.com/assets/4663357/1878719/4b8d56ec-793f-11e3-8ba9-bc471fd68b8a.PNG)

**Comment by elizoller** [comment]
7ba6af5ca6f39d8de9ae22fdfbe40262c965b9af should fix this. I tested using Browserstack and was successful with this fix. If you have an iPhone running iOS7 still, give it a whirl.
