### ISSUE TITLE
Language discrepancy. Facet labels and 'refined by' limiters in SOS don't use same terms.

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#113]
Stephanie Hudner noticed a discrepency in terminology between the facet display terms to the left of search results and the box that displays at the top of the results after refining with the facets. 

The facets on the left use the term “Material Type”, but the "refined by" box at the top uses the term “Resource Type”. 

The same goes for "Subject" and "Topic". I've attached her screenshot.

Example: Search for "housing vacancies" Click on "government documents" under "material types" to the left and then notice the terminology at the top of the results used for refining. 

![resource_type](https://f.cloud.github.com/assets/4663357/1878869/a042245e-7941-11e3-8d86-4924c740c0ac.png)

**Comment by jasf-** [comment]
I'm pretty sure this is a label change that can be done somewhere in the bowels of the Primo back office.

**Comment by elizoller** [comment]
Fixed on test server under Ongoing Config Wizards > Code Tables > Facet Labels
![screen shot 2014-10-30 at 9 28 23 am](https://cloud.githubusercontent.com/assets/5439169/4844076/aae5ae06-6038-11e4-94ff-912b89d5d02d.png)
