### ISSUE TITLE
View online tab displaying labels preceding the authentication and public notes. Alma Config issue.

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#114]
The view online tab is now displaying labels preceding the authentication and public notes. This is a recent change. For example, our authentication notes are now preceded by system supplied text: "Authentication note". And public notes are preceded by the system supplied text: "Public note". In addition to cluttering the screen, the labels seem pretty unnecessary; the notes are self-explanatory. I've attached screen
captures.

@nestochan can you make an alma configuration label? I don't think I am able to ..

**Comment by winthropo** [comment]
![capture_authentication_note](https://f.cloud.github.com/assets/4663357/1879148/76f5987a-7945-11e3-9791-28b05931fc56.png)

**Comment by jdevanna** [comment]
Is this something we still wanted to pursue? I made the edits in the sandbox, but perhaps we discuss this at the next READ meeting?
![image](https://cloud.githubusercontent.com/assets/9257706/13817096/4f90964a-eb67-11e5-909d-9b64114534c1.png)

Permalink: http://onesearch-test.library.neu.edu/NU:NEU_ALMA51196407790001401&tabs=viewOnlineTab
