### ISSUE TITLE
Remove the controlled vocabulary codes from the PNX so they don't display in SOS browse

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#115]
In browse search, choose 'by subject', and search for 'electronic books'

Result shown in screenshot attached.  We want to remove the controlled vocabulary codes from the PNX so they don't display
![ebooksbrowseweirdness](https://f.cloud.github.com/assets/4663357/1887984/e8bbde08-7a06-11e3-903b-d8dec7b65a7e.png)
. Sarah suspects if we remove the code from the PNX, all Electronic books headings will file together, which is probably preferred behavior.

**Comment by sarahjeansweeney** [comment]
Removing the code from display worked as I suspected, but it did file the 655 genre with the 650 subject. I'm not sure if anyone is concerned about those two being filed together (books about Electronic books filed together with books that are Electronic books...), but if that isn't desired behavior, I can look into how we can separate the two.
This is the how the subject browse for Electronic books looks now in staging:
![2014-02-27_0853](https://f.cloud.github.com/assets/4663073/2282974/84db62c0-9fb6-11e3-9cbd-5966a6fa6da4.png)

**Comment by sarahjeansweeney** [comment]
I disabled the rules that added $$T to the browse/subject PNX for the controlled vocabulary code in 6XX $$2 so that all matching terms, regardless of what controlled vocabulary they come from, will file together, and the code will be removed from display.
The rules were not deleted, just disabled.

**Comment by nestochan** [comment]
:thumbsup:

----- Reply message -----
