### ISSUE TITLE
Add citation linker 

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#117]
READ needs to add the citation linker to sandbox and test.

**Comment by nestochan** [comment]
use vid=NUnu there ids one configured there :thumbsup:

----- Reply message -----

**Comment by jasf-** [comment]
Citation linker not working for me in Chrome or Safari in vid=NUnu - am seeing a brief pop-up followed by a greyed-out screen.  Other links on the screen are working as expected.  Can anyone replicate?

**Comment by jasf-** [comment]
Based on feedback from today's READ meeting, we're going to table this for April release - there are too many issues with the linker as it currently stands.  May revisit for a later release.

**Comment by elizoller** [comment]
Citation linker is turned on in NUdev

**Comment by kmerguerian** [comment]
Thank you Eli!  Should we use this ticket to report testing results?  Or open new tickets?

**Comment by kmerguerian** [comment]
Do I have the right URL for NUdev?  I'm using
http://onesearch.library.northeastern.edu/primo_library/libweb/action/search.do?vid=NUdev
but I'm not seeing any styling or a citation linker
![screen shot 2015-02-05 at 11 28 31 am](https://cloud.githubusercontent.com/assets/2442078/6064107/d6d676ce-ad29-11e4-89a2-f0c762780d37.png)

**Comment by jdevanna** [comment]
It is: http://onesearch-test.neu.edu/primo_library/libweb/action/search.do?vid=NUdev

**Comment by kmerguerian** [comment]
Thanks!
Are any fields required?  If so they should be indicated with a *

**Comment by kmerguerian** [comment]
There are two date fields: date, and publication date.  Should not have to enter the date twice.

**Comment by kmerguerian** [comment]
Seems like publication date doesn't do anything.  When I use that, I just get a journal-level link.  When I use the date itself, I get directly to the article.  
However, the link that says "choose date" doesn't do anything.

**Comment by kmerguerian** [comment]
You can put in a DOI and nothing else and it works!!!!   However, I didn't realize that until I had laboriously put in a bunch of other fields via cut and paste.  My suggestion would be to put the doi field FIRST on the form, then I could stop right there and it would be enough.  Most people who use the dpi for searching know that it is a unique number.  Same goes for PMID also. 

On the other hand, if you put a DOI into the big SoS search box, that works too.  So I'm not sure if we need the citation linker just for that...

**Comment by elizoller** [comment]
I've done some bootstrap-ifying of the citation linker but its totally up for changes/modifications obviously.
its on http://onesearch-test.neu.edu/primo_library/libweb/action/search.do?vid=NUdev then click Citation Linker
![screen shot 2015-02-06 at 4 23 35 pm](https://cloud.githubusercontent.com/assets/5439169/6087674/880ca3b2-ae1c-11e4-82f3-82e5241d7293.png)

**Comment by elizoller** [comment]
The choose date link should work now also. 
We can hide the publication date field if that isn't working or is duplicating.
We can manipulate the order of the fields with some JS also.
