### ISSUE TITLE
Reduce space between results on results page

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#118]
One suggestion that has come from a few of my colleagues is the number of results displayed in SOS. For example, if you search for 'nanotechnology' in SOS you can see six results on my display and you can see nine results for the same search using the BU Primo and ten using the BC Primo.

Could some changes be made so that version 1.2 increases the number of results displayed?

![screen shot 2014-01-10 at 11 02 12 am](https://f.cloud.github.com/assets/4663357/1888722/29955544-7a11-11e3-94e6-80be2a013ac5.png)
![screen shot 2014-01-10 at 11 02 18 am](https://f.cloud.github.com/assets/4663357/1888721/29954ce8-7a11-11e3-9e94-6cf3ca2e4495.png)
![screen shot 2014-01-10 at 11 06 15 am](https://f.cloud.github.com/assets/4663357/1888723/29999b36-7a11-11e3-9484-fc4b1f2d7a2f.png)

**Comment by elizoller** [comment]
BC and BU both do not display the author/editor information which adds a line to each of the results. Also, the choice to use buttons takes up some space. Their font in general is smaller and more condensed (less space between each line of text). In order not to alter these styles, I reduced the spacing between the buttons and the availability status- it's not much but it does reduce the height of each results by about 10px.
68b2e9b2442b8c4cdd933f954c8155a53fdcfd4b
![screen shot 2014-10-14 at 11 51 27 am](https://cloud.githubusercontent.com/assets/5439169/4631991/05d3a8bc-53ba-11e4-9b9a-6a57817b23f4.png)

**Comment by elizoller** [comment]
@winthropo is this enough or do we need to talk about other options?

**Comment by winthropo** [comment]
This is enough for this release. Thanks!
