### ISSUE TITLE
enable Google Analytics for SOS usage stats/info

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#119]
Would like a more elegant way to view basic usage information, e.g. through Google Analytics.  It's possible to get some usage information out of the BIRT Report Viewer in Primo's Back Office but it's beyond clunky.  

Details for using GA with Primo at http://www.exlibrisgroup.org/display/PrimoCC/Enable+usage+statistics+with+Google+Analytics+service+for+Primo+and+MetaLib+Plus

**Comment by nestochan** [comment]
### Summary of actions needed to implement it
- Get a Google Account.
- Register the Google account as a Google Analytics service subscriber.
- Create a Google Analytics account for each Primo / Metalib Plus instance (or an unique for all).
- Get the Javascript code and update **footer.html** pages.
- Update footer.html pages on server.
- Access Google Analytics service to see statistics reports or schedule report(s) to automatically be sent by email.

**Comment by bassettsj** [comment]
It is already there my friends. [footer.jade](https://github.com/NEU-Libraries/scholar-onesearch/blob/develop/templates/nu_footer.jade)

**Comment by nestochan** [comment]
:cool:  @kmerguerian can you plan to lead a discussion/tutorial some time soon on navigating GA -- as it pertains to :sos: with a mind for how we can enhance/group what we are currently collecting. 

@winthropo @jasf-  can you gather up google credentials for all in READ to have access to the GA data and i will grant them collaboration/read/analyze permissions for :sos:

how does that sound :question:

**Comment by jasf-** [comment]
:+1:

**Comment by nestochan** [comment]
any movement on this?
@kmerguerian @winthropo @jasf- 

shall we close otherwise?

**Comment by kmerguerian** [comment]
This is done.

Karen Merguerian
User Services
Northeastern University Libraries

On May 5, 2014, at 9:13 PM, "nestochan" <notifications@github.com<mailto:notifications@github.com>> wrote:

any movement on this?
@kmerguerianhttps://github.com/kmerguerian @winthropohttps://github.com/winthropo @jasf-https://github.com/jasf-

shall we close otherwise?
