### ISSUE TITLE
Adjust Call number font-weight to bold in  Browse screen results

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#120]
##### Tweak call number readability in results browse screen.

https://gist.github.com/nestochan/ee84490a12397434b27f

![screen shot 2014-02-04 at 2 20 56 pm](https://f.cloud.github.com/assets/2441612/2080846/49077a82-8ddb-11e3-84ab-a6f1b5a6ad51.png)

**Comment by bassettsj** [comment]
I think this one is done.

**Comment by nestochan** [comment]
indeed. :closed_book:
