### ISSUE TITLE
Add a link that takes a person to location help.

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#121]
- suppress barcode in location & status tab - move elsewhere? 
  --->item2 here is perhaps an alma configuration
- include location map or at least general info ('P-Z are on 4th floor')
##### this an example of a what BC has done - we need to figure out how do we add the locate link here--- maybe can be done with via Alma configuration/ and some tweaking of the VCUcss

![screen shot 2014-02-04 at 3 02 06 pm](https://f.cloud.github.com/assets/2441612/2080577/c519f324-8dd7-11e3-867b-eff6fd448339.png)

**Comment by nestochan** [comment]
targetURL: http://library.northeastern.edu/about/maps-and-directions/floor-maps

**Comment by jasf-** [comment]
Here's an alternative that might be easier, from University of Guelph:

![guelphlocationmap](https://f.cloud.github.com/assets/4661920/2141563/a39571fa-935a-11e3-99fd-208e008f5e06.png)

'Where is it?' leads to 

![locationmap](https://f.cloud.github.com/assets/4661920/2141567/aa30c2b2-935a-11e3-8aaf-55225c7faf95.png)

**Comment by kmerguerian** [comment]
Looks nice!   I think they have a set of searchable floor maps on their web site.  Somehow that "where is it" link generates a search on the web site and brings up the appropriate map.  Here's the map database
http://where.lib.uoguelph.ca/

I think this would be a fun project for a coop or workstudy for next semester.

**Comment by jasf-** [comment]
How BC did it (from Margaret Wolfe):

Glenn Manino (manino@bc.edu) did the ‘Locate’ back end. We had this in our old OPAC too.

To add the Locate link into Holmes via Alma go to:General Configuration -> Integration Profiles -> Add Integration Profile.

![locatelink1sm](https://f.cloud.github.com/assets/4661920/2162530/3952c656-94d3-11e3-8844-6b4b4fed4474.png)

![locatelink2sm](https://f.cloud.github.com/assets/4661920/2162534/3c99493e-94d3-11e3-99dc-ce5acd1d558c.png)

**Comment by nestochan** [comment]
:thumbsup:

**Comment by winthropo** [comment]
Removed 'supported libraries' from 'General Configuration -> Integration Profiles > Find It Link' configuration to disable Locate link from Get It until we have a new page to link to...
