### ISSUE TITLE
Last few changes, 

### ISSUE THREAD

**Issue by bassettsj** [NEU-Libraries/scholar-onesearch#123]
Well I think I got somewhere since the last meeting @nestochan 

I would deploy the latest version to the sandbox and see where that gets you. I don't think the permalink function works very well yet. I split the get title and get id into utility functions with a sanity check to see if the feeder function is even passing the right DOM element. I have the testing structure set up but am stuck on how to best implement that.

**Comment by nestochan** [comment]
:ok:
