### ISSUE TITLE
Change text of label 'open source in new window'

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#125]
We have some evidence that this 'open source in a new window' label is confusing the heck out of at least one class full of undergrads - particularly the word 'source'.

![opensourceinnewwindow](https://f.cloud.github.com/assets/4661920/2440388/261c5de8-ae07-11e3-932e-737b8727e8db.png)

Can the text of this label be changed to just say 'open in a new window'?

Per the below from the technical guide, I'm led to believe this may be a CSS change (?)
![exltabheader](https://f.cloud.github.com/assets/4661920/2440378/07eaa550-ae07-11e3-83df-819836dd545e.png)

It would be fantastic if we can get this fixed quickly, but I definitely realize that we're a day late and a web developer short...

**Comment by jasf-** [comment]
All set in production - closing.  Gracias!

**Comment by kmerguerian** [comment]
This is the documentation in case we need to do it again.  We had opened a case with Ex Libris to help us figure it out.

Case #00070544 
      Case Title :Open source in new window
Last comment: 
"Hi Karen, 

You can change this text in the Back Office>Code Tables>Front End>PNX Record Tab Messages. Then save and deploy.
