### ISSUE TITLE
Alerts for end-users: backend configuration and front-end restart required

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#127]
We are trying to get alerts working for end users' saved searches.  

Following ex libris ticket #00031284 I have changed the Primo Backend configuration according to Ping's instructions: 

In your Primo Back Office, SMTP-AUTH has been set to "True". 
(Primo Home > Advanced Configuration > General Configuration Wizard > Alert Subsystem). Can you change it to "False" and try the alerts? In general this should be set to "False" because the authentication is needed for SMTP sending alerts from Primo server. 

I made this change in production and staging.  It requires a front end server restart.

**Comment by nestochan** [comment]
- [ ] Staging FE service restarted
- [ ] Production FE  service restarted

**Comment by nestochan** [comment]
:ok:

**Comment by nestochan** [comment]
- [X] Staging FE service restarted
- [X] Production FE  service restarted
