### ISSUE TITLE
IE9 issues

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#128]
Using Browser Stack (Windows 7 IE9) it looks a bit wonky. See attached screenshot.

![ie9](https://cloud.githubusercontent.com/assets/4663357/2721798/76290a9a-c57f-11e3-8f54-5cfaf29f214c.png)

**Comment by nestochan** [comment]
@winthropo @jasf- 

when testing against IE9 use this url  :link: http://onesearch-test.neu.edu

> The problem, is that this is the side-effect where IE9 has a bug where is does not allow any individual CSS file to fully load if it contained more that X# of selectors(forget the arbitrary amount)  
> so if your CSS didn't pass your site styling would break in IE9. Microsoft's fix for this was to develop IE10 :grimacing: 
> You may remember that we encountered this very issue with an earlier release of our styling, and steven used 'bless' to break up our css into multiple files in order to circumvent this very bug.
> 
> However, starting with PRIMO 4.5 exlibris implemented CSS preprocessing to gather up all CSS files and customizations etc and 
> minify them (redundant because we already do this) furthermore, they gather everything into one single CSS file thus breaking our fix for IE9. :anguished: 
> 
> So the hacky solution for this is to have the URL include this option &wroDevMode=true in it.
> this bypasses the exlibris CSS treatments and keeps our fix in place. :metal"
> 
>  :ok:  In order to do this, we should where ever possible use:
> http://onesearch-test.neu.edu/  as the official link so that our redirect can push the vid and the wroDevMode prameters -- once in production http://onesearch.neu.edu (of course).

:see_no_evil::hear_no_evil::speak_no_evil: 
Mizaru -- Kikazaru -- Iwazaru

**Comment by winthropo** [comment]
Using http://onesearch-test.neu.eduhttp://onesearch-test.neu.edu/ the main page looks much better, but you still get some wonkiness once you do a search.

We should probably have a list of recommended browsers.

**Comment by nestochan** [comment]
Decision was mad to not support IE9 due to EXLibris's WebResourceOptimizations (WRO4j) 
which negates our Fix Via Bless. 
When this Feature Becomes optional this decision may be reconsidered

Closing for now...
