### ISSUE TITLE
iOS 7 issues

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#129]
Looks a bit wonky in iOS 7 on iPhone 5 and 5S. Tested in Browser Stack and on my iPhone 5. See attached.

![ios7](https://cloud.githubusercontent.com/assets/4663357/2722279/1eda65ca-c586-11e3-98fa-a36c06d930f2.png)

**Comment by nestochan** [comment]
@winthropo I believe this is ok now
close if you agree.

**Comment by winthropo** [comment]
@nestochan a thing of beauty. thanks. closing
