### ISSUE TITLE
Issues with permalink function 

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#130]
The permalink button in the tabs (pictured below) tends to just open the item in a new window - no permalink given.  The permalink under the 'actions' menu works fine.
![permalinktonowhere](https://cloud.githubusercontent.com/assets/4661920/2768753/3740579c-ca49-11e3-8938-17f5282c5fec.png)

Problem persists in Chrome and Safari.  Can't test in clean view since this tab isn't present there.

**Comment by nestochan** [comment]
@jasf- @winthropo 

For this feature to do what the <actions> does
would require a bit of consult with someone a little more versed in javascript...

**Comment by jasf-** [comment]
Gotcha.  What about this - would this be a possibility?

![permalinks](https://cloud.githubusercontent.com/assets/4661920/2881488/77c1120e-d483-11e3-9b7d-0dca8a847f3a.png)

**Comment by nestochan** [comment]
I would for now consider a 'hide' or perhaps a rename
and mark for future development.

Someone with JS chops could easily get this to get this to work the same way as the actions one does.
so it's not a total lost cause and would save a click later on.

++++++++++++++
ernesto valencia :black_joker:
northeastern university libraries
library technology services
617.373.3398 (ph)
617.293.9265 (mobile)

**Comment by nestochan** [comment]
Steven's Permalink will be hidden in the next release 
and may come back pending future development.

**Comment by elizoller** [comment]
Permalink button now functions using bootstrap modal b9cd08bc36f9c168c4aa8fe326931f84ed0dfe63 1a578115679ae3ed02f984bbce649507ce1922b4
Test on [dev view](http://onesearch-test.library.northeastern.edu/primo_library/libweb/action/search.do?vid=NUdev)

**Comment by nestochan** [comment]
@nestochan says :thumbsup:

**Comment by elizoller** [comment]
Modified action link functionality to match the button functionality 2aabeaf68903fb7d60f98461a91f8747937a64f9
