### ISSUE TITLE
Issues with citation function

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#131]
There are a couple of issues with citation function in our custom view (vid=NUdev).
1.  There is no way to close/escape from the citation window in our custom view.

![getmeoutofcitationwindow](https://cloud.githubusercontent.com/assets/4661920/2768896/b7d1a536-ca4a-11e3-9768-846202a73dff.png)
1.  The citation window occasionally opens in a spot where no interaction with it is possible.  It's hard to tell here, but in this screenshot the bottom of the citation popup has completely 'dribbled' off the bottom of the browser window.

![citationpopupcutoffsafari](https://cloud.githubusercontent.com/assets/4661920/2768900/cd206ca6-ca4a-11e3-87b8-b36284917665.png)
1.  Citation window occasionally opens with no content.  (I'm not convinced this is a huge deal as I've only seen this one a couple of times - just noting it for the record).

![citationwindownocontent](https://cloud.githubusercontent.com/assets/4661920/2768955/7647d346-ca4b-11e3-8381-8b82ddd78ad7.png)

Issues were noted in Chrome and Safari, and are not present in vid=NU_CLEAN:

![citationsafaricleanview](https://cloud.githubusercontent.com/assets/4661920/2768891/9feb9ba2-ca4a-11e3-9656-636e5617d636.png)

**Comment by nestochan** [comment]
@jasf- @winthropo 

did a bit of work on this and I think i've isolated the modal issues
with the SaveCitation Feature.
Check it out.

**Comment by jasf-** [comment]
Thanks nestochan, that looks better.
