### ISSUE TITLE
Primo date slider fix

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#134]
This fix from Notre Dame addresses some of our issues with the Primo 4.6 date slider.  

This shows the functionality in their system:  http://primo-fe1.library.nd.edu:1701/primo_library/libweb/action/search.do?mode=Basic&vid=NDU&vl(freeText0)=beethoven&fn=search&tab=nd_campus

Javascript for the fix is here:  https://github.com/ndlib/primo-date-slider

Background info here:  https://developers.exlibrisgroup.com/blog/Primo-4-date-slider-enhancements

**Comment by nestochan** [comment]
: thumbsup:

€

-------- Original message --------

**Comment by elizoller** [comment]
0b4cce620680b20f9d6dd9b2fa8851cfc5ad5cba Added to js files in gruntfile - appends js from [ndlib](https://github.com/ndlib/primo-date-slider)
See [onesearch-test](http://onesearch-test.northeastern.edu/primo_library/libweb/action/search.do?vid=NUdev)
