### ISSUE TITLE
Typo on home page

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#136]
On the home page, please remove the words "print materials" (highlighted in screenshot).
![screen shot 2014-09-03 at 1 42 43 pm](https://cloud.githubusercontent.com/assets/2442078/4139229/8b3b32fa-3398-11e4-88b6-11e1d471b9a6.png)

**Comment by elizoller** [comment]
Fixed by 76e7b76d28998b322755fe54dfe390b80862f6c5
