### ISSUE TITLE
Google Scholar - Primo - CSS issue

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#137]
Please see attached. To see this issue go to NEU, VCU, or BC's Google Scholar. Do a search. Click on getit @ NEU, VCU, or BC and you will see what appears to be a CSS issue. 

![articlesgooglescholarvssos copy](https://cloud.githubusercontent.com/assets/4663357/4166157/daa3dd26-3508-11e4-8ab3-415f8492fbc8.jpg)

**Comment by kmerguerian** [comment]
I'm not sure if this is a CSS issue or is more about what openURL data is being passed.  Because when I look up the same article in Ebscohost and "check for full text," the display in SoS is cleaner (although not all the authors are passed).

**Comment by kmerguerian** [comment]
I'm not sure if this is a CSS issue or is more about what openURL data is being passed.  Because when I look up the same article in Ebscohost and "check for full text," the display in SoS is cleaner (although not all the authors are passed).

**Comment by kmerguerian** [comment]
I'm not sure if this is a CSS issue or is more about what openURL data is being passed.  Because when I look up the same article in Ebscohost and "check for full text," the display in SoS is cleaner (although not all the authors are passed).

**Comment by kmerguerian** [comment]
I'm not sure if this is a CSS issue or is more about what openURL data is being passed.  Because when I look up the same article in Ebscohost and "check for full text," the display in SoS is cleaner (although not all the authors are passed).
