### ISSUE TITLE
Add to e-shelf

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#139]
Would it makes sense to add this enhancement? When you click on Actions>Add to e-Shelf the e-shelf icon changes to reflect this change -- to give feedback to the user.

![screen shot 2014-09-05 at 10 48 34 am copy](https://cloud.githubusercontent.com/assets/4663357/4167973/8b459b2a-3517-11e4-9b8c-59e762c86bac.jpg)

**Comment by elizoller** [comment]
fixed with 3e6f81cfbda90f6585715b74314fc7c1f6a755f8 
test on [dev view](http://onesearch-test.library.northeastern.edu/primo_library/libweb/action/search.do?vid=NUdev)

**Comment by winthropo** [comment]
:+1:
