### ISSUE TITLE
SOS sandbox: facet's "show more options" bug

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#143]
Primo 4.8.2

I see this in Safari and Chrome for facets with many values. Try searching for "steve jobs." Then go to the "subjects" or "authors" facet. Then click on "show more options."  You get a long list and you can't scroll down to the "continue" or "cancel" buttons. 

![screen shot 2014-09-08 at 12 35 25 pm](https://cloud.githubusercontent.com/assets/4663357/4188808/70bc4446-3776-11e4-9cbf-e2169f5c170e.png)

**Comment by elizoller** [comment]
Should be fixed by 1309a6681e4e75c773035477a52b12450550b9dc
The lightbox takes advantage of bootstrap modal js and css now- this helps with the functionality and positioning issues.

**Comment by winthropo** [comment]
Awesome. Works now! Thanks.
