### ISSUE TITLE
Add ebooks to virtual browse

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#146]
From SalesForce case #00101979.

Virtual browse uses the value in the Browse:Call Number section of the PNX. 

Right now, our Browse Normalization Rules only use the AVA field. If our ebook records have sufficient call number information, we can edit the Normalization rules for browse: call number so that information for ebook call number is also included in the browse section. Then, the ebooks can be found in a browse search, as well as displaying the virtual browse feature. 

See: Requirements for the Browse: Call Number field are outlined in the Primo Technical Guide: 

Technical Guide : Additional Configurations : Browse Functionality : Configuring the Normalization Rules : The Browse Section of the PNX 

Note that there are two required elements for the call number field: the display form of the call number and the Normalized form of the call number.

**Comment by kflachs** [comment]
The soft launch was successful- virtual browse now showing ebooks and electronic dissertations for any item that has a call number listed.   Stephanie is working on a streamlined method of adding in call numbers for ebooks whose vendors don't provide them.
