### ISSUE TITLE
SOS - IE9 - outdated browser message

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#147]
We would like this message about outdated browsers and http://www.whatbrowser.org on all SOS pages whenever someone comes from IE9. 
![screen shot 2014-10-17 at 10 35 49 am](https://cloud.githubusercontent.com/assets/4663357/4680665/ce2a6ee6-560c-11e4-8203-32ab89f00682.png)

So for example. We would like it if someone using IE9 got that error message when they clicked on this link below. Currently, I don't think they get that message when they click on that link using IE9.

http://onesearch.northeastern.edu/primo_library/libweb/action/display.do?fn=display&doc=NEU_ALMA51214273550001401&vid=NU&tab=default_tab

**Comment by elizoller** [comment]
The message was only showing up on the homepage because it was being appended to a div unique to that page, I moved it to append to the header so it will show up no matter what page the user lands on if their browser is out of date. 4a9c7f1f060dd76f53b852871727a63f150e2344

**Comment by winthropo** [comment]
Awesome. Thanks!
