### ISSUE TITLE
SOS "you don't know what you're missing." Sign in header. 

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#148]
Amira has expressed interest in adding something like this to SOS.  Harvard and University of Minnesota are two examples. 

http://beta.hollis.harvard.edu

https://www.lib.umn.edu

Search in their catalogs to see the header. 

![screen shot 2014-10-23 at 9 51 14 am](https://cloud.githubusercontent.com/assets/4663357/4754244/cba304ee-5abc-11e4-841a-e462dcd86e8f.png)

![screen shot 2014-10-23 at 9 59 34 am](https://cloud.githubusercontent.com/assets/4663357/4754255/dd488d04-5abc-11e4-9164-57ab5c215e91.png)

**Comment by winthropo** [comment]
READ will discuss whether or not we should go forward with this and if we do... finalize the wording. If we approve it we will label it "READ approved."

**Comment by jasf-** [comment]
This functionality is controlled in the Primo back office, and is called 'opening text' in the brief results tile.  It lives here:

![whereannouncementsliveinprimobackoffice](https://cloud.githubusercontent.com/assets/4661920/4847583/195e7a50-6054-11e4-9a1e-f62b50586f4f.png)

Notice there is also an 'ending text' which you can see successfully deployed in NU-CLEAN here:  
![signinendingtext](https://cloud.githubusercontent.com/assets/4661920/4847592/27d89b4c-6054-11e4-9593-ecf61ec2c50f.png)

I can't successfully deploy 'opening text' on either the NUdev view _or_ the NU-CLEAN view, while I can successfully deploy 'ending text' on both of those views.  

I have a vague recollection that we've had this problem before, and something about our implementation is obstructing the opening text - but I can't quite parse how that could be, if it's also happening in NU-CLEAN.  Any insights?

**Comment by elizoller** [comment]
I verified that NU_CLEAN is using the default files and it is.
I was able to deploy dev successfully by putting an opening text in the advanced search tile.
![screen shot 2014-10-30 at 1 22 12 pm](https://cloud.githubusercontent.com/assets/5439169/4848308/781a3ed0-6059-11e4-948f-99cbfa6de0da.png)

If we want a message to be displayed, it be system-wide not record-wide, though, right? Or am I misunderstanding the meaning of brief result?

**Comment by kmerguerian** [comment]
Just adding that this should go into effect when it is actually true that different results appear when you are signed it.  It seems this happens when the proquest databases are added.

**Comment by elizoller** [comment]
Did a little more poking around on this- the place that I originally thought this would go is not correct- 
that shows up like this:
![screen shot 2014-11-07 at 10 30 48 am](https://cloud.githubusercontent.com/assets/5439169/4955161/225b6cae-6693-11e4-960f-900d6271f245.png)
Looking at how Harvard has theirs in there- it is in the tile called `System Feedback`, the same place where the Did you Mean messages show up. Looking at the JSP that generates the output for the tile, the key seems to be here:

```
<c:if test="${not loggedIn and not searchForm.allFullAccess and (selectedScopeAccessibility==0 or selectedScopeAccessibility==1)}">
    <c:set var="feedbackMessage"><a href="${loginPdsUrl}">Sign in</a> to get results from more resources.</c:set>
</c:if>
```

I'm thinking there must be a setting associated with the search scope that I'm not finding that controls the `selectScopeAccessibility`.
UMN appears to do it all in the backend- no added JS for this functionality.
Harvard appears to use some JS to help out here

```
    //Adding the Sign-in Prompt on Brief results only
    if ($('#exlidSignOut').hasClass('EXLHidden') && $("#exlidFacetTile").length != 0) {
        var signInLink = $('#exlidSignIn a').attr('href');
        var msg = "You don't know what you're missing. <a href='" + signInLink + "'>Sign in<a/> to get results from all available resources.";
        $('#exlidHeaderSystemFeedback').append('<div id="exlidHeaderSystemFeedbackContent" class="EXLSystemFeedback"><strong>' + msg + '</strong></div>');
    }

    //Hiding the Sign-blurb from the main page if signed in
    if ($("#exlidSignIn").hasClass("EXLHidden")) {
        $("#signInHomeBody strong").hide();
    }
```

I think we could employ similar functionality as Harvard to achieve the desired effect when we're ready.

**Comment by elizoller** [comment]
"Sign in for enhanced features and results."

**Comment by elizoller** [comment]
Do you want this on every page or once a search has been submitted?

**Comment by winthropo** [comment]
I say push out the alert now (once search has been submitted). And maybe down the road we can improve how we advertise the benefits of signing in on the main SOS page.

**Comment by elizoller** [comment]
Pushed to production. Closing for now- we can reopen or do a new ticket when it comes time to make changes to the main page.

**Comment by kmerguerian** [comment]
Deb Mandel has asked if something can be done to make it clearer that the words "sign in" are a link.

**Comment by kmerguerian** [comment]
Actually forget that.

**Comment by elizoller** [comment]
I can make it underlined and/or darker?
![screen shot 2015-02-06 at 4 03 08 pm](https://cloud.githubusercontent.com/assets/5439169/6087463/b87c9cee-ae19-11e4-85f6-99476b883dda.png)

**Comment by jasf-** [comment]
We've been asked to change the wording to "Sign in for enhanced features and complete results".

**Comment by elizoller** [comment]
Fixed in dev, staging and prod.

**Comment by kmerguerian** [comment]
Complete?????

**Comment by jasf-** [comment]
Speedy!  Thanks Eli.

The 'complete' bit came from Amira.  She originally suggested 'full' - I was worried that 'full' might imply 'you'll be able to get full text for everything in these search results'.
