### ISSUE TITLE
Results list, title selections (Staging, vid=NUdev)

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#149]
In production, the search results list has clickable titles, when you select one, it goes to the full bib record, this is the correct behavior. 

In the development environment, the results list only has clickable titles when full text online is available, and in that situation, clicking opens up the confusing link resolver window.

I seem to remember we fixed this in production via the backoffice but I am not 100% sure.  I could not find a ticket in Salesforce with instructions.  

To compare, do a search on "orchids" and compare what happens in production with staging: which results have clickable titles, and what happens when you select that title.

**Comment by elizoller** [comment]
Changed brief result link to full record display instead of link to online resource on vid=NU and vid=NUdev on staging server
![screen shot 2014-10-30 at 1 40 36 pm](https://cloud.githubusercontent.com/assets/5439169/4848661/e2389526-605b-11e4-8f0b-c607b2653731.png)

**Comment by jasf-** [comment]
Lookin good!
