### ISSUE TITLE
Link resolution language (Staging, vid=NUdev)

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#150]
When you locate articles in Nature journals Online in the development environment, and you select "View Online" you get a warning message:

Article level linking is currently disabled at this time. Please access the journal above and then browse for this specific article. We apologize for any inconvenience.

Example:
http://onesearch-test.northeastern.edu/NU:TN_nature_a10.1038/500125d

**Comment by elizoller** [comment]
I don't know much about this issue except that box pulls in an iFrame from Alma. On the staging server it pulls from sandbox.alma and prod pulls from prod alma. This makes make me think it might be an Alma config thing.

**Comment by jasf-** [comment]
Is this a remnant from our ExL Salesforce ticket #00108911 re:  Nature article linking?

**Comment by jdevanna** [comment]
no longer an issue
