### ISSUE TITLE
Browse Search Styling - slight misalignment

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#152]
A minor stylistic point - in Chrome, the search box on the browse search is slightly higher than the buttons:
![browsesearchdev](https://cloud.githubusercontent.com/assets/4661920/4848015/1ef99f1e-6057-11e4-993a-009cf4fed311.png)

Here's how it looks in production:
![browsesearchprod](https://cloud.githubusercontent.com/assets/4661920/4848017/25e2fffa-6057-11e4-8c6a-2ddbe222aec3.png)

**Comment by elizoller** [comment]
Should be fixed by d0f05c4cde47b726d30b60b68f2939a084003777

**Comment by jasf-** [comment]
Yep, looking good, thanks!
