### ISSUE TITLE
Did you mean... (Staging, vid=NUdev)

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#153]
"Did you mean" seems overly suggestive and inconsistent in staging. 

For example
Keyword: "international relations" 
Did you mean "internationalization"? Um, no...

Keyword armenian 
Did you mean armenians?  
Well, not necessarily, and "Did you mean" with a plural is NOT suggested for other ethnic groups I tried like russian, yugoslav, israeli, australian, rwandan, egyptian

Keyword: Liar's poker
Did you mean liars poker? No, that would be grammatically incorrect.

Keyword: obama, barack
Did you mean obama barack well... Well, OK you can take out the comma but why if the results are identical?

**Comment by jasf-** [comment]
I'm just gonna leave this here.  :grinning: http://damnyouautosuggest.tumblr.com/

**Comment by elizoller** [comment]
I took a look at the settings for Did You Mean in Advanced Config > Search Config on staging and prod and they appear to be set the same way.
I don't think it would be related to issue #107 ?
Staging
![screen shot 2014-10-31 at 8 52 13 am](https://cloud.githubusercontent.com/assets/5439169/4860851/c92487ce-60fc-11e4-96d2-b74f61530209.png)
Prod
![screen shot 2014-10-31 at 8 52 19 am](https://cloud.githubusercontent.com/assets/5439169/4860853/c92c9888-60fc-11e4-9245-2ca5b4ba4df1.png)

**Comment by elizoller** [comment]
I ran these same searches again (in dev, staging, and prod) and am not getting any did you mean messages. Perhaps re-deploying fixed this issue?
Is anyone else still experiencing overly suggestive did you mean messages?

**Comment by winthropo** [comment]
@kmerguerian okay for me to close this?
