### ISSUE TITLE
Scopus links (Staging, vid=NUdev)

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#155]
The "times cited" link to Scopus is appearing.  This update of Primo is supposed to allow us to hide that.  

By the way, a hack was circulated on the listserv last week for how to use CSS to hide this regardless of the Primo version.

**Comment by kmerguerian** [comment]
Per Ex Libris email: 

Dear Jen Ferguson

A new comment was received for case #00106008:

Case Title :Remove Scopus as linked resource in citations tab?
Last comment: 
"Hello Jen, 

I believe that this is indeed a defect, which has been resolved in Primo 4.8. It is mentioned in the Primo 4.8 release notes under item 22271. 

I would like to take this opportunity to ask you to consider upgrading to 4.8. 
The newer version allows users to enjoy new premium features and improvements, and includes common defects fixes and we will be happy to assist you with any questions you have. 

As this is issue has been resolved, I am setting the case to closing. However, please feel free to add a comment if you have any questions or concerns; adding a comment will prevent the case from closing and bring it back to my attention. If no comments are added, the case will close after 14 days.

**Comment by kmerguerian** [comment]
From the Primo Listserv (though I'm not sure we really want to do this, I think the WOS citations are OK)

Hi, Qinghua.

At WWU, we're hiding the Times Cited tab with the following line of CSS in our customized file:

.EXLCitationsTab.EXLResultTab.EXLServiceConditionalTab  {
    display: none !important;
}

Good luck!
Lesley F. Lowery
Library IT
Western Washington University Libraries
(360) 650-4081

**Comment by jasf-** [comment]
Interesting.  I could swear I checked in staging after that exchange and links were pointing to WOS instead, but they're sure pointing to Scopus now.  

I can comment to re-open that ticket with ExL

**Comment by elizoller** [comment]
Can you send me an example where I can see something pointing to Scopus?

**Comment by kmerguerian** [comment]
http://onesearch-test.northeastern.edu/NU:TN_medline17272688

**Comment by elizoller** [comment]
The suggestion from the Primo listserv would hide the Times Cited button/tab entirely (whether or not it used Scopus). Is that the intention?
This is what is says in the 4.8 release notes about issue 22271:
![image](https://cloud.githubusercontent.com/assets/5439169/4907334/f73efa38-6460-11e4-87d7-125a5c801541.png)
That sounds like it isn't fixed?

**Comment by jasf-** [comment]
I opened a fresh ticket w/ Ex Libris (#00115621).
