### ISSUE TITLE
Times Cited link to WoS not proxied (Staging, vid=NUdev)

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#156]
The "times cited" links to WoS are not proxied, so off campus they will not work.  

Example
http://onesearch-test.northeastern.edu/NU:TN_wos000277543200002

Click on "Times Cited" button.  
Then click on either "View Citation" or "View in WoS".

**Comment by jasf-** [comment]
This issue (with ProQuest, not WoS) came up on today's PRIMO-DISCUSS-L Digest (#2014-247).  

Thread's a bit long to paste here, but one person suggested modifying with javascript, another suggested checking EZProxy prefix in links in Primo back office (Institution Wizard).

**Comment by elizoller** [comment]
The ezproxy prefix is set up in the Institution Wizard
![screen shot 2014-10-31 at 8 34 36 am](https://cloud.githubusercontent.com/assets/5439169/4860656/a4014b46-60fa-11e4-8f0b-1e2de7cf632c.png)
I'm not seeing a very quick solution via Javascript.
I'm wondering if Primo is smart enough just to prepend the ezproxy piece when it detects an off campus user? @kmerguerian Were you testing this from off or on campus?
@jasf- can you tell me how to view/subscribe to the PRIMO-DISCUSS-L Digest?

**Comment by jasf-** [comment]
Sure, good idea.  You can sign yourself up for PRIMO-DISCUSS at https://listserv.nd.edu/cgi-bin/wa?A0=PRIMO-DISCUSS-L

**Comment by elizoller** [comment]
thanks @jasf-

**Comment by elizoller** [comment]
Not sure how to approach this issue. The box with the WoS links also sometimes contains external links such as links to full resources- both open access resources and resources that require NU authentication. We don't want blanket proxy every link because open resources do not have proxy config.

**Comment by winthropo** [comment]
Since this hasn't been update in about 3 years I'm going to close it.
