### ISSUE TITLE
Refworks and Endnote export (Staging, vid=NUdev)

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#157]
I believe this is for Ex Libris/Salesforce

The citation export (Actions -- Refworks or Action--Endnote) for books duplicates the place names--basically it puts the place name in the publisher field.  For example
http://onesearch.northeastern.edu/NU:NEU_ALMA21171977720001401

renders in a bibliography as 
(APA)
Collaer, Paul. 1973. Music of the Americas; an Illustrated Music Ethnology of the Eskimo and American Indian Peoples. New York: New York, Praeger. 
or 
(Chicago)
Collaer, Paul. Music of the Americas; an Illustrated Music Ethnology of the Eskimo and American Indian Peoples. New York: New York, Praeger, 1973. 

(Chicago author/note)
Collaer, Paul. 1973. Music of the Americas; an illustrated music ethnology of the Eskimo and American Indian peoples. New York: New York, Praeger.

This is the RIS file.  PB should be "Praeger"

TY  - BOOK
ID  - NEU_ALMA21171977720001401
T1  - Music of the Americas
T1  -  an illustrated music ethnology of the Eskimo and American Indian peoples
AU  - Collaer, Paul
Y1  - 1973
N1  - Bibliography: p. 177-[196]
KW  - Eskimos -- Music -- History and criticism
KW  -  Indians -- Music -- History and criticism
PB  - New York, Praeger
CY  - New York
ER  - 

Here's how the publisher field should look (exported RIS from WorldCat)

TY  - BOOK
DB  - /z-wcorg/
DP  - http://worldcat.org
ID  - 588798
LA  - English
T1  - Music of the Americas; an illustrated music ethnology of the Eskimo and American Indian peoples
A1  - Collaer, Paul,, 
PB  - Praeger
CY  - New York
Y1  - 1973///
ER  -

**Comment by elizoller** [comment]
I don't know that much about how the metadata gets fed in to Primo but I'm thinking that the Publisher info (location and publisher name) as being pulled in is one field. This is verified by the fact that Publisher is one field in the Full Results Attributes
![screen shot 2014-11-04 at 3 12 36 pm](https://cloud.githubusercontent.com/assets/5439169/4907146/0ae4f79c-645f-11e4-81cc-94f8990470c9.png)

**Comment by sarahjeansweeney** [comment]
We can define what PNX field is used for RIS in the RIS field mapping table. Like Eli says the publisher field is a combination of publisher name and place, but I think we can create a custom display field for just publisher name and use that custom field in the RIS mapping table.

**Comment by kmerguerian** [comment]
There's a thread about this in the Primo listserv, including a suggestion to try to suppress the CY field (city? maybe?) in that table maybe since it's duplicated?  See "Exporting references to Refworks" starting around 10/23 with numerous contributions.
