### ISSUE TITLE
Link in emailed citation is not working (SoS Staging, vid=NUdev)

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#158]
This is the email I sent to myself generated from SoS in staging

The link was 

http://onesearch-test.northeastern.edu/primo_library/libweb/action/dlDisplay.do?vid=NU&afterPDS=true&institution=NEU&docId=TN_tayfranc10.1080/13530194.2014.942978

From: Library library@neu.edu
Date: Thursday, October 30, 2014 1:45 PM
To: GK Merguerian g.merguerian@neu.edu
Subject: Northeastern Libraries search items

Here is the information you sent from the Northeastern Libraries Scholar OneSearch.

Please do not reply to this message.

The Impact of the Palestinian Refugee Crisis on the Development of Amman, 1947–1958

Author: Hanania, Marwan D.
Is Part Of: British Journal of Middle Eastern Studies, 2014, p.1-22
Description: Amman has been relatively underexplored in the literature on Middle Eastern cities. Using a broad range of primary and secondary sources, this article addresses the impact of the 1947–1949 Arab-Israeli War on the Jordanian capital during the late 1940s and 1950s. A number of themes are examined: Amman during wartime; the settlement of the Palestinians; change and continuity in terms of Jordan's centralization process and Amman's urban growth; and, finally, the city's transformative socio-economic structures and political forces. This article argues that the influx of Palestinian refugees transformed the public culture of Ammani society, which became much more politicized than before. It is also argued, however, that the political developments of the late 1940s and 1950s were not sufficient to overturn the defining characteristics of Amman as it had existed before the 1947–1949 Arab-Israeli War. Article ahead-of-print.
Publisher: Routledge
Source: Routledge, Taylor & Francis Group
Identifier: ISSN: 1353-0194 ; E-ISSN: 1469-3542 ; DOI: 10.1080/13530194.2014.942978

**Comment by elizoller** [comment]
I can't seem to get a consistent reaction from clicking on those emailed links. 
I tested a whole batch of them and I was wondering if links to resources which the user would have to request from another library will not have this sort of functionality. But some other resources that we don't have access to seem to be working. Also occasionally, the link for the resource above works.
I'm not getting consistent results from prod on this either though.
