### ISSUE TITLE
squished text, locations tab (android/chrome)

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#159]
I'm seeing some squished text in the locations tab on Android using Chrome.  One example:  Mitochondrial  DNA:  Methods and protocols, by Jeffrey Stuart

**Comment by kmerguerian** [comment]
Another example of squished text on iOS with Safari

http://onesearch-test.northeastern.edu/NU:NEU_ALMA21138573860001401

[image.png]

Karen Merguerian
User Services
Northeastern University Libraries

On Nov 3, 2014, at 7:44 PM, "jasf-" <notifications@github.com<mailto:notifications@github.com>> wrote:

I'm seeing some squished text in the locations tab on Android using Chrome. One example: Mitochondrial DNA: Methods and protocols, by Jeffrey Stuart

**Comment by elizoller** [comment]
This section is an iframe of Alma. This is part of the Alma sandbox styling not being as responsive.

Staging with Alma Sandbox
![screenshot_2014-11-04-06-43-42](https://cloud.githubusercontent.com/assets/5439169/4901445/503913ec-6431-11e4-9cab-98b3d6e202fd.png)

Prod with Alma Prod
![screenshot_2014-11-04-09-44-49](https://cloud.githubusercontent.com/assets/5439169/4901442/4e981fc4-6431-11e4-9b66-2e5561ab9e05.png)

**Comment by jasf-** [comment]
I will put in a ticket to Ex Libris on this one.

**Comment by jasf-** [comment]
Just memorializing the response from Ex L:

"After looking into this issue, I see that the issue that you are experiencing is due to your otb_mashup.css file. This issue does not display incorrectly in the default view. I was able to use Firebug and change the elements .internalSection li and .width15 to make the text unsquished by changing the properties from margin: 0; to margin-left: 17px; for .internalSection li and width: 25% for .width15. This is just a quick change that was not permanent and was just to see if the change would make things look better. The way you would like to format the elements is up to you and your staff. However, the issue that you are seeing is due to the otb_mashup.css file and needs to be edited to correct the issue. "

Now the question is how to access that CSS file in the Alma sandbox.

**Comment by elizoller** [comment]
I think this may be related to Issue #110

**Comment by nestochan** [comment]
@jasf- @elizoller  close this right?

**Comment by elizoller** [comment]
I'm not longer able to replicate squished text in staging or production.
