### ISSUE TITLE
Permalink function dropping portion of URL

### ISSUE THREAD

**Issue by jdevanna** [NEU-Libraries/scholar-onesearch#160]
- Screenshot: ![image](https://cloud.githubusercontent.com/assets/9257706/4925229/63ba9140-6529-11e4-8638-b0699ac992c7.png)
- URL: http://onesearch-test.neu.edu/primo_library/libweb/action/search.do?fn=search&ct=search&initialSearch=true&mode=Basic&tab=default_tab&indx=1&dum=true&srt=rank&vid=NUdev&frbg=&vl%28freeText0%29=test&scp.scps=scope%3A%28NEU%29%2Cprimo_central_multiple_fe
- Browser: IE 10 on Windows
- Description: The Permalink function is dropping the protocol, domain, and path of SOS leaving only the record ID

**Comment by elizoller** [comment]
added IE10 fix with c467d924d52f4ea74ec031a95d5c1388543d6264
