### ISSUE TITLE
Clear and Search buttons appearing above advanced search box

### ISSUE THREAD

**Issue by jdevanna** [NEU-Libraries/scholar-onesearch#161]
- Screenshot: ![image](https://cloud.githubusercontent.com/assets/9257706/4925458/3c0a3ba8-652b-11e4-8936-623a2ccd2f3f.png)
- URL: http://onesearch-test.neu.edu/primo_library/libweb/action/search.do?mode=Advanced&ct=AdvancedSearch&dscnt=0&dstmp=1415219685454&vid=NU
- Browser: IE 10 on Windows
- Description: The clear and search buttons are appearing above the search fields on the advanced search page in staging.

**Comment by elizoller** [comment]
Should be fixed in ie10 with 4562168c698de9d5ed8480bea466010f6a77f67a
