### ISSUE TITLE
Refworks and Endnote export, author problems (Staging, vid=NUdev)

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#162]
When there are two authors, the second one is saved as an editor and is processing incorrectly as a Refworks file. 

This book has co-authors, but is showing as an author and an editor.
http://onesearch-test.northeastern.edu/NU:NEU_ALMA21165360850001401

  Here is the citation output

Kubiszyn, Tom. Educational Testing and Measurement : Classroom Application and Practice, edited by Borich, Gary D. 5th ed. ed. New York: New York : HarperCollins College Publishers, 1996. 

And here is a screenshot of what the import looks like as it comes into Refworks.

![screen shot 2014-11-05 at 5 23 59 pm](https://cloud.githubusercontent.com/assets/2442078/4927311/81832582-653a-11e4-81ce-ef46ae5c04a6.png)

Here is the same book correctly imported from WorldCat

Kubiszyn, Tom., Borich,Gary D.,. Educational Testing and Measurement : Classroom Application and Practice. New York: HarperCollins College Publishers, 1996. 

and a screenshot of the correct import into Refworks

![screen shot 2014-11-05 at 5 26 41 pm](https://cloud.githubusercontent.com/assets/2442078/4927369/ed6833c8-653a-11e4-8b39-1fb0c9548d78.png)

**Comment by elizoller** [comment]
I think that's the wrong first screenshot?

**Comment by kmerguerian** [comment]
Sorry about that.  Imported into Refworks from Primo:

![screen shot 2014-11-14 at 10 23 05 pm](https://cloud.githubusercontent.com/assets/2442078/5056348/e00e7282-6c4c-11e4-972e-8e16252bf6ba.png)

**Comment by winthropo** [comment]
Since this hasn't been updated in about 3 years I'm going to close it.
