### ISSUE TITLE
Northeastern dissertations displaying duplicate publication date in results browse (prod and dev)

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#164]
In the results browse, Northeastern dissertations show the publication date twice.  For example 
2008,2008

http://onesearch.library.neu.edu/NU:NEU_ALMA51191677750001401

![capture](https://cloud.githubusercontent.com/assets/2442078/4947229/677ab83a-6620-11e4-986f-1f519c45b4c9.JPG)

**Comment by kmerguerian** [comment]
More examples
http://onesearch.library.neu.edu/NU:NEU_ALMA21172081420001401
http://onesearch.library.neu.edu/NU:NEU_ALMA21144700050001401

**Comment by sarahjeansweeney** [comment]
Dissertations don't have typical publication statements, just dates. The Primo norm rules adjust for this by writing the dissertation note field into the PNX <publication> field ("Thesis (Ph.D.)--Northeastern University, 2008."), which includes the dissertation date. There are a few options to fix this:
The norm rules can be updated to remove the date from the dissertation publication statement ("Thesis (Ph.D.)--Northeastern University. 2008.")
The norm rules can be updated to stop using the dissertation note as the publication statement, leaving only the date in the publication statement for dissertations. ("2008.")

Keep in mind both changes would affect the result display and the Details and Related Links display.

**Comment by winthropo** [comment]
I'm going to close this old ticket. Still an issue. Please open if there are plans to fix it.

**Comment by kmerguerian** [comment]
I'm not sure I understand exactly what  "writing the dissertation note field into the PNX field" means...Does that mean the PNX publication date field? 

Is there a downside to the first option?  I would want there still to be an accurate publication date, so the citation will format correctly when people download Primo records into Endnote for click on the citation button etc.
