### ISSUE TITLE
Clear and Search buttons appearing within journal title search box

### ISSUE THREAD

**Issue by jdevanna** [NEU-Libraries/scholar-onesearch#165]
- Screenshot: ![image](https://cloud.githubusercontent.com/assets/9257706/4957760/a1fe2ca8-66a7-11e4-9157-9384c6d3b9cc.png)
- URL: http://onesearch-test.neu.edu/primo_library/libweb/action/search.do?mode=Advanced&ct=AdvancedSearch&dscnt=0&vid=NU_JOURNALS
- Browser: IE on Windows
- Description: The ejournal title search box clear and search buttons are floating within the search box instead of under it.

**Comment by elizoller** [comment]
should be fixed with c68cdf3de1dfc2d1d4abe22f17bf6a5141ee572b
