### ISSUE TITLE
Fix Labels on Fines

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/scholar-onesearch#168]
Fines and billing: currently the fines that display in Primo are reset to zero weekly when the balance is sent to the Bursar, even if the items are still accumulating fines.  Consequently students do not realize—until they hear from the Bursar—how much they have racked up.  If they don't log in frequently, they may get a false sense of security about what they really owe, as the fines disappear from the My Account page. 
Proposal: Change the statement in Primo to say Fines This Week instead of Fines.

**Comment by elizoller** [comment]
in BO > Advanced Configuration > All Code Tables > User Space Menu renamed `Fine &Fees` to `Fines This Week`
![screen shot 2014-12-05 at 11 27 59 am](https://cloud.githubusercontent.com/assets/5439169/5318873/d35124f6-7c71-11e4-8215-0d3cca0455a4.png)

Maybe it would be helpful to add a message on that page. Something like this?
![screen shot 2014-12-05 at 12 22 26 pm](https://cloud.githubusercontent.com/assets/5439169/5319702/7e21421a-7c79-11e4-851b-2a20034017c0.png)

This is up in [NUdev view](http://onesearch-test.northeastern.edu/primo_library/libweb/action/search.do?vid=NUdev)

**Comment by kmerguerian** [comment]
I would simplify the language even more:

These are your library fines for this week only. 
For total fines, check your Northeastern Student Account or contact circulation@neu.edu.

**Comment by elizoller** [comment]
deployed to prod
