### ISSUE TITLE
Renewable status when not renewable

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/scholar-onesearch#169]
Renewals: Items that display with a Status of "renewable" in Primo are often not renewable.  This may be due to a block, max days exceeded, a recall, etc…    In case you think these situations are rare, just ask someone who works in Access Services!  It actually happened to the student in my office right in front of me.  It turns out that "renewable" is not a status, it's more like a label for the loan policy associated with our stack books.  
Staff at the Help and Information desk can attest to what a difficult position they are put in when angry patrons object to having a "Renewable" book suddenly change to "non-renewable" when they try to renew it.  It is hard for them to provide good customer service when the language in Primo does not reflect our users' reality.  
Proposal: Change the status Renewable to something more generic like Circulating.  Alternatively, remove or hide it from the MyAccount display so the status doesn't show at all.

**Comment by elizoller** [comment]
The `Renewable` label/message is part of BO > Advanced Configuration > All Code Tables > Loans List Labels
It looks like from these messages, there is a message setup for if the renewals were successful and if only some of the renewals were selected. But I'm not able to find anything help in the Primo documentation.
I can hide the status column easily with CSS- is it the column labelled 'Status'?

**Comment by kmerguerian** [comment]
I can open a ticket to ask where the documentation is for this or what the loans list labels mean in Primo.

Karen

**Comment by elizoller** [comment]
That'd be great. Thanks!
The table looks like this in BO:
![screen shot 2014-12-05 at 1 52 15 pm](https://cloud.githubusercontent.com/assets/5439169/5321090/fda9ce92-7c85-11e4-9db0-0ffba12c3890.png)
The documentation that I found only relates to when they added the Renew All feature so it doens't talk about the Renewable/Non-renewable piece and where it get's that info from.

**Comment by kmerguerian** [comment]
Actually I see what is going on, I'll send a note around to READ with a proposal.

Karen

**Comment by elizoller** [comment]
From Tricia:
It appears the consensus from Access Services is to leave the default.loans.renew.Y (“Renewable”) field blank and that “Not renewed. Please return this item or contact the library” in the default.loans.renewed.failed field is fine.

**Comment by elizoller** [comment]
I pushed this out to the NUdev view but I don't have any items checked out to see if this is working.
http://onesearch-test.northeastern.edu/primo_library/libweb/action/myAccountMenu.do?vid=NUdev

**Comment by elizoller** [comment]
Pushed to prod
