### ISSUE TITLE
Link to DRS in SOS header

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#170]
Please add a link to the DRS (https://repository.lib.neu.edu/) in the header of SOS, alongside the e-journal finder and database links.

No rush on this; Patrick suggested it be deployed circa late January.

**Comment by nestochan** [comment]
:memo:    The link to the DRS will be changing soon in order to accommodate MarCom URL service naming requirements... new URL will be 

```
repository.library.northeastern.edu
```

**Comment by jasf-** [comment]
:ok_hand:

**Comment by jasf-** [comment]
Can we label the link 'DRS', with hover text that shows the whole 'Digital Repository Service' moniker?

**Comment by elizoller** [comment]
Like this?
![screen shot 2015-01-07 at 10 35 32 am](https://cloud.githubusercontent.com/assets/5439169/5648010/f2770e94-9658-11e4-82b1-e9223ab0ef00.png)
I could make the tooltip on the bottom instead too

**Comment by kmerguerian** [comment]
I would say yes to tooltip below

**Comment by kmerguerian** [comment]
The links on the top left are increasingly becoming a cloud or a swarm to me.  How can we make them more scannable?  Maybe by breaking them up more?  For example, those in the top row are clearly tools for using SoS, because they have icons and because that position is commonly used for tools on web sites. But they are overly similar to the ones in the second row, which represent links to services outside of the SoS environment?  I put some examples below of ways other web sites distinguish and group two sets of links.  I am not recommending any of these, just saying these are design tools available to us:

Use of color
![screen shot 2015-01-07 at 11 49 58 am](https://cloud.githubusercontent.com/assets/2442078/5649778/aca8366e-9666-11e4-912f-3c8858e763b6.png)

Using a different case or font for each line
![screen shot 2015-01-07 at 11 45 02 am](https://cloud.githubusercontent.com/assets/2442078/5649790/c59c6406-9666-11e4-97ed-5669fcfba41e.png)

Another example of distinguishing font and case
![screen shot 2015-01-07 at 11 43 19 am](https://cloud.githubusercontent.com/assets/2442078/5649893/ace42560-9667-11e4-91df-1dbee51cf6b5.png)

Use of figure and ground
![screen shot 2015-01-07 at 11 37 05 am](https://cloud.githubusercontent.com/assets/2442078/5649830/161a2bca-9667-11e4-898f-9e1fe7f8b584.png)

**Comment by kmerguerian** [comment]
Do we have to use an acronym that is not understood outside the library?  Can we call it "NU Repository"?  

I understand "repository" is not widely understood, but at least some people will know what it is.  DRS  is not at all understandable by anyone outside Snell.

**Comment by kmerguerian** [comment]
Should "Databases" and "DRS" have one of those icons to let people know they are taking you to another site?  If it can be worked in --I wouldn't want it to junk things up.  
![icon_offsite](https://cloud.githubusercontent.com/assets/2442078/5650109/5a391a3a-9669-11e4-834d-4c257c569763.gif)

**Comment by elizoller** [comment]
An idea:
![screen shot 2015-01-07 at 12 58 43 pm](https://cloud.githubusercontent.com/assets/5439169/5650531/39ddba44-966d-11e4-8aed-65deac90afa9.png)

**Comment by kmerguerian** [comment]
better!

**Comment by elizoller** [comment]
If we spell out Digital Repository Service:
![screen shot 2015-01-07 at 1 05 27 pm](https://cloud.githubusercontent.com/assets/5439169/5650608/ed25a378-966d-11e4-84e5-eee4779f5c33.png)

**Comment by elizoller** [comment]
Using the little icons
I think this crowds it a little bit
![screen shot 2015-01-07 at 1 12 17 pm](https://cloud.githubusercontent.com/assets/5439169/5650734/0a90d2ba-966f-11e4-9880-e0dca90289a9.png)

**Comment by elizoller** [comment]
Is the consensus to go with grey bg and spell out Digital Repository Service, no tooltip, no outbound icons? If so, I'll put it up in dev.

**Comment by kmerguerian** [comment]
Sounds like what we agreed on yesterday.

**Comment by winthropo** [comment]
Yep. Sounds right. Make it so please!

**Comment by elizoller** [comment]
I've got this up in Dev http://onesearch-test.northeastern.edu/primo_library/libweb/action/search.do?vid=NUdev

**Comment by kmerguerian** [comment]
Can the background color of the links be more of a grey and less of a blue?  Would rounded edges work better with the rest of our design?

Karen

**Comment by elizoller** [comment]
I used the same color as the panel headers when you complete a search and the same border-radius value as on the rest of the items. 
Are you able to see this?
![screen shot 2015-01-08 at 3 15 28 pm](https://cloud.githubusercontent.com/assets/5439169/5669864/34a2e8f6-9749-11e4-8383-7f6e5693e778.png)
![screen shot 2015-01-08 at 3 16 56 pm](https://cloud.githubusercontent.com/assets/5439169/5669884/6c4003c0-9749-11e4-9fdb-1cd75e5f2192.png)

**Comment by jasf-** [comment]
Hope you don't mind that I shared a screenshot with Patrick and Sarah.  Two thumbs up.  :+1: :+1:

**Comment by jasf-** [comment]
Just checked in with P&S - they've asked us to hold off on deploying the DRS link a while longer.  Let's revisit at the March READ meeting unless otherwise directed.

**Comment by elizoller** [comment]
Some more options:
![screen shot 2015-03-18 at 10 41 16 am](https://cloud.githubusercontent.com/assets/5439169/6711099/5cc0d198-cd5b-11e4-8d9b-427e3d8fb282.png)

![screen shot 2015-03-18 at 10 38 39 am](https://cloud.githubusercontent.com/assets/5439169/6711060/261f29e6-cd5b-11e4-8735-63bfef0fcafc.png)

![screen shot 2015-03-18 at 10 39 05 am](https://cloud.githubusercontent.com/assets/5439169/6711062/27ffcfa4-cd5b-11e4-928d-77c1bd0fb4b0.png)

![screen shot 2015-03-18 at 10 39 30 am](https://cloud.githubusercontent.com/assets/5439169/6711064/2c21aaee-cd5b-11e4-9089-071f3f8f96bb.png)

![screen shot 2015-03-18 at 10 42 05 am](https://cloud.githubusercontent.com/assets/5439169/6711118/72e5160a-cd5b-11e4-8479-47194c22ef17.png)

**Comment by jdevanna** [comment]
I'm personally a fan of option #2, clean and highlights the sign in option.

**Comment by kmerguerian** [comment]
Agree!

**Comment by jasf-** [comment]
Another vote for #2, and an update on deploying the DRS link in production.  

Sarah suggested we hold off a bit as they're still waiting for handles to point to DRS rather than IRiS.  We'll revisit sometime next month.

**Comment by elizoller** [comment]
Are we ready to push this out now?

**Comment by jasf-** [comment]
Just checked in with Sarah.  They're not quite ready yet; still waiting for the handles to be switched.  She'll let us know when they're ready.

**Comment by sarahjeansweeney** [comment]
The IRis handles have been switched, so it's safe to add the DRS link in the header. Thanks for being patient!

**Comment by jasf-** [comment]
Thanks, Sarah.  At your leisure, Eli.

**Comment by elizoller** [comment]
This is deployed to staging and prod
It may require a cache clear.
