### ISSUE TITLE
Guided Tour of SOS

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/scholar-onesearch#171]
Add a guided tour to SOS which walks through features of SOS 
Button to start tour on the right hand side of page 
Using bootstrap-tour

**Comment by jdevanna** [comment]
Lookin' good so far! Is it possible to have the tour navigate to a search results page to tour the facets and other features?

**Comment by elizoller** [comment]
Working on that now :smile_cat:

**Comment by elizoller** [comment]
I've put the start of a tour up in dev. The styling is out of the box so we can change that if we want. I opted to turn on the backdrop, but we can turn that off. I think if we decide to turn it off, we should modify the color scheme of the actual tour to be darker so it pops out of the paper more. The direction of the popover can be changed also. The content can also be changed, I just went off the existing guide to get a start.
http://onesearch-test.northeastern.edu/primo_library/libweb/action/search.do?vid=NUdev

**Comment by jdevanna** [comment]
Love it, Great job Eli!

**Comment by jasf-** [comment]
Agreed - this will be a fantastic addition.  Thanks!

**Comment by elizoller** [comment]
This is up in production.
