### ISSUE TITLE
Default Tab from Permalink

### ISSUE THREAD

**Issue by elizoller** [NEU-Libraries/scholar-onesearch#173]
Permalinks should take the user to the 'View Online' tab if an electronic resource and 'Location and Status' tab if a print resource.
This functionality works from search results page when you click on the title of the resource but the permalink always returns to the 'Details' tab.

**Comment by jasf-** [comment]
Ex Libris previously helped us fix a similar behavior in which any link from a third party database went automatically to the 'Details' tab rather than 'View Online'/'Location and Status'.  That behavior was addressed by changing settings in the Primo back office under Ongoing Config>Views Wizard>Tiles Config.  I just took a quick look there, but didn't see anything specific to the permalink function.

**Comment by winthropo** [comment]
I filed a SF case with EXL.

**Comment by winthropo** [comment]
Not configurable according to EXL need to submit an enhancement request.

**Comment by nestochan** [comment]
https://exlibrisgroup--c.na4.visual.force.com/apex/vf_case_view?id=5006000000cwTq2AAE

can a rewrite and reload of the url be done as to add &tabs=requestTab

-e

**Comment by elizoller** [comment]
I'll give that a whirl. Thanks!

**Comment by elizoller** [comment]
give it a whirl in NUdev view. I think it works!

**Comment by jasf-** [comment]
:star: :star: :star: !

**Comment by winthropo** [comment]
it works!!

**Comment by winthropo** [comment]
looks like it isn't working for online articles though. just print books?

**Comment by elizoller** [comment]
They have two different tab names I think. I'll should be able to fix that.
Also I will see about getting the Actions menu permalink fixed also.

**Comment by nestochan** [comment]
I think it's

tabs=requestTab   (books)
tabs=viewOnlineTab (electronic stuff)

:black_joker:

**Comment by elizoller** [comment]
I think I've got this working for both the permalink button and the actions menu for print and electronic resources. I pushed it to dev and staging.

**Comment by winthropo** [comment]
I tested both the permalink button and actions menu permalink for a few e-resources and print resources and it all worked.

I see no reason not to push it to production.

Thanks! Nice improvement.

**Comment by elizoller** [comment]
Deployed to production
