### ISSUE TITLE
Abstract links in Staging (4.9)

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#176]
Not that I think this is a big deal, but since I haven't yet found any other issues I thought I'd memorialize it in Git...

For the half dozen or so books I've looked at in staging, links to the abstract (under Details & Related Links tab) are opening a new SOS search results window rather than abstract-like content.

Example:  search both staging and production for Biology, by Sylvia Mader.

Biology by Sylvia Mader, in staging:  
Details & Related Links > Table of Contents:  resolves to Syndetic content
Details & Related Links > Abstract:  opens new SOS window

Biology by Sylvia Mader, in production:
Details & Related Links > Table of Contents:  resolves to Syndetic content
Details & Related Links > Abstract:  resolves to Syndetic content

**Comment by elizoller** [comment]
It seems that the href part of the link tag that actually tells the browser where to go is blank for the Abstract links in Staging. 
I double checked our JS to see if we were messing with those links but we aren't.
I also checked the mapping on that field and they are both (staging and production) mapped to MARC 20 subfield a parameter $$Tnu_syndetics_abstract$$Elinktoabstract
I'm thinking this might be another one of those issues with alma staging vs alma production.
Do you know if this was happening in staging before the upgrade to 4.9?

**Comment by jasf-** [comment]
Not sure whether it was happening in staging before 4.9.  I did see that the 4.9 release notes mention some enhancements in that general vicinity, but no idea if it's related:

"7. Increasing the visibility of Syndetics Table of Contents, libraries that subscribe to the Syndetics Table of Contents for indexing can now opt to display the TOC in the detailed tab of the related record."

I doubt that the abstract links are high-traffic items.  I'd be fine with waiting to see how this works once Primo production is upgraded to 4.9.

**Comment by elizoller** [comment]
I was thinking that the release notes were referring to actually displaying the table of contents in the Details tab instead of just linking out to them.

**Comment by kmerguerian** [comment]
I will check the backoffice for the third party links from syndetics and see if there is another setting we can adjust.

**Comment by elizoller** [comment]
Thanks!
