### ISSUE TITLE
"View online" for item in print and online (staging)

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#177]
Search "Creating the National Security State" 
http://onesearch-test.neu.edu/NU:TN_jstor_booksj.ctt7sz13&tabs=viewOnlineTab

There are print copies in the law library. 

in staging vid=NU, the "Check for full text" tab is empty.  

But in the clean view, the tab reads "view online" and the item is also available via a link to ebrary.  

The clean view is the desired behavior, I think.

**Comment by elizoller** [comment]
When I search for this record I am seeing the 'view online' and 'location and status' tabs.
![screen shot 2015-04-09 at 7 30 47 am](https://cloud.githubusercontent.com/assets/5439169/7065869/74a99250-de8a-11e4-972e-872433f3e891.png)
Were you on campus or off? Were you logged in? I'm wondering if these might have an affect on what we're seeing.
I see the correct tabs from on campus not logged in.

**Comment by winthropo** [comment]
I am also seeing them. However, they do sometimes take a few seconds to load — longer than in production. My guess is it has to do with Alma sandbox.

**Comment by elizoller** [comment]
This version of the book doesn't show up in production.
