### ISSUE TITLE
Permalink not working in staging environment

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#178]
This is a permalink for "Creating the National Security State."

http://onesearch-test.neu.edu/NU:TN_jstor_booksj.ctt7sz13&tabs=viewOnlineTab

When I click on the link, I get the note that I have to sign in to view this record, but it does not appear even when I sign in. 

I'm not sure if this is exactly the same issue that was supposed to be fixed according to the release notes for 4.9.

**Comment by elizoller** [comment]
I'm not able to create the same permalink you are. I'm wondering if this has something to do with being off or on campus or being logged in or not. When I visit this record from on campus not logged in, I am getting http://onesearch-test.northeastern.edu/NU:dedupmrg98275483&tabs=viewOnlineTab as the permalink which seems to work without the sign in loop.

**Comment by elizoller** [comment]
This version of the book doesn't show up in production.
