### ISSUE TITLE
Improvements to "find it" experience

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#182]
Updates were made to SoS to add a context-sensitive "find it" link on the staging site. 

The link points to the library's drupal site. 
If an item is checked out, no "find it" appears
If a law library book, it goes to an intermediary page about the law library
If an archives NU or archives MSS item, it goes to the Archives visitors page
If a Snell Stacks book, it goes to a new Snell Stacks informational page (new)
If Periodicals ... (new)
If storage, it goes to the "request an item from storage" page
Otherwise, it goes to the "floor maps" page

Changes made on the drupal dev site, to be added to production

Small edits to Archives Visitors page
Major edits to the floor maps page, including addition of a screenshot showing a call number
Rename the floor maps page
Rename the Request an item from storage page since that page has no requesting
creation of new specific location/collectinon pages 
Removal of 2 contexts from main floor maps page so the page has more "room"

TBD 
More pictures and text on the new location/collection specific pages. 
More specific pages if needed

**Comment by elizoller** [comment]
@kmerguerian the features are deployed to production. so just the updates to the pages need to be migrated over.

**Comment by kmerguerian** [comment]
OK, thanks!
Karen

**Comment by kmerguerian** [comment]
new pages are
New pages in dev:
Snell Stacks
Snell Periodicals 
Law Info

Also create in dev and production:
New Hub page

**Comment by kmerguerian** [comment]
Remove Find It button for "Storage" locations
We can test this--it may be it's preferred to have the button and have it point to the request from storage page
OR if possible, have that button prompt for a login/if you are already logged in, prompt for a direct request from the upper call number display.

**Comment by kmerguerian** [comment]
New pages complete in production.  Note the URL is /maps-directions/, not /maps-and-directions/

**Comment by elizoller** [comment]
Storage is hidden for now.
I will replace dev links with prod links. Then this should be all set.

**Comment by jasf-** [comment]
Nice work!

I'm going to send around an all-staff message later today about this weekend's production upgrade, and I'd love to include a screenshot of how the new 'find it' looks (from staging, obviously).  If you'd prefer I hold off on that part, that's fine too - just let me know in the next few hours.

**Comment by elizoller** [comment]
Sounds good to me. Thanks!

**Comment by jasf-** [comment]
:+1:

**Comment by kmerguerian** [comment]
I don't think it hurts to send around how it looks in staging if Eli has updated it.  Because people in the library may have suggestions for improvements that we haven't considered, or they may notice typos, mistakes, etc.

For example, I just tried it, and I'm wondering if the screen shot with the sample call number is so realistic students may think it pulled in _their_ book.  So I'm going to watermark that sample screenshot with the diagonal word "example."

Karen

**Comment by kmerguerian** [comment]
Reminder to address your email? to  "library-notify All libraries" if you wish to include the law library staff.

Karen

**Comment by jasf-** [comment]
Righty-o, thanks!

**Comment by jasf-** [comment]
Reopening to ask a question.

So for items like this one: 
http://onesearch-test.northeastern.edu/NU:dedupmrg98923592&tabs=requestTab

Which has copies in two locations (Snell & Law, in this case), the Law Library info page pops up, even though Snell has the preferential location in the real-time availability statement.  So users will not have seen that there's a copy in Law, unless they drill down into the locations & status tab.  (Did that make sense?)

I get why this is happening, just checking in to confirm that this is the desired behavior.

**Comment by elizoller** [comment]
The real-time availability gets updated after the page is loaded and this can change the location information. I have the find it button showing up after a 1 second because it has to wait for the real time availability to process.
I can increase that time and this would solve that problem but the find it buttons would not appear right away.

**Comment by kmerguerian** [comment]
Would an alternative option be to suppress the top "findIt" in cases where it says "and other locations"? Then users would have to open the "Location and status" tab to get more info and they would see all holdings...

Karen Merguerian
User Services
Northeastern University Libraries

On May 1, 2015, at 2:35 PM, "Jen Ferguson" <notifications@github.com<mailto:notifications@github.com>> wrote:

Reopening to ask a question.

So for items like this one:
http://onesearch-test.northeastern.edu/NU:dedupmrg98923592&tabs=requestTab

Which has copies in two locations (Snell & Law, in this case), the Law Library info page pops up, even though Snell has the preferential location in the real-time availability statement. So users will not have seen that there's a copy in Law, unless they drill down into the locations & status tab. (Did that make sense?)

I get why this is happening, just checking in to confirm that this is the desired behavior.

##

**Comment by elizoller** [comment]
Yeah we should be able to do that.

**Comment by jasf-** [comment]
Yeah that makes sense.  Thanks.
