### ISSUE TITLE
Online tour

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#183]
The "take a tour" button is not available in staging.  I don't know that it needs to be, but just want to note so that we're not forgetting or overwriting it when we move things from staging to production.

**Comment by jdevanna** [comment]
I see the take a tour button in all browsers and operating systems. perhaps a resolution issue?

**Comment by kmerguerian** [comment]
If it's expected behavior that it disappears at a certain resolution, that's OK,--then I would say yes, it does depend on resolution.  However, the threshold for it to disappear is different in staging and production.

**Comment by elizoller** [comment]
What view are you on in staging?

**Comment by elizoller** [comment]
I did hide the tour button under 979 px

**Comment by kmerguerian** [comment]
Looks the same in production and staging, not sure what I was doing before.  Just tested in FF and Chrome on the Mac
