### ISSUE TITLE
Layout of browse screen

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#184]
When you browse, the layout of the banner area in staging seems to be different--the field is narrower in width in staging, and the banner area is much looser and pushes the content down.  See screenshots below.  These are both in Chrome on the MacOS.  Compare the screenshots below: 

![screen shot 2015-04-15 at 11 22 40 am](https://cloud.githubusercontent.com/assets/2442078/7162060/7ed1a012-e360-11e4-809b-12d0ac3b0d7b.png)
![screen shot 2015-04-15 at 11 22 24 am](https://cloud.githubusercontent.com/assets/2442078/7162064/837dbf88-e360-11e4-8cd8-77832ef258de.png)

**Comment by kmerguerian** [comment]
Actually I'm seeing this difference on the search screen also.

**Comment by kmerguerian** [comment]
Correction: this is happening in Firefox, not chrome.

**Comment by elizoller** [comment]
It looks like one of those screen shots is zoomed in?
They have the exact same breakpoints. The only difference is the word staging which is set so we always know what site we're on.

**Comment by elizoller** [comment]
![screen shot 2015-04-15 at 1 39 45 pm](https://cloud.githubusercontent.com/assets/5439169/7165319/e9b39c0a-e374-11e4-84c1-84320a391a6c.png)

**Comment by kmerguerian** [comment]
Thanks!
