### ISSUE TITLE
for ebooks:  add link to ebook help guides in view online tab

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#186]
There is an enhancement request to add links to ebook help guides to help users navigate the wild and woolly world of ebook capabilities.

It would look something like this (pardon my seat-of-pants mockup):  
![ebookhelpguidemockup](https://cloud.githubusercontent.com/assets/4661920/7618427/f54e96de-f97f-11e4-8e18-4a5e2756e38f.png)

Links would go to Julie's e-book LibGuide:   http://subjectguides.lib.neu.edu/ebooks

It would be really slick if the ebook help link was vendor-specific, so that Ebrary items went directly to the Ebrary tab on the LibGuide, Knovel ebooks went to the Knovel tab, etc.

**Comment by elizoller** [comment]
Do you want the link in the View Online tab?

**Comment by kmerguerian** [comment]
Yes, I think this would be a uresolver resource.

Karen

**Comment by elizoller** [comment]
Ah so not a front end piece for me

**Comment by kmerguerian** [comment]
right--and yes, it has to be vendor specific, that number of tabs is not scannable.

**Comment by jdevanna** [comment]
I mocked this up in the sandbox, so the css is missing, but here is how it would look:

http://onesearch-test.neu.edu/NU:NEU_ALMA51194612840001401&tabs=viewOnlineTab

![image](https://cloud.githubusercontent.com/assets/9257706/7619462/db6d9114-f986-11e4-90e8-1ddba81bbeb0.png)

**Comment by jdevanna** [comment]
I can add this to any collections desired.

**Comment by jasf-** [comment]
That would be outstanding.  Maybe it would make sense to work from the vendors Julie has on the guide?  That would take care of most of the big collections, I think.

**Comment by jdevanna** [comment]
Now added to production for all the collections on the ebook guide:

http://onesearch.neu.edu/NU:NEU_ALMA51194612840001401&tabs=viewOnlineTab

**Comment by jasf-** [comment]
Very nice, thanks!

Is it possible to link directly to the vendor tab for each collection?  So that Knovel items would go to http://subjectguides.lib.neu.edu/content.php?pid=236943&sid=1957680 while AccessMedicine items go here http://subjectguides.lib.neu.edu/content.php?pid=236943&sid=4342271 ?

**Comment by jdevanna** [comment]
Of course, I'll do that now. Also, does anyone have an opinion about getting rid of the "public notes" text? It feels a bit redundant, I think it would look more polished if we replaced it with a notes icon like so:

![2015-05-14_0921](https://cloud.githubusercontent.com/assets/9257706/7632478/941f706c-fa1b-11e4-91eb-2e02e3099186.png)

**Comment by kmerguerian** [comment]
I like the idea of an icon, but that icon actually looks more like "text/content" than "help" to me-it might be a good one to use in front of the article suppliers in the resolver!    Also it looks like the help link is a listing under the heading Ebrary Academic Complete-Maybe the positioning or styling would make it clearer that they are both links, one to the e-book, and the other to the help? Maybe Eli could suggest an adjustment?

Karen

**Comment by elizoller** [comment]
You could use something like http://fortawesome.github.io/Font-Awesome/icon/question-circle/ for the help guide?

**Comment by jdevanna** [comment]
All the links have been updated to point to the vendor tab. Unfortunately I'm unable to suppress the public notes text from within Alma, I think this needs to be edited in the css, I could add the image in the note field with some html, but does it make sense to just add it into the css?

**Comment by jdevanna** [comment]
I mocked up the logo for the question mark for the ebook help guide in staging, I unfortunately cannot add images to the resource links though:
![image](https://cloud.githubusercontent.com/assets/9257706/7634852/854dcce0-fa2b-11e4-8df0-a22d550f4de3.png)

**Comment by kmerguerian** [comment]
Ooh, I feel an enhancement request coming on...

**Comment by jdevanna** [comment]
Good news, after a little digging, it is possible to remove the "public notes:" text from within Alma and add an icon to the full text collection name, however, the icon would be static, it cannot account for content type, so all ebooks, streaming media, and journals will all have the same icon. Any suggestions, ideas, do we think this is a good idea, put it up for discussion during the next READ meeting?

I have mocked up how this could look in staging, the spacing between the resource and the note would have to be updated in the css though:

http://onesearch-test.neu.edu/primo_library/libweb/action/dlDisplay.do?vid=NU&docId=NEU_ALMA51194612840001401&tabs=viewOnlineTab&fn=permalink

**Comment by kmerguerian** [comment]
Thanks, Joe, yes, it would be great to review in READ if we have time at the next meeting!

**Comment by winthropo** [comment]
We will have time to discuss at the next READ.

Would we be better off linking directly to the publisher/platform FAQ instead of the libguide? I've noticed the links to publisher/platform in the libguide don't always take user directly to the FAQ. And I think publisher might have more of what the user is looking for in this situation -- downloading, reading, etc. 

For example. Use these links instead of libguide. 

http://proquest.libguides.com/c.php?g=87048&p=559281
http://support.epnet.com.ezproxy.neu.edu//help/?int=ehost&ver=live&lang=en&feature_id=eBooks
http://help.safaribooksonline.com.ezproxy.neu.edu/faqs

**Comment by jasf-** [comment]
From READ 05/28/15:  We've decided to link directly to vendor help guides per Scott's comment above.  Joe will work to update links to go to vendor help guides.

**Comment by jdevanna** [comment]
Ebook help guides now point to vendor help pages.

The css in production is causing a line break after I put the icon html in though, so I have not implemented that yet, or else the links appear below the icon.

**Comment by jasf-** [comment]
:grinning:

**Comment by elizoller** [comment]
@jdevanna I think I have the CSS fixed for the icon to display inline with the text. Would it be possible for you to deploy the change in production and we can see if it worked?

**Comment by jdevanna** [comment]
@elizoller still appearing with the icon above the text:

http://onesearch.library.neu.edu/NU:NEU_ALMA51194612840001401&tabs=viewOnlineTab

**Comment by elizoller** [comment]
Can you try doing a hard refresh (CTRL/CMD + SHIFT + R)?

**Comment by elizoller** [comment]
It looks like this for me
![screen shot 2015-06-17 at 9 09 06 am](https://cloud.githubusercontent.com/assets/5439169/8207593/884bf3c6-14d0-11e5-9a60-613ef2578f05.png)

**Comment by jdevanna** [comment]
Just refreshed the page normally and it now displays correctly. Thanks!

**Comment by elizoller** [comment]
Awesome. Let me know if there is anything else I can do for this ticket.
