### ISSUE TITLE
Proceedings and conference papers: what should the u-resolver present? 

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#187]
Originally presented nothing -- not satisfactory!
Now presents an article ILL request, possibly leading to misunderstanding that user will get an article. 
Generally raises information literacy questions.  Will users understand they are ordering an abstract?  
Is it cost effective to order abstracts via ILL?  
Are abstracts sometimes available in our 3rd party databases?
Would reference want to try to locate the actual presentation in databases or on the Inter-tubes? 

Example:

Database or resource:  (http://onesearch.library.neu.edu/NU:RS_125508113)

Citation, if supplied:

Specificity and activity of Y-family DNA polymerases

**Comment by jasf-** [comment]
From READ 05/28/15:  This feels a bit 'beyond' us - not sure how to tackle this knotty problem.  

It would help if conference proceedings were properly presented as conference proceedings, not articles, because then the proper ILLiad form will be presented, which would clue in some users about the nature of these items.

I will look into which resources are presented correctly as conf proceedings in SOS, and which are showing as articles.

**Comment by jasf-** [comment]
Here's what I've been able to find out so far.  IEEE has got this business _down_.

Presenting as conference proceedings
- IEEE Xplore POP ALL
- IEEE Xplore Conferences
- ScienceDirect
- ACM Digital Library
- Cambridge Univ Press
- SwePub

Presenting as articles
- RSC Journals, RSC Gold, RSC Archive
- AIP Select

**Comment by kmerguerian** [comment]
Thanks for going through those Jen!  The other thing I  noticed is that in computer science and engineering, and electrical engineering especially, the proceedings papers are very robust and not just abstracts the way they tend to be to some extent in other subjects.  (Especially in the social sciences and humanities, the conference paper is often minimalist and is followed by a more in-depth journal article.) The medical and other sciences I'm still not sure about, but it's making me reconsider the positives of offering ILL, more than I thought when I started this quest.

**Comment by jasf-** [comment]
Yes, they're really all over the map in terms of length and content!
