### ISSUE TITLE
What am I searching

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#189]
Add a bullet saying 
View a complete list of publishers and providers whose content is included in Scholar OneSearch

The phrase "View a complete list" links to
https://library.northeastern.edu/get-help/tech-support/about-the-home-page-search/databases-and-resources-in-scholar-onesearch

**Comment by elizoller** [comment]
http://onesearch-test.northeastern.edu/primo_library/libweb/action/search.do?vid=NUdev
![screen shot 2015-05-21 at 2 38 09 pm](https://cloud.githubusercontent.com/assets/5439169/7756123/0ca15824-ffc7-11e4-9ca3-29d74c46a215.png)
Does that look right?

**Comment by kmerguerian** [comment]
Yes!
Karen

**Comment by elizoller** [comment]
Deployed
