### ISSUE TITLE
E-shelf behavior

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#192]
I have opened a ticket with ex Libris for the "save to e-shelf" feature, which does not work when clicking on a link in the weekly email alert.  

When selecting a link for an item in the catalog scope, the e-shelf option is not offered.  For example, see this email alert:

---

From: library@neu.edu
Date: June 18, 2015 at 12:00:12 AM EDT
To: g.merguerian@neu.edu
Subject: New search results: AW

There are new items in your saved search:4036

Note that 25 items are included in this email.
All new records can be found via the following link:
[lots of stuff removed here…]

Silver poetry
http://onesearch.northeastern.edu/primo_library/libweb/action/display.do?fn=display&doc=NEU_ALMA51218762790001401&vid=NU&tab=default_tab

---

It is technically possible to remove items from the action menu using CSS, so I just want to make sure we didn't remove "e-shelf" from the action menu deliberately in this record view, before ex libris spends a lot of time troubleshooting.

**Comment by elizoller** [comment]
It has something to do with the 'fn=' part of the URL. 
If you navigate to this item by searching the fn=search and if you use the link about the fn=display
If fn=search then the e-shelf buttons appears, if fn=display then it doesn't.
They're using the same view and thus the same CSS file. Also when I view the source, it's not just that the link is there but hidden, it just isn't in the render HTML at all.
But I'm not sure what the fn correlates to.
