### ISSUE TITLE
July release - 'Personalized' label messing with our lovely display

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#195]
If you choose to apply personalization to your search results, Primo helpfully inserts a 'personalized' label that messes up our lovely display.

![personalized](https://cloud.githubusercontent.com/assets/4661920/8697780/e8ffa46e-2ac5-11e5-83af-3a1cfa201236.png)

**Comment by elizoller** [comment]
Should we put it under the "Results" line?

**Comment by jasf-** [comment]
That might be better.  Though based on that other issue I just filed I'm wondering whether we should display it at all - not sure how accurate it is.  Further testing needed.
