### ISSUE TITLE
July release - View Online and Location and Status buttons not bringing up results

### ISSUE THREAD

**Issue by jdevanna** [NEU-Libraries/scholar-onesearch#198]
Using Jen's same search of "benevolent" I'm finding that the view online tabs are not connecting with the link resolver nor is the location and status buttons pulling information about the print holdings:

![image](https://cloud.githubusercontent.com/assets/9257706/8698849/46dfcad8-2acf-11e5-8e6d-50ac77973cdc.png)

**Comment by jasf-** [comment]
Are you seeing it now, Joe?  I am.  Maybe related to the Alma refresh problem addressed earlier this week(?)
