### ISSUE TITLE
SOS greyed out

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#202]
When I click on Show More Options in the upper-left corner. Then click on Cancel in the Personalize Your Results. SOS Staging remains greyed out. 

![greyeout1](https://cloud.githubusercontent.com/assets/4663357/8781188/9a129702-2edb-11e5-91ff-df2073bf5bc6.png)
![greyedout2](https://cloud.githubusercontent.com/assets/4663357/8781190/9c19f4be-2edb-11e5-9116-3de4c9a6884d.png)
![greyedout3](https://cloud.githubusercontent.com/assets/4663357/8781192/9dbf0e1c-2edb-11e5-8043-fbde72bbd9d1.png)

**Comment by winthropo** [comment]
We decided to completely turn off the feature causing this problem.

**Comment by elizoller** [comment]
By turn off do you mean its an option in the backend to disable it or do you want me to hide it with CSS?

**Comment by winthropo** [comment]
There is an option in the backend to disable it. CSS is not needed. Thanks!

**Comment by elizoller** [comment]
Awesome thanks

**Comment by jasf-** [comment]
If only all fixes were so simple :grin:
