### ISSUE TITLE
hyphen necessary to locate known item - change search engine config?

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#203]
**Scenario**

Reported by a colleague on behalf of a student who could not locate a known item:

The book in question is 'Demand-driven Forecasting A Structured Approach to Forecasting' by Chase.

Searching Primo for 'demand driven forecasting' does not raise this book anywhere in search results, even when scoped just to catalog items. It does display some articles and reviews written about this book, but not the book itself.

Searching for 'demand-driven forecasting' (with the hyphen in the title) does find the book.

**Questions**

Apparently we can control this based on an ExL knowledgebase article (pasted below).

My questions (_finally_) are:
- is this something that would be desirable for us to do?
- would doing so have unintended consquences?

**Knowledgebase article**

Hyphenated Terms Not Found Unless Hyphen Included
ARTICLE PROPERTIES
Type
General
Relevant for Customer Levels:

Environment
Primo 4
Main Product
Primo
Category

Product Version
4
Subject

GENERAL
Description
Problem Symptoms:
- Local records have hyphens in search fields (title, subject etc.)�
- A search for the term with hyphen (one-way), retrieves the record 
- However, a search for the term without the hyphen (one way), doesn't retrieve the record

Cause:
Remove Hyphens option is not checked.

Resolution:
1. In the Back Office, as the ExlibrisSupport user go to Advanced Configuration > Search Engine Configurations
2. Expand Miscellaneous option (click the plus sign)
3. Check Remove hyphens option
4. Save
5. Go to the Primo Home > Deploy All > deploy Search Engine Configuration
5. Re-index the database
6. Remove hyphens should remain checked.
ADDITIONAL INFO
File
Additional Info / Related Articles
1. "Remove Hyphens" can be seen and edited only via ExlibrisSupport user.
2. Background for this feature- from SP 3.1.1 RN, PRM-13972:
'The standard behavior of the Search Engine is to remove hyphens when normalizing data for indexing and when normalizing the search query. This is problematic for e.g. Finnish, because it has many hyphenated words. The "Remove hyphens" field has been added to Advanced Configuration > Search Engine Configurations > Miscellaneous page in the Primo Back Office. By default, this field is selected, keeping the current behavior of the system. If it is cleared, the system will not remove hyphens during normalization of indexing and search queries. ' 
3. "Remove Hyphens" option affects the index as well as the search. Running index while this option is checked will cause the records to be indexed without hyphens.

**Comment by winthropo** [comment]
@jasf- didn't we get the go ahead by READ to do this? I see in the Primo BO that it hasn't been implemented.

**Comment by kmerguerian** [comment]
Just to clarify, this setting/option removes hypens from the search as well as the index, right?  So after the change, if I type in "Egyptian two-step", I will continue to retrieve the recording titled "Egyptian two step" (no hyphen), correct?

If so, I would agree with this change.

**Comment by winthropo** [comment]
@jasf- Going to test in staging.

**Comment by winthropo** [comment]
Kristin is going to configure this in staging for @jasf- to test.

**Comment by kflachs** [comment]
This is configured in staging and now waiting for the re-indexing the database ...will be ready for testing Thursday morning (9/8).

**Comment by winthropo** [comment]
Thanks @kflachs

**Comment by kflachs** [comment]
Report shows that pipe successfully ran, so should be ready for testing.

**Comment by jasf-** [comment]
I finally had some time to take a look at this in staging.  Looks great to me.  I think we can push changes to production whenever time permits.

**Comment by kflachs** [comment]
I went to configure the hyphen setting in production, and the option is not available, like it is in the Sandbox.

![searchengineconfiguration](https://cloud.githubusercontent.com/assets/12529759/18586266/d294b0b8-7be9-11e6-8727-f27cfc0398c2.PNG)

**Comment by kflachs** [comment]
It turns out I could not see the option with Admin status.  When Scott changed it to SuperAdmin, I could see the hyphen option.  It has been deployed, so now waiting for database to re-index.

**Comment by jasf-** [comment]
I saw Julie's report a problem submission #2725 yesterday and was wondering - did this setting change?  Excerpt from her report below:

> Database or resource: Leadership-as-practice : theory and application (http://onesearch.library.neu.edu/NU:NEU_ALMA21227957470001401)

> Describe the problem:
browse title search does not retrieve this title unless you type the hyphens.

**Comment by winthropo** [comment]
Was the original fix for browse title search too?  @kflachs what do you think?

**Comment by winthropo** [comment]
Closing. Please open if necessary.
