### ISSUE TITLE
date facet auto-expanded in staging instead of material type facet

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#204]
In production, the material type facet is automatically expanded on the results page.

In staging, the material type facet is collapsed, and the date facet is expanded instead.  This is not ideal (even though the date facet is heavily used) because the date slider can be used while the facet is collapsed - so expanding it seems somewhat pointless.

I think I'm seeing this behavior consistently; can anyone confirm or deny?

**Comment by elizoller** [comment]
I am seeing the same thing. Probably something changed with the way the HTML is structured in the new release. I'll take a look and fix it back to expanding the material type facet. Shouldn't be a big deal.

**Comment by jasf-** [comment]
:+1:

**Comment by elizoller** [comment]
You still want the material type facet expanded by default, right?

**Comment by jasf-** [comment]
Yes please, and thanks!
