### ISSUE TITLE
SOS Tour:  Add 'get full text' to Take a Tour?

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#207]
Some of our users are still having trouble figuring out how to get to full text in SOS.  Would it be possible to show access to full text as part of our nifty 'Take a Tour'?

Maybe the tour could first highlight the View Online tab, then highlight the link to click to get to the full text.   If the existing tour can be edited, I'm thinking this new piece might work best between the existing bits about adding to eshelf and reporting a problem.  Other thoughts?

**Comment by elizoller** [comment]
The tour can definitely be edited. Just let me know what you want it to do/say.

**Comment by jasf-** [comment]
(Dang, you're fast, El!)

Something like this?  (wordsmithing/massaging welcomed)

(header) View Online (text) Here's where you'll find direct links to materials
(header) Link (text) Click here to start reading

It would really drive the point home if the actual opening of the article can be included in the tour if that's feasible.

**Comment by elizoller** [comment]
as in leaving SOS?

**Comment by kmerguerian** [comment]
Great idea IMO

**Comment by kmerguerian** [comment]
I just helped two people in a row at the Circ Desk who were looking at this screen for two different books, and asking me,

"So how am I supposed to get this book?"

[cid:d29544d3-e58b-4710-bee4-9a7f349ca0b0]

So in addition to the tour, maybe we need to revisit in READ having a header line in the link resolver window

```
To get this online, select one of the following:


        eBrary
```

Karen

**Comment by jasf-** [comment]
Yes, I think that would be a good addition!

Just saw your question, Eli.  Yes, as in showing the new window with the article that opens after clicking the link.  Dunno if it's possible.

**Comment by elizoller** [comment]
I don't think we'll be able to reach into the iframe.
See the tour on dev http://onesearch-test.northeastern.edu/primo_library/libweb/action/search.do?vid=NUdev

**Comment by jasf-** [comment]
Belated thanks, Eli - I like the tour addition.  

Maybe this issue should be retitled 'how can we better lead people to full text in general'?

Copied from a library-help ticket (#14886) - this user clearly describes that they don't realize that the link in the u-resolver is their path to full text:

"Unable to open full text. The article space remains blank when I open it. I tried clicking view online and open this space in another window but all the space says is SAGE 1999. You can see what i mean in the attached screen shot."
