### ISSUE TITLE
Different search results - library home page SOS box vs. onesearch.neu.edu

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#209]
Same search is returning slightly different results depending on starting point - library home page SOS box vs. onesearch.neu.edu

Scenario:  search 'endocrinology human behavior', no changes to dropdown, not signed in.
#1:  Video of search starting from library home page:  http://screencast.com/t/VaqKwDLZ1cOf
#2:  Video of search starting from onesearch.neu.edu:  http://screencast.com/t/hCG6N8SZ

Couple of things to note:
- Numbers of results vary quite a bit (731 results from library home page search, 981 from search starting at onesearch.neu.edu)
- Of more concern, look at results page.  The second result from search #2 - Endocrinology and Human Behavior by Goldstein, with red 'check for full text' icon - does not appear anywhere in the first five pages of results of search #1.  

Any idea what might be going on here?

**Comment by kmerguerian** [comment]
I can replicate this.  If I add  
&institution=NEU

to the URL generated by the home page search box, I seem to be able to generate the same results as if I am doing a native search.

**Comment by elizoller** [comment]
The homepage search box generates this url: `http://onesearch.northeastern.edu/primo_library/libweb/action/dlSearch.do?institution=NEU&vid=NU&group=GUEST&onCampus=true&displayMode=full&query=any%2Ccontains%2Cendocrinology+human+behavior&primoQueryTemp=endocrinology+human+behavior&search_scope=everything_scope&op=Search` 

Native SOS generates this url: `http://onesearch.northeastern.edu/primo_library/libweb/action/search.do?fn=search&ct=search&initialSearch=true&mode=Basic&tab=default_tab&indx=1&dum=true&srt=rank&vid=NU&frbg=&vl%28freeText0%29=endocrinology+human+behavior&scp.scps=scope%3A%28NEU%29%2Cprimo_central_multiple_fe`

**Comment by elizoller** [comment]
I am wondering if they are doing different searches.
It looks like the homepage is doing a query for any field contains endocrinology human behavior where the native SOS search is doing a free text search (not really even sure what that means?)
Also might be worth noting the scope differences 'everything_scope' for the homepage and 'primo_central_multiple_fe' for the native SOS

**Comment by kmerguerian** [comment]
Notice when you start on the library home page, then go to page 2 of your results, the number changes to the higher number--as if the search is being rerun, correctly

**Comment by kmerguerian** [comment]
Another thing--the admonishment to sign in for enhanced results does not appear when you launch your search from the home page.  (Not sure if this is new with this release or I just didn't notice and it had disappeared before).

**Comment by elizoller** [comment]
When you do the homepage search and then click to the second page and back to the first page, it shows results like the native SOS search and produces some sort of conglomerate url. 
`http://onesearch.northeastern.edu/primo_library/libweb/action/search.do?ct=&pag=&indx=1&pageNumberComingFrom=2&op=Search&vl(2622881UI0)=any&primoQueryTemp=endocrinology%20human%20behavior&query=any%2Ccontains%2Cendocrinology%20human%20behavior&fn=search&indx=11&dscnt=0&search_scope=everything_scope&scp.scps=scope%3A(NEU)%2Cprimo_central_multiple_fe&displayMode=full&vid=NU&onCampus=true&ct=Next%20Page&institution=NEU&tab=default_tab&vl(freeText0)=endocrinology%20human%20behavior&dstmp=1452105560215&group=GUEST`
I will look at the search box and see if we are missing parameters or have the wrong ones.

**Comment by jasf-** [comment]
:+1:

**Comment by elizoller** [comment]
Looked at this some more. Still no solution. No matter which parameters I add/remove/change, I can't seem to get this search to produce the same results in deep search and regular search. I've looked the EXL documentation and past listserv emails but can't find any solutions. I think it might have something to do with the scope or the actual query because deep search uses `search=any,contains,endocrinonology+human+behavior` and `scope=everything_scope` where regular search uses `vl(freetext0)=endocrinology+human+behavior` and `scp.scps=scope:(NEU),primo_central_multiple_fe` and transferring those values from one search to the other either breaks the search entirely or doesn't change the results at all.

**Comment by elizoller** [comment]
I put in a ticket with SOS and they got back to me with a response.
"In your regular (search.do) search you include results with no full-text, but your dlsearch.do searchbox is not taking this into account. " 
We need to add a parameter called pcAvailbiltyMode=true to include this. (yes the correct parameter has availability spelled availabilty)
I have tested this locally and it seems to fix the problem. I will put a patch up on the library website today.

**Comment by jasf-** [comment]
Aha.  Thanks for shepherding this through, Eli!

**Comment by elizoller** [comment]
Deployed to production
