### ISSUE TITLE
Virtual browse display in production

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#210]
The virtual browse display is knackered in production post-November release.  Covers are showing as a double row and can't interact with them.  

Screenshot is from Mac/Chrome, but same issue is occurring with Mac/Firefox and iPad/Chrome.
![virtualbrowsepostupgrade](https://cloud.githubusercontent.com/assets/4661920/11932825/16b1e444-a7c6-11e5-9eb8-5489f78cf9aa.png)

**Comment by elizoller** [comment]
What did this look like before?

**Comment by jasf-** [comment]
If you pop the window out it displays correctly/like it did before.

**Comment by elizoller** [comment]
It seems the Javascript which is dynamically created to make the gallery function is not being created. Looking into it.

**Comment by elizoller** [comment]
Narrowed this down to an issue with the dateslider plugin we use from ndlib. Now digging into that.

**Comment by elizoller** [comment]
There is at least one issue with primo having renamed a function that breaks the dateslider. There are additional issues with dateslider that I'm not able to resolve quickly.
I am wondering if an acceptable solution would be disable dateslider from ndlib (it still works to some degree with the out of the box primo dateslider) until i can fix the dateslider to cooperate with the newest release?

**Comment by jasf-** [comment]
Works for me!
