### ISSUE TITLE
Languages offered in "personal settings"

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#211]
Remove:
Deutsch

Add:
Chinese
Korean
Spanish

If it can be added to the enhancement list for Ex Libris for the future, we would like to have:
Arabic 
Hindi

**Comment by kmerguerian** [comment]
![2016-01-11_16-26-00](https://cloud.githubusercontent.com/assets/2442078/12248364/e77d7f5e-b886-11e5-818b-d96df423a6d1.png)

**Comment by kmerguerian** [comment]
Checked today--his has been done in staging. 

To do in production, look in FE mapping tables under Language. Check the languages you want.

Chinese
English
French
Hindi
Spanish
Taiwanese Chinese

**Comment by winthropo** [comment]
We added languages to production. Have a look.

**Comment by kmerguerian** [comment]
Changing to French.  (I had it set on French for about a week). 

Change the dropdown to "Library catalogs"
Do a search
In the results, the buttons "Consulter" (View online) and Details (Details) do not work.
Permalink does work

This can be replicated in the NU_CLEAN view.

**Comment by winthropo** [comment]
@kmerguerian did you open a ticket with Ex Libris? What's the latest?

**Comment by kmerguerian** [comment]
Yes, sorry this was fixed and closed by ex libris, case 00212736
