### ISSUE TITLE
Advanced journal search

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#212]
In the advanced journal search, the first dropdown allows you to choose Title [contains] or [is exact].

However, the second box gives you a third option, [starts with].  Can that be available in both search boxes please?

**Comment by jdevanna** [comment]
This appears to have been fixed.

**Comment by winthropo** [comment]
Can we close this?

**Comment by winthropo** [comment]
@kmerguerian @jasf- This hasn't been fixed. Is this still something you want fixed?

**Comment by jasf-** [comment]
Interesting - seems to be fixed in the new UI.

<img width="495" alt="fixedinnewui" src="https://cloud.githubusercontent.com/assets/4661920/18889307/611bd094-84ca-11e6-936c-bcb51ea38caf.png">

**Comment by winthropo** [comment]
doesn't appear to be an issue in new UI. closing.
