### ISSUE TITLE
SoS notification for services affected by NA003 cutover

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#213]
It's early yet, but I thought I'd open the question of how we can notify users within Scholar OneSearch of  the NA003 cutover, through a banner, popup or some such.

Something like this, maybe?  (Wordsmithing welcome)

"Due to scheduled maintenance March 6-7, 2016, not all Scholar OneSearch services may be available."

Thoughts, amendments, edits?

**Comment by jasf-** [comment]
What if for the outage - maybe starting late in the day on Friday March 4th - we temporarily hijacked the 'sign in' message referenced [here](https://github.com/NEU-Libraries/scholar-onesearch/issues/148)?  Would that be feasible, Eli?

**Comment by elizoller** [comment]
Yeah. I can just change it so it isn't dependent on whether the user is signed in and shows up all the time instead.

**Comment by jasf-** [comment]
That sounds great - thanks!

**Comment by winthropo** [comment]
At our READ meeting today we agreed to use the same language found on the site.

"Scholar OneSearch will be down for maintenance starting Sunday, March 6 at midnight. Certain features may be unavailable."

**Comment by winthropo** [comment]
Funny. It is a bit tricky to clearly articulate when the change happens. I think the message below is the clearest. I sent a note to Jennie to get the message on the site revised to this. Please use this on the SOS banner, thanks. 

"Scholar OneSearch will be down for maintenance starting Sunday night, March 6, at midnight. Certain features may be unavailable."

**Comment by elizoller** [comment]
Deployed

**Comment by jasf-** [comment]
Looks good - thanks Eli!
