### ISSUE TITLE
e-journal finder link

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#217]
READ agreed to replace the E-journal Finder link on the E-journal Finder page with a link to the Journal Title Search page and label this new link Journal Title Search. -Scott

![screen shot 2016-03-18 at 3 57 27 pm](https://cloud.githubusercontent.com/assets/4663357/13891012/f8c35298-ed24-11e5-9fae-38bec6ecff8c.png)

**Comment by kmerguerian** [comment]
I realize this goes beyond this ticket, but I forget why this is called a Journal Title search?  It's conveniently set up to search author/creator, subject, keyword, and ISSN, as well as title.

Karen

**Comment by winthropo** [comment]
I think we just borrowed the name from BU. I'm not married to the name. BU allows for these searches:

keyword
title
issn
oclc#
call number
