### ISSUE TITLE
May release - display looking cluttered

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#218]
That's a lot of little boxes crowding the display now.  Any ideas for how to streamline this and make it look a little better?

![lotsaboxes](https://cloud.githubusercontent.com/assets/4661920/16008762/79982680-3147-11e6-821b-6c464db0f05b.png)

**Comment by kmerguerian** [comment]
Maybe the "citations" and "cited by" could be distinguished from the rest of the buttons using space, color, etc?
And View Online/Check for full text maybe should have it's own singularity somehow?

Karen

**Comment by nestochan** [comment]
how does this render in the new UI? if at all?

ě

On Mon, Jun 13, 2016 at 11:50 AM -0400, "kmerguerian" <notifications@github.com<mailto:notifications@github.com>> wrote:

Maybe the "citations" and "cited by" could be distinguished from the rest of the buttons using space, color, etc?
And View Online/Check for full text maybe should have it's own singularity somehow?

Karen

**Comment by jasf-** [comment]
Good question.  If it's in the new UI, I'm not seeing it.

**Comment by elizoller** [comment]
I don't think they've implemented citation trail in the new UI? I'm not seeing it either.

**Comment by elizoller** [comment]
As far as the visuals of the buttons, I think it depends a little on how prominent you want these buttons. Could we consider collapsing them into one button and having it open something like the details tab does. Or could we add these links to the details tab somewhere (or somewhere else) instead of using such prime real estate?

**Comment by jasf-** [comment]
Closing since we're not enabling citation trail for now.
