### ISSUE TITLE
Indexing libguides: icon

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#220]
Associate the libguides with an icon of some kind, maybe use the web site icon if it's a web site, or use the web site icon with a label like "Research guides."  I realize this is not helpful, but I don't know who makes the decision about what they should be called.

**Comment by nestochan** [comment]
Possible Icon candidate: modified libguide icon on grey background
![screenshot 2016-07-08 10 34 32](https://cloud.githubusercontent.com/assets/2441612/16709127/7130cd92-45d5-11e6-9246-66ff2dde9325.png)

**Comment by kmerguerian** [comment]
It looks like a phone to me...

Karen

On Jul 9, 2016, at 1:04 PM, "nestochan" <notifications@github.com<mailto:notifications@github.com>> wrote:

Possible Icon candidate: modified libguide icon on grey background
[screenshot 2016-07-08 10 34 32]https://cloud.githubusercontent.com/assets/2441612/16709127/7130cd92-45d5-11e6-9246-66ff2dde9325.png

##

**Comment by kmerguerian** [comment]
OK, OK,  I will ask Jen Robbiano for something...

**Comment by nestochan** [comment]
Jack likes this one 😍 
But yes, definitely have marketing take a stab at this.
Icon size is 38px by 56px.

![nu-libguidesred](https://cloud.githubusercontent.com/assets/2441612/16773810/550764a6-4827-11e6-985d-d5c9bb5cf2b9.png)

**Comment by kmerguerian** [comment]
It looks a little more like a computer and less like a phone now …

I never said I didn’t like it by the way!  I just didn’t understand what it was for, because a phone doesn’t communicate the notion of a guide to me.

I will ask Jen R. what she thinks.

Karen

**Comment by kmerguerian** [comment]
Also if no one minds, I may ask if she has someone who can make it greyscale to match the other ones.  (Or they could be all red.)

**Comment by jasf-** [comment]
Chatted about this at READ 08/03 - icon is in process.

**Comment by winthropo** [comment]
@kmerguerian has the icon and will add it here.

**Comment by kmerguerian** [comment]
![subject guides icon-04 1](https://cloud.githubusercontent.com/assets/2442078/18328548/3a3817a6-751d-11e6-8df4-57f065e871ca.png)

I'm assuming the text gets added on by someone else?

**Comment by nestochan** [comment]
@kmerguerian : I believe the text is in a table in the primo_BE .
