### ISSUE TITLE
Indexing libguides: publication date

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#221]
The created date is a problem to display.  The guides are updated constantly, and the created date gives an impression that's the date of the guide, but it's not in any meaningful way.  Also the "created date" pushes the guide down in the results ranking compared to if it were the date last updated. 

Dublin core says DATE can be any date in the life cycle of the resource.  Arguably, a guide first published in 2008 and updated last in 2016 was created, in its current version, in 2016.   

This ticket proposes if the last updated date can be shown in SoS, that is the most helpful and accurate information we can provide.  

Otherwise, I would manually update each date on upload to the current year.  All the published guides have been updated in 2016 except for two belonging to Amanda (and I will tell her to change a comma or something so hers will be, too).

**Comment by nestochan** [comment]
dc:date as passed by libguides is the creation date.
at present the update date is in header, but unable to expose it via NormRule as the datasource is currently configured. options here may be:
- [ ] Look into re-engineering NR, and Datasource
- [ ] apply a static constant value with just the current year
- [ ] omit this date entirely

**Comment by winthropo** [comment]
I vote for applying a static value - current year. Any objections?

**Comment by kflachs** [comment]
Since there seems no way (at this time) to capture the date, a static value would work.
If the encoding would change so that the most current date could be captured, then we could consider changing it.

-Kristin

**Comment by nestochan** [comment]
updated NR to add current year to libguide records
