### ISSUE TITLE
Disable Primo Citation Trail on July 31

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#225]
I won't be able to do this on Sunday, July 31. If someone else could do it that would be great. 

By default, this Citation Trail functionality is enabled in the Views Wizard (Primo Home > Ongoing Configuration Wizards > Views Wizard) for each view. You may disable this functionality by clearing the Enable Citation Trail check box.

**Comment by jasf-** [comment]
I can do this on the 31st.

**Comment by winthropo** [comment]
Thanks!

**Comment by jasf-** [comment]
Done.
