### ISSUE TITLE
Link to librarian image for subject guides instead of material type icon

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#227]
Evan Simpson has suggested instead of using a standard material type icon, we use an image of the subject librarian responsible for the guide.  The image could come from libguides/springshare or from the library web site.  

Approaches could be to use the name to pull in an image with javascript OR to write a normalization rule that would create a link to the image.

**Comment by nestochan** [comment]
I feel I need to insert a sanity check here: This sounds like it would be a pretty javascript heavy --difficult to maintain solution -- which will require quite a lot of logic to achieve
 as the javascript would have to parse entire pages to get this to work. We don't think this would be a very efficient or reliable way to do this as it will increase processing time per search.  I think that case #226 may be the way to go here, and leverages the use of NormRules and places this in the Details tab. By implementing this approach you could have "A Research Guide authored by <distinguished R&I librarian> display and the head shot similar to the way Harvard is doing this for bookplates. And we can solve 2 thinks with one solution that is native to SOS/Primo. 🃏

**Comment by kmerguerian** [comment]
If you think it would be resource heavy on the page, absolutely let Evan know and close this ticket, or if you want me to talk to him that's fine too.     

(If you or others think it would be useful or fun to put the photos in the details tab, go for it!   That's not a "solution" to what Evan thought of and I proposed here, however. We were proposing an alternative to a single material type icon, something that would make the guides look enticing and easy to spot on the results screen, just as the book cover images do.)

**Comment by jasf-** [comment]
This kinda got subsumed into #220 & #226.
