### ISSUE TITLE
Enable ascending date sort option?

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#228]
In the May release, an ascending date sort option is now possible.

![ascendingdate](https://cloud.githubusercontent.com/assets/4661920/17216015/ee7be346-54ac-11e6-8d50-56b7539ca21a.png)

Question for the next READ meeting on 8/3:  do we want to enable this in production?  Do we need to enable in staging first?

For reference, instructions on how to pull this off are [here](http://knowledge.exlibrisgroup.com/Primo/Product_Documentation/Highlights/047Primo_May_2016_Highlights).

**Comment by jasf-** [comment]
The R&I folks I've talked to would like this implemented.

READ discussed on 8/3 and decided to implement.

**Comment by winthropo** [comment]
Kristin is going to test in staging and if it works -- do it in production.

**Comment by kflachs** [comment]
This is now in production.
