### ISSUE TITLE
Troubleshoot customized Alma iframe CSS

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#229]
I created two separate, but possibly related, Ex Libris cases for Primo records not displaying the request button. For both cases, Ex Libris thinks our custom CSS is preventing the request button from displaying

Case 1: https://exlibrisgroup.my.salesforce.com/50032000013dNio
Item-level request buttons not displaying for record in Primo production. 

Eli confirmed that the item-level request buttons are not displaying in Production because of the get-it services menu Alma CSS. 

![requestbuttons](https://cloud.githubusercontent.com/assets/4663357/17520327/590654d4-5e1d-11e6-955e-18573f935200.png)

Case 2: https://exlibrisgroup.my.salesforce.com/50032000013dONl
Request button not displaying for record in Offsite Remote Storage in the Primo SB. 

We can't confirm that the CSS is the problem from Case 2, but Ex Libris seems to think it is. See case for details. 

Can someone troubleshoot **both** case examples to see if our custom CSS is preventing the request button from displaying? Please reapply default get-it iframe CSS in Alma SB or edit custom CSS so the buttons appear in SB. 

Thanks

**Comment by nestochan** [comment]
@elizoller @winthropo original mashup.css link is this 2yrs old. if it's changed since then dunno, but ours is based on this one.

https://gist.github.com/nestochan/9398aacfda99fbb88120
