### ISSUE TITLE
Move facets in new UI to the left

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#231]
Right now the facets are on the right in the new UI. 

Please move to the left.

Thanks!

**Comment by elizoller** [comment]
I have done this with CSS - but I think it may be possible in the newest release to do this with a back office config Will want to test that out and see if we can eliminate this customization.

**Comment by elizoller** [comment]
Waiting for February release on this which is slotted to be installed on Feb 12 as far as I know

**Comment by elizoller** [comment]
Does anyone see where to turn this on in staging? wanted to test to see if it worked better/different from the solution I put in.

**Comment by elizoller** [comment]
Ok I don't see anywhere in my notes on why I thought this was happening in the February release. But the fix that I put in is working well (as far as I can tell) so I'm going to close this.  But do let me know if you see any issues with it.

**Comment by kmerguerian** [comment]
The conversation on the listserv was about how moving the facets to the left caused display problems on iPhone/iPads, but I have not tested this myself. Just commenting, not re-opening.

**Comment by kmerguerian** [comment]
This:

Hi Todd,

the div containing the facets will get a new class "is-stuck" as soon as
you start scrolling through the results. Amongst other changes this will
give said element a rule of "position: fixed;" Now an iPhone for example
will treat "position: fixed;" as "position: absolute;" - see:

http://stackoverflow.com/questions/4889601/css-position-fixed-on-ipad-iphone

That is why the element will be stuck on top next to the results list. I
am not aware of any convenient workaround for this.

Best regards,
Gabriele
gabriele.hoefler@obvsg.at
