### ISSUE TITLE
Basic Search Autocomplete

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#232]
@jasf- pointed out this nifty autocomplete that BU and other new UI sites have running. It does a nice job of highlighting the scopes, too. I'm not sure where this is configured. We don't have this running and I can't find anything in the documentation about it.

@elizoller could you look at this please? Thank you.

![autocomplete](https://cloud.githubusercontent.com/assets/4663357/21899236/8a67056c-d8bd-11e6-9d76-00ba883df1c9.png)

**Comment by elizoller** [comment]
I think this is a config thing since I can see some attributes in the HTML with the words autocomplete in theme. I'll dig into it a bit more soon

**Comment by winthropo** [comment]
I think you are right about it being a config thing because Colorado School of Mines has it working, too. And they are a Total Care customer who doesn't really do custom stuff.

**Comment by elizoller** [comment]
http://knowledge.exlibrisgroup.com/@api/deki/files/42355/Primo_Autocomplete_Configuration_Guide.pdf
Not sure if this applies to the New UI?

**Comment by winthropo** [comment]
I’ll try it out in the sandbox. Those screenshots, of the front end, don’t show quite the same thing so I wasn’t sure. I’m not seeing the scopes come up like at BU. But I can try to follow this and see what happens.

**Comment by winthropo** [comment]
"Before you can use the Autocomplete functionality, you must register your institution with the Autocomplete service." hmmm. Might be more to this than flipping a switch?

**Comment by elizoller** [comment]
You can supposedly "register" via the backend by editing the institution

**Comment by winthropo** [comment]
I'm working on this and hopefully we can have it up and running for July 10.

**Comment by winthropo** [comment]
closing this. open if we start seeing any funny business.
