### ISSUE TITLE
WorldCat passthrough in new UI

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#234]
READ decided to put the passthrough in the following place. See how that looks and adjust if necessary. 

![wcpassthru](https://cloud.githubusercontent.com/assets/4663357/21904208/e02c05de-d8d0-11e6-914a-679f4e4417a0.png)

**Comment by elizoller** [comment]
Should this not show up until a user has done a search?

**Comment by winthropo** [comment]
Correct. so that needs adjusting.

**Comment by elizoller** [comment]
Making a note to figure out how to handle the passthrough on mobile and fix CSS on scaling - around ipad size it starts to look wonky

**Comment by elizoller** [comment]
This should be all set. Closing for now - if there are more changes we can reopen or create new more specific tickets
