### ISSUE TITLE
Report-a-Problem links in new UI

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#235]
READ decided to place those links in the following places.

![rap1](https://cloud.githubusercontent.com/assets/4663357/21904301/259c98a4-d8d1-11e6-8f6c-67c7c5fd3f9f.png)

![rap2](https://cloud.githubusercontent.com/assets/4663357/21904380/64c3be72-d8d1-11e6-98ba-7f3496762b65.png)

**Comment by elizoller** [comment]
closed with https://github.com/NEU-Libraries/scholar-onesearch/commit/bc350d30571308c5d65220a26b851bf571411009 https://github.com/NEU-Libraries/scholar-onesearch/commit/fc192fd7a1a7d2332663e919a9c6ab29a8a8f8f7 https://github.com/NEU-Libraries/scholar-onesearch/commit/761cbce0eb9111977059dc0c57ce66fb31901f67
