### ISSUE TITLE
Hide Default Language Dropdown

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#238]
@elizoller are we using CSS to hide this in the current UI? I see it in the clean view but not production. 

Want to hide it in new UI prod and sandbox.

![defaultlanguage](https://cloud.githubusercontent.com/assets/4663357/21934057/fe4ada54-d975-11e6-9d7b-45c19635f4c2.png)

**Comment by elizoller** [comment]
Do you also want the selected language hidden?
![screen shot 2017-01-13 at 10 15 11 am](https://cloud.githubusercontent.com/assets/5439169/21934898/37d0823a-d979-11e6-85ef-1c11986790ac.png)

**Comment by winthropo** [comment]
Yes! thanks for thinking of that. Definitely.

**Comment by kmerguerian** [comment]
Why hide it?  1. it's kind of a nice way to advertise that other languages are available, even to guests, and 2. It makes it easy and convenient to change the language.

Karen "the troublemaker" Merguerian

**Comment by winthropo** [comment]
My initial reaction was to hide it for now because it displays an odd collection of languages and until we sort out which languages to display we should hide it. If you want to sort out which languages to display in the BO I'm fine with not hiding it. But as long as it is displaying this collection of languages it should be hidden. 

![screen shot 2017-01-19 at 9 30 26 am](https://cloud.githubusercontent.com/assets/4663357/22110508/f3b80540-de29-11e6-81d4-aa688eee4101.png)

**Comment by winthropo** [comment]
New UI is displaying the right interface languages in My Account. If folks want to unhide the language link  -- next to the sign in. I'm fine with that. @kmerguerian ?

**Comment by kmerguerian** [comment]
If it's displaying the right languages, I would not hide it.

**Comment by winthropo** [comment]
It's displaying the right languages. I'm going to close this case.

**Comment by elizoller** [comment]
Do you want me to bring the language dropdown back? It is hidden with CSS

**Comment by kmerguerian** [comment]
Yes, thanks

**Comment by winthropo** [comment]
My bad. I thought we were talking about the language settings in My Account. Which have always been visible.

**Comment by kmerguerian** [comment]
Thanks--Note the list of languages available is different depending on what language you choose. Maybe the only practical way to manage that is to make them all available in all interfaces?

**Comment by kmerguerian** [comment]
Sorry, that may not be true, I think they are just in different order so that confused me.

**Comment by winthropo** [comment]
I guess this shouldn't surprise me. But the My Account area doesn't get much action. Since 2017:

![screen shot 2017-06-05 at 3 50 50 pm](https://cloud.githubusercontent.com/assets/4663357/26800329/e3cb5c6a-4a06-11e7-8874-519c6d6bfc39.png)
