### ISSUE TITLE
Details & Related Links link split in new UI modal

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#245]
It looks like this link is split and might need attention from @elizoller ?

![screen shot 2017-01-17 at 2 34 48 pm](https://cloud.githubusercontent.com/assets/4663357/22036679/54cd2e3c-dcc2-11e6-8b87-9b10977384c5.png)

**Comment by elizoller** [comment]
Option 1:
<img width="530" alt="screen shot 2017-01-23 at 2 07 14 pm" src="https://cloud.githubusercontent.com/assets/5439169/22218586/918804ac-e175-11e6-9ff5-7c6756a9fd0f.png">
Option 2:
<img width="489" alt="screen shot 2017-01-23 at 2 07 22 pm" src="https://cloud.githubusercontent.com/assets/5439169/22218590/945fbb16-e175-11e6-8f11-ca0d271c4d89.png">

**Comment by winthropo** [comment]
I like Option 1.

**Comment by elizoller** [comment]
I am also open to other ideas
