### ISSUE TITLE
Material type facet functionality

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#246]
When using the facets, it is possible to select multiple.  It is a slow and unpleasant task but it is possible.  For example, search Merguerian.  Click on Author/Creator and choose Merguerian, P. (wait for refresh) then choose Merguerian, PA (wait for refresh) then choose Merguerian, Paul (wait for refresh), and so forth in order to get all the permutations of the name.   

However, I cannot choose multiple Material types.  For example, if I want both articles and conference proceedings.  I choose articles (wait for refresh) but then there is no longer a material type facet available in order to choose Conference Proceedings.

**Comment by winthropo** [comment]
I can't figure out how to choose multiple material types in the old UI. Can you?

**Comment by kmerguerian** [comment]
At the bottom of the list of material types, click "show more options".  use the checkboxes for what to include.  

I actually just realized there is no way to do this in the new UI.   From the list of authors, you can only select one permutation of the name.  You would have to use asterisks or something or approach it from the advanced search point of view to make multiple selections of author or subject in the new UI.

I just checked BU and it doesn't work there either. Is there no way to include multiple selections from the facets?  Should I put this on the listserv?

**Comment by winthropo** [comment]
Hey, I couldn't figure out how to even do it in the old UI so maybe I'm not the person to ask 😃 

You could put it on the listserv, check the documentation, or file a case I suppose. 

How critical is this for going live?

**Comment by winthropo** [comment]
You could also check the other newUI sites I sent around. See if they have something like this working.

**Comment by kmerguerian** [comment]
That's why I looked at BU.

**Comment by winthropo** [comment]
I meant other sites beyond BU. If you want.

Carleton College
https://apps.carleton.edu/campus/library/
St. Olaf College
http://www.stolaf.edu/library
California State University San Marcos
https://biblio.csusm.edu/
Colorado School of Mines
http://library.mines.edu/
Tennessee Technological University
https://www.tntech.edu/library 
Buckinghamshire New University
 http://bucks.ac.uk/home_eu_students/library
Cambridge University
 http://www.lib.cam.ac.uk/
Edinburgh Napier University
http://my.napier.ac.uk/library/Pages/Library.aspx
University of Surrey
http://www.surrey.ac.uk/library/
Sussex University
http://www.sussex.ac.uk/library
University of East London
https://www.uel.ac.uk/Discover/Library

**Comment by jasf-** [comment]
I remember that a couple of patrons wanted this functionality when we first rolled Primo out lo these many years ago.  We (and they) were happy when ExL eventually added it, so if it's indeed lost now that's not good.  I'll check some of these other new UI sites.

**Comment by jasf-** [comment]
I tried half a dozen of the new UI sites and couldn't select multiple options on any of the facets, material/resource type included.

I find it odd that you can *exclude* things until the cows come home (see below - I could've kept going but I got bored ;) ) but the functionality to do this the other way round, by *including* only certain options, is now gone.

![exclusionzone](https://cloud.githubusercontent.com/assets/4661920/22213741/3d3e6d80-e163-11e6-9849-74e70a3b9eac.png)

**Comment by kmerguerian** [comment]
I put it on the listserv.  Summary: Person from NZ commiserated with me.  Systems librarian from UW Green Bay at first said you could do it, then wrote back never mind, I see what you're talking about.

Karen

**Comment by jasf-** [comment]
Ha, yeah, just spotted your message.  The quote you posted from the documentation is a bit puzzling too.

**Comment by elizoller** [comment]
I wonder if this is slotted for a future release by EXL already since it is existing functionality in the old UI?

**Comment by winthropo** [comment]
Karen found this statement in the Ex Libris knowledgebase 
   
_Why we can’t choose multiple facets?
We found the multiple facet selection was not used by the users and that by adding this functionality may make the new interfaces confusing and cumbersome to them. After users begin to use and become familiar with the new interface, we may reconsider this functionality._

**Comment by elizoller** [comment]
Ah ok - then should I look into the possibility for adding this functionality back in (perhaps not in the exact same form with the modal but in some way)?

**Comment by winthropo** [comment]
Normally I question customizations, but this is loss of functionality. 

I would like to discuss this over email with PUIG to see what they think. As a formality.

**Comment by kmerguerian** [comment]
Update: The iterative exclusion method 

_In principle,_ you can search multiple selections in a single facet by **excluding** all the facets you don't want.  For example search "graphene" then under material type, exclude everything except reviews, books, and articles. 

_In practice,_ there seems to be a limit of about 12 exclusions. After that, the system tells you there are no results.  For example, search Merguerian. Under Author/creator, exclude everyone except variations on the first name Paul or P. After about a dozen the system tells you there are no results. 

Multiple exclusions is a slow method, because the results screen has to refresh after each exclusion.  The performance deteriorates to the point of sometimes hanging/freezing the browser completely (firefox on MacOSx).

_Conclusion_
Searchers who are careful and experienced might be able to accomplish multiple selections with the iterative exclusion method for up to 12 exclusions, but it does not work consistently, the performance is poor, and it is not intuitive.

**Comment by winthropo** [comment]
@elizoller Regina expressed interested in an initial investigation to figure out what a customization would look like and how much time would be needed - to deliver a customization for this loss of functionality. Let's discuss next week.

**Comment by winthropo** [comment]
According to our friends at Ex Libris: multiple facets selection is planned to be added with the August release, and they are also reconsidering the option to add more prominent indication for including facets. We are going to stand down on looking for a custom solution.
