### ISSUE TITLE
Responsive style in Safari for MacOS

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#247]
I'm getting a stacked/responsive view in Safari on the mac.   Facets at the bottom of the screen, and inappropriate overlaying of different elements of the screen are the main results.   

See screen capture from production attached.  (Thank you, SnagIt scrolling capture!)

![safaricapture](https://cloud.githubusercontent.com/assets/2442078/22085438/1772177e-dda2-11e6-9d6a-1a6ec10de14b.png)

**Comment by winthropo** [comment]
I'm not seeing this. Can't reproduce.

**Comment by winthropo** [comment]
@kmerguerian can this be closed?

**Comment by kmerguerian** [comment]
User is going to update her OS and her browser at some point... :-)
