### ISSUE TITLE
Inappropriate icon sizes in Safari for the mac

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#248]
On the search results pages, the icons for material type in the search result pages are HUGE and GIGANTIC and make it difficult to navigate the site.  

It's especially entertaining if you search Regina Pagani and the result lists contains a record for a subject guide.  :-)

**Comment by winthropo** [comment]
I can't reproduce this with Safari 9.1.

**Comment by winthropo** [comment]
@kmerguerian can this be closed?

**Comment by kmerguerian** [comment]
I am closing this based on the assumption it's caused by my out of date Safari instance.  I will need to update my OS, so in the meantime, someone else needs to test with Safari.
