### ISSUE TITLE
Page title/branding

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#249]
The page titles for our system should say Scholar OneSearch (not Primo by Ex Libris).  

![screen shot 2017-01-18 at 5 26 01 pm](https://cloud.githubusercontent.com/assets/2442078/22085896/1ffed100-dda4-11e6-8172-4adcd965f2a4.png)

**Comment by elizoller** [comment]
I believe this is a back office config thing - looks like `nui.brief.title` from the code

**Comment by winthropo** [comment]
Fixed this.

**Comment by winthropo** [comment]
@kmerguerian , would it be better to change this to just "SOS" instead of "Scholar OneSarch" and then the search term logic we have in place? In a separate case i've requested a branded NEU favicon.
