### ISSUE TITLE
Color/branding

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#251]
Shouldn't there be some red, since we are Northeastern?  
Red is a difficult color since it takes over... Maybe use as an accent color...in the logo, icons and arrows, the search icon, etc.  Examples:

http://buprimo.hosted.exlibrisgroup.com/primo-explore/search?vid=BU&sortby=rank&lang=en_US
https://pmt-eu.hosted.exlibrisgroup.com/primo-explore/search?vid=44NAP_ALMA_VU1&sortby=rank&lang=en_US

**Comment by winthropo** [comment]
Now that we've had a chance to see some color/branding in dev. OK to close this? Unless there are specifics you would like to see.

**Comment by kmerguerian** [comment]
Yes, I should have mentioned I think it looks great to have some red!  

 I suggest the UI testing group discuss the overall look to make sure everyone is comfortable with the use of color and branding and ask if they have further suggestions--this shouldn't just be about me or my own taste.

**Comment by winthropo** [comment]
Of course the UI group and READ will discuss. And we will get feedback from R&I and IDEAS.
