### ISSUE TITLE
Email address in user account area

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#252]
If you log in to Scholar One and navigate to "my account" then "personal details" you can change your own email address.  

My recollection is that we deliberately removed the end-user's ability to edit this information since our institutional  data loads override this periodically, and we didn't want people changing it and having it be constantly changed back etc.

**Comment by elizoller** [comment]
Will have to wait until we have working shib in staging to do this

**Comment by elizoller** [comment]
@nestochan any update on shib with staging?

**Comment by winthropo** [comment]
What is the latest with this now that we have shib working?

**Comment by elizoller** [comment]
No luck as of yet. Still looking into it.

**Comment by winthropo** [comment]
@elizoller & @nestochan i'm still able to change my email address in my account in the new UI. Does this need to be fixed before April 3?

**Comment by elizoller** [comment]
I have investigated this and am still not seeing a way to disable the field that seems acceptable. Any solution I come up with is quite "hacky". 
So if it is not a high priority, I will keep looking for a better solution when I have time. If it needs to be in place by the 3rd, I can work up a temporary solution and then find a better solution later on.

**Comment by winthropo** [comment]
@kmerguerian did you notice that you can also do this in the old UI?

**Comment by winthropo** [comment]
@elizoller I don't think this is a priority and doesn't have to be fixed by the 3rd. I'll update the milestone.

**Comment by kmerguerian** [comment]
No—I thought we removed user access to editing email long ago.  Maybe it came back somehow in a subsequent release.  My understanding is if you change it, it will just change back due to Banner data, so it’s not a good idea to give people the idea they have control.

Karen

**Comment by winthropo** [comment]
I guess we could hide it, but I just wanted to separate it from the New UI tagged things.

**Comment by nestochan** [comment]
@kmerguerian the change is local to primo...  -- it does not update Alma at all... or revert back based on banner data. however, it does give the impression that you are making a much larger change than it does... changing this would be hacky... perhaps hiding tab or edit button is a solution here. -- 🃏

**Comment by kmerguerian** [comment]
Does it actually change Primo-related functions?  For example does it change the address for alerts but not overdue notices, etc..?  If so I think that’s OK, right?
Karen

**Comment by winthropo** [comment]
@kmerguerian closing this. reopen if it is still an issue for you.

**Comment by kmerguerian** [comment]
So what functions would be "local to Primo"?  Would anything be affected other than alerts?  It would be good to have that documented in this ticket if the information is available just for reference.

**Comment by winthropo** [comment]
Fixed 

prevent patrons from updating their Personal Details in Primo by modifying the default configuration in Alma: set the primo_patron_info_updatable parameter to N in the Customer Parameters table (Configuration Menu > General > General Configuration > Other Settings) in Alma.
