### ISSUE TITLE
Icons random in personal account area

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#253]
This may be a matter of personal opinion, but IMO the icons in the personal account area that appear when you have no "requests" or "blocks and messages" are kind of random.  Why a six-pointed star?  Why a palm tree?   Are these necessary to have? 

![screen shot 2017-01-18 at 6 02 46 pm](https://cloud.githubusercontent.com/assets/2442078/22086851/d141a466-dda8-11e6-8d19-084ddc062cfc.png)

**Comment by winthropo** [comment]
I think we should hide these icons.
