### ISSUE TITLE
Default language "items sent by"

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#254]
When you email a record to yourself from the search results page

change the language from
Item(s) sent by Primo

to
Northeastern Libraries search items
(matching the existing UI)

**Comment by jasf-** [comment]
Just noticed that the new UI still has the 'items sent by Primo' language.  Is this something that needs addressing before cutover?

![sentbyprimoemail](https://cloud.githubusercontent.com/assets/4661920/26689575/14800e96-46c4-11e7-9da4-0bc3f2c000e5.png)

**Comment by winthropo** [comment]
Filed a case. 

https://exlibrisgroup--c.na26.visual.force.com/apex/VF_Case_WithoutJira?id=5003200001DJ8uTAAT

**Comment by winthropo** [comment]
Fixed in production. Closing.
