### ISSUE TITLE
View it/Get it labels

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#255]
It seems like in the Modal, the "View it" label in the new UI corresponds to "View Online" in the old UI. If I am right, can we update this language so the new UI also says "View Online"?  It would be helpful to stick with familiar language. 

At the bottom of the modal screen, there's another link that says "Get it".  So far that always seems to go to a screen that says we don't have the item, even when we do.  Maybe that needs to be removed, or doesn't apply to certain types of records or materials?  Let me know if this should be another ticket. 

For an example, see 
http://onesearch.library.northeastern.edu/primo-explore/fulldisplay?docid=NEU_ALMA51213396890001401&context=L&vid=NU&search_scope=everything_scope&tab=default_tab&lang=en_US

I apologize for never really grasping the "View it" and "Get it" environment in Primo.  I know it's in the knowledgebase and I have tried to read it, but it uses words that I don't understand like "GetIt/ViewIt mashup" and OvL and Alma-D records.

**Comment by winthropo** [comment]
Fixed. Closing the case.
