### ISSUE TITLE
I am not authorized! Checked out books

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#256]
When looking at a checked-out item in the catalog, I am not offered any options for requesting (after logging in).   

The message is "You are not authorized to place requests for this record." (Hmph!)

Offer the option to either add the end-user's name to a waiting list or to request on interlibrary loan, as appropriate based on our policies. 

![screen shot 2017-01-18 at 6 30 18 pm](https://cloud.githubusercontent.com/assets/2442078/22087588/b8748cba-ddac-11e6-8e28-0505c18a8cf9.png)

**Comment by winthropo** [comment]
this item is now available in the stacks. do you have another example you want to use?

**Comment by winthropo** [comment]
closing @kmerguerian . please reopen if you are still seeing this issue.
