### ISSUE TITLE
Add the option to request from storage

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#257]
When viewing an item in storage, even after logging in, there is no option to request. 

See
http://onesearch.library.northeastern.edu/primo-explore/fulldisplay?docid=NEU_ALMA21147061170001401&context=L&vid=NU&search_scope=everything_scope&tab=default_tab&lang=en_US

**Comment by winthropo** [comment]
Yep. Needs fixing.

**Comment by winthropo** [comment]
Seems fixed. What do you think @kmerguerian 

![screen shot 2017-02-16 at 8 49 25 am](https://cloud.githubusercontent.com/assets/4663357/23023757/0085ed6c-f425-11e6-9031-f3f053d58e0c.png)

**Comment by winthropo** [comment]
Closing this. Feel free to reopen.
