### ISSUE TITLE
"Availability" facet appearance

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#258]
I'm not sure the peer reviewed facet belongs under availability.  The two concepts aren't related... I think it might be easier if we used the language on the old UI, which is 

* Show Only
   * Peer reviewed journals
   * Full text online
   * Available in the library

Or something like that.

**Comment by winthropo** [comment]
I agree. We should change "Availability" to "Show Only" in the facet header. 

![screen shot 2017-01-19 at 9 55 34 am](https://cloud.githubusercontent.com/assets/4663357/22111502/85bba566-de2d-11e6-8211-0f3fc4b37139.png)

**Comment by winthropo** [comment]
Fixed in dev.
