### ISSUE TITLE
Messages in the modal for available books 

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#259]
Do we need either one of these Yellow-banded messages in the full record for an available book? 

Can they be removed? They are off-putting. 

![screen shot 2017-01-18 at 7 30 01 pm](https://cloud.githubusercontent.com/assets/2442078/22088814/b40a9b9e-ddb4-11e6-86b6-1dc1c621ad72.png)

**Comment by winthropo** [comment]
@kmerguerian what do you think of this now? Looks like some changes have been made.

**Comment by winthropo** [comment]
I'm going to close this. Feel free to reopen if necessary.
