### ISSUE TITLE
OneSearch homepage on iPad

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/scholar-onesearch#26]
- URL: http://onesearch.neu.edu:1701/primo_library/libweb/action/search.do
- Browser: Chrome on iPad
- Description: I think the red bar and the black bar are supposed to be the OneSearch logo. Also the "Why sign in" bubble is squished into Report a Problem and it seems attached to New Search
  ![image](https://f.cloud.github.com/assets/4663073/633575/1ecd20c0-d204-11e2-806f-b55450fc91cc.jpg)

**Comment by bassettsj** [comment]
@sarahjeansweeney Try clearing your cache to see if the homepage renders better.

**Comment by sarahjeansweeney** [comment]
That worked!
