### ISSUE TITLE
Link to floor maps: "Find it"

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#260]
Using the same rules as the old UI, add links to floor maps (the "Find it" button).

**Comment by winthropo** [comment]
Right the "Find It" button is there in sandbox and links to the page but the logic using the call number isn't there. @elizoller is working on that. 

![findit](https://cloud.githubusercontent.com/assets/4663357/22111739/6bbc8120-de2e-11e6-95ae-fead58276ffc.png)

**Comment by elizoller** [comment]
This may be harder to recreate than I originally thought because the Find It button is now inside the Alma iframe- Do we have the ability to add JS from Alma or only CSS?

**Comment by kmerguerian** [comment]
Is there another place we can put the Find It button?

**Comment by winthropo** [comment]
Is it good enough the way it is now? If not, good enough for August 1?  I think so.

**Comment by kmerguerian** [comment]
If all the "Find It" links are going to this page on August 1:
http://library.northeastern.edu/about/maps-and-directions/floor-maps

I might redesign the page differently.  Before I look at that, a couple of questions

Is it possible to put a find-it link on the search results page?  Does it have to be in the popup?
Is it possible to make the link go to a different page based on the location (archives, stacks etc.) if not the call number?

Just thinking that the answers to these questions would determine what I do on the target linked pages on the web.

**Comment by winthropo** [comment]
Send a screenshot of where you are thinking of putting it when you get a chance. I think I know what you mean though. Almost anything is possible, but using the GUI BE I don't think it is possible to put it where you are suggesting. We could review the documentation to confirm.

**Comment by winthropo** [comment]
PUIG discussed and agreed that the way it is now is "good enough for August" or GEFA.

**Comment by winthropo** [comment]
I'm going to close this case. Please feel free to reopen. if necessary.
