### ISSUE TITLE
Are we going to have course reserves in the new UI?

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#261]

**Comment by winthropo** [comment]
Why wouldn't we? We have a reserves scope in there now. Is it not working?

**Comment by kmerguerian** [comment]
Sorry, I can't find it... I tried to append scp.scps=scope%3A(NEU_CR) onto the URL but that didn't seem to work.   But I'm glad it's there anyway.

**Comment by winthropo** [comment]
![screen shot 2017-01-19 at 3 15 30 pm](https://cloud.githubusercontent.com/assets/4663357/22123591/32f21860-de5a-11e6-85b4-f0ad38159a2c.png)

**Comment by kmerguerian** [comment]
I don't have that dropdown on my home page!   Not in firefox or chrome on macOS!!!  

But I found it on the advanced search page, so that's good.

![screen shot 2017-01-19 at 3 17 06 pm](https://cloud.githubusercontent.com/assets/2442078/22123649/6c1b5610-de5a-11e6-82df-67f7b187db96.png)

**Comment by winthropo** [comment]
It should show up after you click the magnifying glass in that view. It is more obvious when you are in SOS itself and don't have to click on the magnifying glass. And the autocomplete should make it more obvious too. 

My guess is you don't like this behavior and we need to try to improve it. That should be a separate ticket.

**Comment by kmerguerian** [comment]
Hm, I predict the law library is going to love this....

**Comment by winthropo** [comment]
Always an option to make their own custom view.

**Comment by elizoller** [comment]
There is a very simple JS fix to show the scope dropdown when the page initializes- is that something you'd be interested in?

**Comment by winthropo** [comment]
if it is very simple. i'm just mindful of the slippery slope of customizations. we wan't to avoid according to Amira.

**Comment by elizoller** [comment]
Are we ok with this customization? If so, this can be closed.

**Comment by winthropo** [comment]
Yes, very nice improvement. I'll close it now. Thanks!

**Comment by winthropo** [comment]
@elizoller can you make this happen in production vid=NU? It would be nice to have it in place today if at all possible. the simple JS fix to show the scope dropdown when the page initializes

**Comment by elizoller** [comment]
Up in prod on vid=NU

**Comment by winthropo** [comment]
Thanks for doing that so quickly!
