### ISSUE TITLE
Location items -->Location

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#262]
Can we change "Location items" to just say "Location"?  I don't think "items" is adding anything here to say the least. 
![screen shot 2017-01-20 at 12 12 11 pm](https://cloud.githubusercontent.com/assets/2442078/22158373/ecaa810c-df09-11e6-8cbf-f2412a343a07.png)

**Comment by winthropo** [comment]
@elizoller I'm not 100% certain I found this in the code tables. Could you make the fix @kmerguerian is asking for?

**Comment by elizoller** [comment]
It is under Front End Code Tables > aria Labels > default.nui.aria.locationItems.locationItems

**Comment by winthropo** [comment]
Thanks. I made the change in dev. not sure why my code table search didn't find that.

@kmerguerian what was the specific example that brought this to our attention?

**Comment by kmerguerian** [comment]
You can check any physical object in the catalog. 

  It looks like the label has completely been removed in dev. I'm not sure that's a bad thing, actually, but is it what you intended? 
 
Compare
http://onesearch.library.northeastern.edu/NU:dedupmrg46176281&tabs=viewOnlineTab (Location and status tab)
and 
http://northeastern-primo-sandbox.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=NEU_ALMA21172019850001401&context=L&vid=NUdev&search_scope=new_everything_scope&tab=default_tab&lang=en_US

**Comment by winthropo** [comment]
I just removed the word "ITEMS" from the code table. That is why I asked for the specific example to figure out what happened here because I couldn't find it anywhere. I think maybe an adjustment/improvement to a mapping table may have fixed this. 

Not 100% sure what happened here.

**Comment by winthropo** [comment]
@kmerguerian can you check this? I think we can close it.
