### ISSUE TITLE
Worldcat Wecord

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#263]
1. I think READ decided we don't want world cat books in SoS, right?
2. If that's not true, then 
a. Spelling of "WorldCat Record" correction
b. Something would have to be done about the relevance ranking to prevent them from appearing above materials in our collection. 

![screen shot 2017-01-20 at 2 27 02 pm](https://cloud.githubusercontent.com/assets/2442078/22162541/1b831648-df1d-11e6-80e6-a74e0a0d5ec7.png)

**Comment by elizoller** [comment]
Looks like you had sort by Date-newest on instead of relevancy?

**Comment by winthropo** [comment]
This is because we are in Dev. Ignore this says @nestochan

**Comment by kmerguerian** [comment]
Yup

**Comment by winthropo** [comment]
I think it is ok to close this @kmerguerian

**Comment by kmerguerian** [comment]
OK, thanks, will close.  Note that it would help to remove the distraction of the WorldCat Wecords if that is possible at some point before showing it to R&I.

**Comment by winthropo** [comment]
We aren't going to share dev with R&I.
