### ISSUE TITLE
Show license behavior

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#265]
Example
http://northeastern-primo-sandbox.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=TN_hindawi10.1155/2010/915937&context=PC&vid=NUdev&search_scope=new_everything_scope&tab=default_tab&lang=en_US

There are two publishers to choose from, neither of which has a license on file.   

the first (Hindawi OA) has no *show license* drop down. 
the second (DOAJ) has a *show license" drop down, which is empty. 

In cases where there is no license, I vote NOT to have the "show license" drop down appear at all. following the Hindawi example.

If anyone cares, I do like the way Ex libris has incorporated this feature in the new UI!  It indicates something's there (in theory anyway), but without making it take up space unless/until the user wants to examine it.

**Comment by winthropo** [comment]
We should check with Stacy.

There isn't much to the Alma licensing config I don't think. See screenshot.

A theory. Maybe there **is** licensing information in Alma for DOAJ but no specific terms to display for public?

![license](https://cloud.githubusercontent.com/assets/4663357/22164092/b00191cc-df23-11e6-870d-8750270cba00.png)

**Comment by winthropo** [comment]
emailed Stacy about this. may just be a result of how the public license terms are currently set up in the sandbox. she is on it and told us not to be worried about it. she's on the case.

**Comment by winthropo** [comment]
Fixed. Closing. 

![screen shot 2017-02-16 at 8 40 59 am](https://cloud.githubusercontent.com/assets/4663357/23023476/c7aa6ec4-f423-11e6-9e10-73aa75eb821e.png)
