### ISSUE TITLE
Landing page - a more icons, less text approach

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#266]
Noting for the record that I happened across Edinburgh Napier's landing page during my Grand Tour of New UI sites.  I like it, so thought I'd memorialize it here for possible discussion/consideration.

![niceiconz](https://cloud.githubusercontent.com/assets/4661920/22214417/863932de-e165-11e6-8796-41b4e5eb1538.png)

**Comment by winthropo** [comment]
I like this.

**Comment by winthropo** [comment]
@RPagani are there plans to do something like this? Can I close this ticket?

**Comment by RPagani** [comment]
@winthropo Yes, I'll have something this week. We are going to keep it relatively simple (not major changes but less text) for now.
