### ISSUE TITLE
Hide Citation Linker?

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#267]
Unless there are volunteers to revisit/test the citation linker I think we should hide it until we have the time do so. Any concerns with hiding it for now?

![citationlinker](https://cloud.githubusercontent.com/assets/4663357/22251736/dae3f094-e219-11e6-808b-ba8a5856af32.png)

**Comment by jasf-** [comment]
I can do a little testing in my spare time - especially since I hated the citation linker with the fire of a thousand suns when it was first deployed and am ready to give it another chance to impress me.  

Seems like a good idea to hide it in the meantime if doing so is not onerous.

**Comment by jasf-** [comment]
Did some testing.  I'm still of the opinion that the citation linker has issues, but suggest keeping it available for the R&I beta to see what they think.

**Comment by winthropo** [comment]
PUIG discussed this. We are going to leave it on for the R&I round of testing. R&I will make a decision on keeping it or not.

**Comment by winthropo** [comment]
Regina got some feedback on this and we have decided to hide the citation linker. @elizoller is that something you can take care of?

**Comment by elizoller** [comment]
I removed it from the top menu via back end config - is it showing up somewhere else?

**Comment by winthropo** [comment]
I didn't realize you had removed it because we just made that decision minutes ago. Thanks!
