### ISSUE TITLE
New from last week/month/3-months

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#268]
The "New from last week" etc. options are not showing in the facets in the new UI.

**Comment by jasf-** [comment]
I believe this is a back office setting.  Correct @winthropo ?

**Comment by winthropo** [comment]
Yep. It just wasn't configured in Dev. All set now. Let @elizoller know if you want it to be closed by default like the other facets. I think that is something he has to do. I like it the way it is now because it draw attention to this new feature.

**Comment by winthropo** [comment]
We could also move it up the list of facets, too.

**Comment by kmerguerian** [comment]
Yes, Jen, I think so, the Primo UI group has just been asked to use github to keep track of all the settings we need to address as we're testing, so we don't lose track of them. 

Scott, generally I'm fine with replicating what's in production unless someone objects.

**Comment by jasf-** [comment]
Yes @kmerguerian, I am aware of the rationale for use of GitHub.  It was not clear to me that you knew the location of this function, so I thought my comment might be helpful.

**Comment by kmerguerian** [comment]
Very much appreciated!
