### ISSUE TITLE
Eshelf label wording 'push to RISPush to'

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#27]
![pushtopushto](https://f.cloud.github.com/assets/4661920/633561/c85b94d8-d203-11e2-9b07-4d64eab18719.png)

URL:  eshelf
Browser:  Chrome 27, Mac
Description:  Wording on 'push to RIS' is mangled on the button.  I know this is probably on ExLibris' end, not sure if it can be rectified on our end
Medium importance

**Comment by bassettsj** [comment]
Yeah that is can exlibris issue. Sorry
