### ISSUE TITLE
Advanced search: WC passthrough link crowding/stacking on basic search link

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#270]
In Firefox and Chrome.  Seems to persist regardless of window resizing.

![linkpiling](https://cloud.githubusercontent.com/assets/4661920/22335609/57178290-e3ad-11e6-81cf-269414f14e6b.png)

**Comment by elizoller** [comment]
Thanks.
Related to #234 
I still need to fix scaling as well for this

**Comment by elizoller** [comment]
fixed with https://github.com/NEU-Libraries/scholar-onesearch/commit/1128111ac3974d6a8d627f6060025a72f8575538
