### ISSUE TITLE
Re-enable sort by date-oldest in new UI? (#228)

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#271]
I'm not seeing ability to sort by date-oldest in the new UI, so looks like we would have to re-enable it.  Assuming we want to do so, #228 is the thread for when we did this in September.

**Comment by kflachs** [comment]
I can add it in to the Sandbox so we can test it.

What is the name of the view for the new UI in the back office?  It appears to be either NUnu or NUlib.  I found it- NUdev.

-Kristin

**Comment by kflachs** [comment]
I just added in the date-oldest into the Sandbox.

**Comment by jasf-** [comment]
Great - thanks, @kflachs.  I'll close this issue.
