### ISSUE TITLE
Date limit in advanced search

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#272]
The date limit does not seem to be working in advanced search.  This is both in the old and the new UI.  It seems like it happens when there are multiple records ("see all" in the new UI, or "view all versions" in the old UI) even if all of them have the same publication date. 

Is this a known issue? I can't remember. If not, maybe an ex libris ticket?

Advanced search
Keyword Mergers and acquisitions
Date limit--specific date--1990 to 1995
The first result is published in 1988. 

If you use the old UI, limit your search to books to prevent having to plow through so many results. 

The same thing happened when I tried this at Colorado School of Mines.  There the 18th result is published in 1988.

**Comment by elizoller** [comment]
Is the old UI a clean view problem also or just NU view?

**Comment by kmerguerian** [comment]
I didn't check but it seems unlikely that it's our view because I ran into the same problem at Colorado School of Mines.

Can you remind me the name of the clean view? vid=???

Karen

**Comment by elizoller** [comment]
NU_CLEAN

**Comment by kmerguerian** [comment]
Adding that to the Wiki, thanks!

Yes, it happens with the clean view.

**Comment by winthropo** [comment]
@kmerguerian is this a ticket with EXL? Not sure I follow all of this thread.

**Comment by winthropo** [comment]
@kmerguerian what is the latest with this?
