### ISSUE TITLE
Request from another library fail

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#273]
Hmmmm. Wonder what is going on here. Any thoughts?

![what](https://cloud.githubusercontent.com/assets/4663357/22345996/516718e2-e3d0-11e6-9bf1-9127762c9e04.png)

![hmmm](https://cloud.githubusercontent.com/assets/4663357/22346017/59cefeaa-e3d0-11e6-8c94-28a3322a4f5e.png)

**Comment by winthropo** [comment]
Because Scott!  it is connected to the Alma sandbox which is not wired right. closing this case because it looks fine in prod.

**Comment by nestochan** [comment]
__*Note:*__ This may be linked to a change in current Alma release on AlmaSandbox -- due to configuration in Primo __AlmaServices__ We will keep an eye on when AlmaProd is updated to see if it affects newUI in prod...
