### ISSUE TITLE
Order this article from ILLiad fail?

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#274]
In SB. Should this ILL option be offered? We have access through T&F. 

![hmmm](https://cloud.githubusercontent.com/assets/4663357/22346208/397425da-e3d1-11e6-91a2-650222e5e989.png)

**Comment by winthropo** [comment]
And why is # **Options** so large?

**Comment by winthropo** [comment]
In Prod. This can't be what we want.

View It > brings user to alma services screen for T&F

Links > brings you directly to article

Get it > brings you to ILLiad and "request from another library"

so not right in prod or sb. 

![screen shot 2017-01-26 at 2 20 38 pm](https://cloud.githubusercontent.com/assets/4663357/22346661/dbdeab6e-e3d2-11e6-8cec-b7756582f294.png)

**Comment by winthropo** [comment]
We have the "links" section in the old UI, but it is a bit more hidden. So it is really the Get It section that I think is in need of attention.

**Comment by elizoller** [comment]
The options thing is probably a result of the alma css needing to be updated since I'm fairly certain the CSS will need to be rewritten for the new UI

**Comment by winthropo** [comment]
I filed a case for the Get It thing. Case Number	00384776. and we will continue to investigate.

**Comment by winthropo** [comment]
Confirmed with EXL. Known defect that New UI: Missing code for "Request options" lable in Code table GetIT! Tab2: nui.getit_full.alma_tab2_full. At the moment EXL doesn't know the time frame when the fix will be release yet. 

How bad is this?

**Comment by winthropo** [comment]
Emailed BU to see if they can help. They don't have this problem.

**Comment by winthropo** [comment]
I completely disabled the GetIt2 mapping table. Please have a look a look.
