### ISSUE TITLE
Links from the Results Screen to the online version of an item

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#275]
Right now it appears that "Full text available" is appearing for articles, and takes you to the popup (modal) with the services menu of choices and licenses. 

The link label "Online Access" is appearing for books and videos, and goes right to the item, without showing the services menu and licenses. 

So are these labels appropriate, and are they behaving the way we want them to.

**Comment by winthropo** [comment]
READ discussed this  on June 8th and agreed that the labels are appropriate and they are behaving the way we want.

**Comment by nestochan** [comment]
👍
