### ISSUE TITLE
"Check availability via ProQuest Dissertations" fail

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#276]
The "Check availability via ProQuest Dissertations" button is failing in the newUI - production and sb. Working fine in old UI. Looks like the account ID is in the link so not sure what the problem is right now. 

![screen shot 2017-02-06 at 3 23 35 pm](https://cloud.githubusercontent.com/assets/4663357/22664800/3f57754e-ec80-11e6-9734-d0788d5d4fd6.png)

**Comment by elizoller** [comment]
Can you provide a record example?
One of the JS customizations in the old UI is to append the accountID for proquest so it is likely not be being applied at all or correctly in the new UI

**Comment by winthropo** [comment]
_Seeing both the trees and the forest: An analysis of the Indian interorganizational network_

**Comment by elizoller** [comment]
https://github.com/NEU-Libraries/scholar-onesearch/blob/develop/js/src/scholarOneSearch.js#L163
I will have to look into carrying this fix through which looks for any view online buttons and then checks if its a proquest link and then appends the account id
