### ISSUE TITLE
WorldCat passthrough link misaligned

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#277]
Looks like WorldCat passthrough link (Search Other Libraries) misaligned in Safari 9.1.2

![safari](https://cloud.githubusercontent.com/assets/4663357/22693267/884be86c-ed10-11e6-8324-71b7670b4bf3.png)

**Comment by winthropo** [comment]
In Chrome. Looks like starting at 1280 x 1270 the WC passthrough disappears. 


![screen shot 2017-02-14 at 9 18 20 am](https://cloud.githubusercontent.com/assets/4663357/22932676/c3d1716e-f296-11e6-80bf-9a88871f12ef.png)

**Comment by elizoller** [comment]
try a hard refresh - command + shift + R

**Comment by elizoller** [comment]
just pushed up new css this morning so its likely cached in your browser

**Comment by winthropo** [comment]
Thanks. did the trick.
