### ISSUE TITLE
SOS notification for Primo Production Server Move

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#279]
Similar to #213 

The wording will be "Scholar OneSearch will be down for maintenance starting Friday, March X, to March Y. Certain features (eShelf and saved queries) may be unavailable."

I will update this when I know the precise dates in early March. 

Thanks

**Comment by elizoller** [comment]
Sounds good - just let me know the dates and when you want me to take it up and down

**Comment by winthropo** [comment]
EXL gave me some dates. 

"Scholar OneSearch will be down for maintenance starting Sunday, March 5, to March 10. Certain features (eShelf and saved queries) may be unavailable."

If you could put this up on Friday, March 3 that would be great. Can come down on the 10th in the afternoon. 

Thanks.

**Comment by winthropo** [comment]
@kmerguerian what was the revised language you wanted to use? I forget, but remember it was more accurate/better than what was proposed by me.

**Comment by kmerguerian** [comment]
Scholar OneSearch will undergo scheduled maintenance between Sunday, March 5 and Friday, March 10.  During this period, certain features such as eShelf and saved queries may be unavailable.

**Comment by elizoller** [comment]
This message is up in all old UI in dev, staging, prod. Let me know when it's ready to be taken down.

**Comment by winthropo** [comment]
Ready to be taken down. Thanks.
