### ISSUE TITLE
Browse search:  move dropdown to right of search box?

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#28]
![movebrowsedropdown](https://f.cloud.github.com/assets/4661920/633600/2bd61dde-d205-11e2-96e6-b6337d8c68de.png)

URL:  http://northeastern-primostaging.hosted.exlibrisgroup.com:1701/primo_library/libweb/action/search.do?dscnt=0&dstmp=1370892894971&searchField=author&fn=BrowseRedirect&vid=NU&searchTxt=sweeney
Browser/OS:  Opera 27, Mac
Description:  I'd like to see the dropdown for the browse search moved to the right of the search box.  This would keep the design consistent with that of the main search.
Importance:  low

**Comment by bassettsj** [comment]
Can't do my friend, that is the HTML order that was laid out by Exlibris

**Comment by jasf-** [comment]
Bummer.  Thanks.

On Jun 12, 2013, at 4:33 PM, "Steven Bassett" <notifications@github.com<mailto:notifications@github.com>> wrote:

Can't do my friend, that is the HTML order that was laid out by Exlibris
