### ISSUE TITLE
Relabel 'no full text' to 'check for full text' in new UI

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#280]
Example:  http://northeastern-primostaging.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=TN_gale_ofa471292095&context=PC&vid=NUdev&search_scope=new_everything_scope&tab=default_tab&lang=en_US

For the 'no full text' message that displays here:  

<img width="810" alt="nofulltext" src="https://cloud.githubusercontent.com/assets/4661920/23025294/7cf68aea-f42b-11e6-85bf-e7c793d54533.png">

Please change label to 'check for full text' to match label in production.

**Comment by winthropo** [comment]
This is labeled the way you want in production. OK to close this ticket? 

![screen shot 2017-02-16 at 1 41 25 pm](https://cloud.githubusercontent.com/assets/4663357/23035770/461cf20c-f44e-11e6-9983-06b02cb0ef1e.png)

**Comment by jasf-** [comment]
Closed.  Thanks!
