### ISSUE TITLE
Discrepancies in email contents - new UI vs. current UI

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#281]
**Here's the email from our current UI:**

<img width="997" alt="emailfromproduction" src="https://cloud.githubusercontent.com/assets/4661920/23026476/5ef8a876-f42f-11e6-8291-cc143e6826b8.png">

**Here's the email for the same item from the new UI:**

<img width="997" alt="newui email" src="https://cloud.githubusercontent.com/assets/4661920/23026505/722d48a2-f42f-11e6-9aa8-869fc4989aa4.png">

There are several differences between the two, some of which I called out by annotating the screenshot.  Not sure whether the lack of links, stuff happening in the ISBN, 'do not reply to this message' etc. rise to the level of needing a fix - but they are different.

**Comment by winthropo** [comment]
Is this still happening? Anyone know how to fix it?

**Comment by winthropo** [comment]
Closing this issue. Response from EXL:

> With regard to the first question about the authors and subjects not appearing as hyperlinks. I am afraid that this is expected behavior. It is not currently possible to configure or make any changes. I apologize for any inconvenience this may have caused. 
> 
> As far as the second issue you reported in which subfield delimiters from the PNX record such as $$C are appearing in the emails and that the identifiers are not displaying properly. This issue has been reported in the past. However, after a thorough examination, it has been decided that a solution for this will not be part of the current Primo work plan. This means that, while the issue is not scheduled for a fix in any near future releases, it will remain in our development system for possible future consideration. 
> 
> Therefore, I will be setting the status of this case to 'Pending Work Plan'.
