### ISSUE TITLE
WorldCat passthrough

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#282]
There was a fix made to staging to prevent the WC passthrough from dissapearing around 1280 x

It looks like this fix might be needed in production. 

![screen shot 2017-02-22 at 1 23 08 pm](https://cloud.githubusercontent.com/assets/4663357/23226006/133fd224-f902-11e6-84c7-02165f2c191c.png)

**Comment by elizoller** [comment]
Which view on production?

**Comment by winthropo** [comment]
vid=NU

**Comment by elizoller** [comment]
Ok should be all set now

**Comment by winthropo** [comment]
Thanks

**Comment by kmerguerian** [comment]
I am seeing the WC passthrough in Firefox, but I do not see it on Chrome at any width. 
MacOSX, using vid=NU

**Comment by winthropo** [comment]
Production or staging? I'm seeing it in Chrome and Safari in production and staging.

**Comment by winthropo** [comment]
I don't see this issue @kmerguerian can we close this?
