### ISSUE TITLE
Appearance of "null" text

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#283]
I'm not sure what screen this is, but it's a "full record view" that does not involve the modal overlay. 

![screen shot 2017-02-22 at 4 51 23 pm](https://cloud.githubusercontent.com/assets/2442078/23234746/08c8e7ee-f921-11e6-94e4-377863252de8.png)

There's more than one way to get to the screen that shows these "null" words:

Example 1
Search "lincoln in the bardo"
Click the book record (which is hopefully result #2)
In the modal, scroll down to Virtual Browse section
Select the book called Pastoralia
You'll see the null text on the resulting screen to the right of the search box. 

Example 2
Get a permalink to a book:

http://onesearch.library.northeastern.edu/primo-explore/fulldisplay?docid=TN_gale_ofa452198008&context=PC&vid=NU&search_scope=everything_scope&tab=default_tab&lang=en_US

In the display on this screen you will also see the null text on the right side of the search box.

**Comment by winthropo** [comment]
@kmerguerian or anyone else reading these...are you seeing this because I'm not.

**Comment by kmerguerian** [comment]
Yes, I am still seeing it. Firefox on MacOSX, following the steps I outlined above.
