### ISSUE TITLE
Strange icon behavior in results list

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#284]
In the results list, when you click on the baby quotation mark icon " (citation) instead of showing a citation, it shows another row of larger square icons.   Then you have to choose one of those larger square icons, such as clicking the larger square citation icon again, to actually get the citation. 

Compare with BU where you click on the baby citation icon, and the citation appears below the row of larger square icons.

Also, in Scholar Oneafter you click the baby citation icon--or any one of the baby icons--and then click on the baby email icon, it goes to the printer instead of email.  And if you click on the baby citation icon again, it goes to Report a Problem instead of citation.

I made a video for all you visual learners out there.  
http://www.screencast.com/t/nSqxwdRU  

Chrome in macOS

**Comment by winthropo** [comment]
Yep, I see this bug, too. Only happens in production. Working fine in staging.

**Comment by elizoller** [comment]
Alright, thanks. I'll look into it

**Comment by elizoller** [comment]
I do think there might be something environmental about this - do you know when we are moving production to the most recent release?
Thanks

**Comment by winthropo** [comment]
We will test the Feb Old UI in staging later this week / early next week. Hopefully that will go smoothly and we will get Prod upgraded to Feb release no later than week of March 12.

**Comment by winthropo** [comment]
This is no longer an issue in production for the new UI. Closing this case.
