### ISSUE TITLE
Related reading

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#285]
Not sure this is an issue, but when you are in the modal for an item and you click on a suggested item in "Related Reading" on the right, it goes to the old UI.  

I'm guessing this isn't going to happen in August, but will it happen when we are in the public beta?  If so, is it worth pursuing a fix?

**Comment by winthropo** [comment]
Yep. This needs to get fixed before go-live.

**Comment by winthropo** [comment]
Not an issue anymore. Closing.
