### ISSUE TITLE
Citation problem: missing publisher?

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#286]
Not sure why this is but no publisher appears when you click on "citation" 
http://onesearch.library.northeastern.edu/primo-explore/fulldisplay?docid=NEU_ALMA21234016050001401&context=L&vid=NU&search_scope=everything_scope&tab=default_tab&lang=en_US

**Comment by winthropo** [comment]
@kmerguerian what is the latest with this?
