### ISSUE TITLE
RTA not working in brief view in new UI?

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#287]
Any theories? Brief view location is incorrect = Stacks. Detailed view location is correct = offsite location

![ss1](https://cloud.githubusercontent.com/assets/4663357/23377201/13f2caf6-fcfd-11e6-8801-5fb78bcaeae9.png)

![ss2](https://cloud.githubusercontent.com/assets/4663357/23377204/165057a0-fcfd-11e6-8d28-348c5f99bc16.png)

**Comment by winthropo** [comment]
in the old UI the wrong RTA location shows up briefly (cached?) and then goes away.

**Comment by kflachs** [comment]
All the RTA information in Primo is coming from Alma.  If RTA is wrong in both UIs, it sounds like something changed in Alma configurations, rather than it being the new UI.

**Comment by winthropo** [comment]
Agreed -- RTA is coming from Alma. The RTA isn't wrong in the old UI. Hard to describe what happens. Have a look at the old UI for this one.

**Comment by winthropo** [comment]
This won't be a problem in production. Verified with @nestochan . 

closing this one.
