### ISSUE TITLE
Material type labelling for subject guides

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#288]
Ernesto, you asked me to open a GitHub ticket for the R&I springshare guides regarding the material type information in Primo.  

They should be called Research Subject Guides. Can this please be updated in the labels? (test and production).  This affects the material type label on the record itself, and the label in the Material Type facet.  

![screen shot 2017-02-27 at 4 23 57 pm](https://cloud.githubusercontent.com/assets/2442078/23380625/8fc0f656-fd09-11e6-8986-f1a48d68c245.png)

![screen shot 2017-02-27 at 4 27 21 pm](https://cloud.githubusercontent.com/assets/2442078/23380732/eb60d904-fd09-11e6-8aad-2a7ef8fafab9.png)

Thank you!

**Comment by nestochan** [comment]
@kmerguerian ```ThisISdone```
