### ISSUE TITLE
Subject Guide update schedule

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#289]
R&I and the Web Team recommend the update schedule for the subject guides be once every two weeks. Let me know if that is OK.  Thanks, Karen

**Comment by nestochan** [comment]
@kmerguerian  That schedule frequency cannot be accommodated by Primo. going with weekly on Thursdays:

```Northeastern University	ReloadLibguides	PIPE	Weekly	THU 12:15am```

**Comment by kmerguerian** [comment]
Great, thanks so much!

Karen
