### ISSUE TITLE
New UI beta links for April 3

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#290]
Regina and I discussed. We would like to offer a link (on April 3rd) to the new UI production like Ithaca does. Screenshots here. Thanks. 

![ithaka](https://cloud.githubusercontent.com/assets/4663357/23663360/5cc071f6-0320-11e7-9962-719ff09cbbcf.png)

![neu](https://cloud.githubusercontent.com/assets/4663357/23663330/434869e0-0320-11e7-976f-d5045b23b8c9.png)

**Comment by kmerguerian** [comment]
Might look a little cluttered and cause other content to move down if we try to fit it under our search box as they have done at Ithaca.  Unlike Ithaca, we have a lot of content under our home page search box, so it's not as elegant a solution for us as it is on their site.  Maybe we could see a mockup of how it would look both below and above the box (i.e. next to the words "Search Help"?).  It will be easier to make a decision once we see how it looks.

**Comment by winthropo** [comment]
I'm going to close this ticket and schedule a special READ meeting to discuss this and other links to the new UI.

**Comment by elizoller** [comment]
I can prepare some screenshots of options if you like

**Comment by winthropo** [comment]
@nestochan kicked around the idea of having a passthrough link which seemed cool. And @kmerguerian reminded me that this needs to go through and be approved by the WEB group so I think I'll try to invite Deb M to the meeting since she is the co-chair of WEB.

**Comment by elizoller** [comment]
Some mockups:
<img width="1203" alt="screen shot 2017-03-13 at 8 42 34 am" src="https://cloud.githubusercontent.com/assets/5439169/23855606/a8d62e86-07cc-11e7-918b-efedbf1e9319.png">
<img width="1187" alt="screen shot 2017-03-13 at 8 50 41 am" src="https://cloud.githubusercontent.com/assets/5439169/23855612/acabb774-07cc-11e7-884a-9a7125f95b4e.png">
<img width="1196" alt="screen shot 2017-03-13 at 8 51 31 am" src="https://cloud.githubusercontent.com/assets/5439169/23855617/b18e9446-07cc-11e7-9735-49b0e45daa0b.png">
