### ISSUE TITLE
Changing New UI color

### ISSUE THREAD

**Issue by RPagani** [NEU-Libraries/scholar-onesearch#291]
Feedback from IDEAS regarding background and text colors: 

"liked the Worldcat link (they liked the look and location) but overall they found it difficult to look at without straining their eyes. It seems that the light gray background and the light gray text and icons made it difficult for people to find what they needed... difficult time focusing on the screen and discerning the facets from the results and the light blue text almost blends in with the background."

![new ui color](https://cloud.githubusercontent.com/assets/25326379/23715291/18c77cd0-03fa-11e7-887a-d355d64ca246.png)

Is it possible to contrast the colors more?

**Comment by winthropo** [comment]
Of course I have an opinion! I agree, a little bit, with the light blue comment, but don't see a problem with the facets or action buttons. 

My $.02

**Comment by elizoller** [comment]
Darker location links:
<img width="1134" alt="screen shot 2017-03-13 at 9 27 32 am" src="https://cloud.githubusercontent.com/assets/5439169/23856250/70917bc2-07cf-11e7-9113-20c4f7d02af6.png">

**Comment by winthropo** [comment]
@RPagani OK to close this?

**Comment by RPagani** [comment]
Looks good to me.
