### ISSUE TITLE
Linking to new UI beta from Library site

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#292]
"Try the beta version" in red. For April 3rd launch. 

Although not necessary, it would be nice it this was a passthrough. Ernesto will investigate. 

Thanks. 

![trybeta](https://cloud.githubusercontent.com/assets/4663357/23999705/8e9da688-0a2f-11e7-80bd-4cf9c4ee85a3.png)

**Comment by elizoller** [comment]
This is up on dev: https://librarydev.neu.edu
will deploy to production Monday ~7am

**Comment by elizoller** [comment]
Deployed to prod
