### ISSUE TITLE
Remove Law Scope from Library Site and SOS

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#297]
This decision was approved by READ, Snell Admin, and Law Admin

![lawjob1](https://cloud.githubusercontent.com/assets/4663357/24458223/4a6a4994-1466-11e7-80ec-949a7a163bfc.png)

![lawjob2](https://cloud.githubusercontent.com/assets/4663357/24458226/4b8c7b4e-1466-11e7-852f-56498f67ef50.png)

**Comment by elizoller** [comment]
This is up on librarydev and NUdev on staging
Will deploy to production with the rest of the changes on Monday morning

**Comment by elizoller** [comment]
Removal of law scope deployed to prod
