### ISSUE TITLE
Duplicate Relevance drop downs

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#30]
![screen shot 2013-06-10 at 3 37 30 pm](https://f.cloud.github.com/assets/2441612/633625/aa22e69a-d205-11e2-9502-4b08cfb9b3ae.png)
- URL: http://onesearch.library.neu.edu/primo_library/libweb/action/search.do?dscnt=0&frbg=&scp.scps=scope%3A%28NEU%29%2Cprimo_central_multiple_fe&tab=default_tab&dstmp=1370893043732&srt=rank&ct=search&mode=Basic&dum=true&indx=1&vl(freeText0)=&fn=search&vid=NU
  - Browser: Chrome 27 on Mac
-  Browser: Firefox 21 on Mac!
  - Description:  When you click the search arrow with no search terms you get 2 Sorted By: relevance markers....

**Comment by bassettsj** [comment]
Can't fix this one. This is a primo system issue.
