### ISSUE TITLE
Testing of My Account functionality in new UI

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#300]
We need to test all aspects of _My Account_ in New UI especially _My Favorites_ 

- Does _E-Shelf_ functionality, in old UI, migrate and display in _My Favorites_ in new UI properly?
- OVERVIEW
- LOANS
- REQUESTS
- FINE + FEES
- BLOCKS + MESSAGES
- PERSONAL DETAILS

**Comment by jasf-** [comment]
I spent a few minutes looking My Account, and it seems pretty solid to me - definitely an improvement over the version in our current UI.  

My loans and e-shelf favorites migrated and displayed correctly.

Minor quibble - it seems odd to me that there's no way to change the sort of the My Favorites list, and no indication as to what order they're displayed in.  It looks as though they're in order of addition, with most recently added items going to top.  Not a bad default, just not very transparent about the display choice.

**Comment by winthropo** [comment]
I'm going to close this. Please reopen if you want.

**Comment by jasf-** [comment]
Quick comment and then I'll re-close.  Just got this email - this is good news.

![sorteshelfaug](https://user-images.githubusercontent.com/4661920/26929909-726ff48e-4c29-11e7-97c7-9e7a1ccfbe43.png)

**Comment by winthropo** [comment]
woohoo!
