### ISSUE TITLE
Broken Accessibility Statement Link

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#301]
Anyone remember what this was supposed to link to? 

Loops back to Primo. 

![brokenlink](https://cloud.githubusercontent.com/assets/4663357/24472363/6f9b1e0a-1493-11e7-9c78-4f76bd81440a.png)

**Comment by jasf-** [comment]
Ha.  Nope.  And I can't find evidence of this link, working or otherwise, amongst our local friends with Primo.

**Comment by elizoller** [comment]
This link has never actually pointed to anything since the initial creation of the footer template - https://github.com/NEU-Libraries/scholar-onesearch/blame/develop/templates/nu_footer.jade

**Comment by winthropo** [comment]
I guess we should remove it
