### ISSUE TITLE
Title tags in new UI

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#302]
Apologies if this has been discussed already - I just noticed it.  

Here's the title tag in the new UI before a search is run.  
![sosnosearch](https://cloud.githubusercontent.com/assets/4661920/24526030/9fd77992-156a-11e7-8174-d67b8da03fb1.png)

Run a search and your search term appears in the title tag.
![titlewithsearchterm](https://cloud.githubusercontent.com/assets/4661920/24526079/b83d2306-156a-11e7-89ef-7bef009c510d.png)

Your last search term persists in the title tag even when you meander off to other areas of the site (like My Account), which seems a bit odd/buggy.
![lastsearchpersists](https://cloud.githubusercontent.com/assets/4661920/24526106/d3c1da0e-156a-11e7-9de2-844cd41a9c71.png)

Not reporting an issue per se, and certainly not a priority, just memorializing/asking if this is working as we'd like it to.

**Comment by winthropo** [comment]
Interesting. Didn't notice that. This morning I don't have a strong opinion on this. I could disable it if READ wants...tagged for future READ discussion.

**Comment by jasf-** [comment]
READ discussed 6/8/17.  Going to leave these as they are.
