### ISSUE TITLE
Cannot see WorldCat passthrough button

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#303]
Basic search/keyword results page looks like the attached.  The WorldCat passthrough is not available. 

![screen shot 2017-04-04 at 10 56 30 am](https://cloud.githubusercontent.com/assets/2442078/24663306/86d5b60c-1925-11e7-9a25-d1d46a7b9658.png)

The URL I am using is the one on the library home page. 

MacOSX
Chrome Version 51.0.2704.63 (64-bit)

**Comment by elizoller** [comment]
I can't replicate this in chrome on mac - wondering if the styling is cached in your browser - is your pagination on the right or left (if its on the right then the styling is not cached, if its on the left then try clearing your cache)

**Comment by winthropo** [comment]
Fixed this by upgrading browser.
