### ISSUE TITLE
Report a problem captured URL

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#304]
When you are in the beta and you click "Report a problem" the form captures a URL that looks like this

http://northeastern-primostaging.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=TN_mla2010421069&context=L&vid=NUdev&search_scope=new_everything_scope&tab=default_tab&lang=en_US

But it's not actually primo staging or vid=NUdev

Not urgent--maybe fix before going live this summer, however.

**Comment by winthropo** [comment]
@gam5 can you fix this? New UI Production report a problem needs to send production links not staging links.

**Comment by elizoller** [comment]
This should be fixed with 70b6db99ca9c9afd96683ea8e5f35d2468268e76 and 2747dd7101798df1a6ca26d04ee408df2db70057
if vid=NU then it goes to prod library website form with prod url
if vid = anything but NU it goes to dev library website form with staging url
