### ISSUE TITLE
Annex Request Button Not showing in Primo staging

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#305]
Could it be related to the server move @nestochan ? 

Here is what Ex Libris said they did to fix the problem in SF case: 00237828

-The "primo_pds_url" & "primo_pds_test_url" parameters in Alma were changed to "https://dc02vg0308na.hosted.exlibrisgroup.com:443/pds?". 
-The Shibboleth identifier (001277847) was defined as the test user identifier in Alma. 
-In PDS , the file "01NEU_INST.tags" was renamed to "01NEU_INST_primo.tags".

**Comment by winthropo** [comment]
fixed. thanks!

**Comment by nestochan** [comment]
🃏  -- ***NP.***
