### ISSUE TITLE
Request & Request from another library link size

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#306]
Can we make these links a little bigger?

![small request button](https://cloud.githubusercontent.com/assets/4663357/24964771/2edf5db2-1f70-11e7-86ba-86a5d977bf2f.png)

**Comment by winthropo** [comment]
....was discussing the new Library Annex with Amira the other day. She definitely wants to see these request links better. She brainstormed making them bigger, different color, and giving them a border to make them actual buttons. We don't necessarily have to do that, I don't think, but they do need to be more visible.

**Comment by kmerguerian** [comment]
I think it also needs to be clearer what the Request button is.

**Comment by kmerguerian** [comment]
I suggest "Request this item"

**Comment by winthropo** [comment]
What do you think of this buttonization?

![request2](https://cloud.githubusercontent.com/assets/4663357/25249464/ecfef8e6-25df-11e7-8d15-a8cf341389d6.png)

**Comment by kmerguerian** [comment]
Definitely looks more clickable that way!

**Comment by winthropo** [comment]
@gam5 I don't think this buttonization of the request link is in production. Can you do that?

**Comment by winthropo** [comment]
Do people like how this looks in production?

**Comment by winthropo** [comment]
Do folks think the request links in these screenshots are prominent enough? 

![screen shot 2017-08-08 at 8 49 28 am](https://user-images.githubusercontent.com/4663357/29072647-860b16fa-7c16-11e7-8624-11a6b1f228db.png)


![screen shot 2017-08-08 at 8 46 13 am](https://user-images.githubusercontent.com/4663357/29072552-19f805fe-7c16-11e7-8f5b-bb2f8a71ad8c.png)

**Comment by winthropo** [comment]
No comments on these so I will assume we like them. Open if you would like to comment.
