### ISSUE TITLE
Confirmation screen after placing an annex request

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#307]
Instead of "Request placed" 
change to

"Thank you!  Your request has been received. Check your email for a confirmation message."

**Comment by kmerguerian** [comment]
Amending this--it should include delivery time and notification info, so users know what's going to happen and when. Something like: 


Thank you for your request.  We will notify you by email when this item is ready to pick up at Snell Library. Normal delivery time is two days.

**Comment by winthropo** [comment]
Changed it to "Thank you for your request. We will notify you by email when this item is ready to pick up."

Looks like this label is set at the institution level so I don't think we can say Snell. And I don't think we can say 2 days for other reasons.

We can discuss at some READ.

**Comment by kmerguerian** [comment]
Thank you!

**Comment by winthropo** [comment]
Can this ticket be closed @kmerguerian ?

**Comment by winthropo** [comment]
Please feel free to reopen with an update.
