### ISSUE TITLE
Move virtual browse

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#309]
Please move virtual browse up. Below ViewIt/Getit and above Details and Related Links. 

![screen shot 2017-05-03 at 3 40 46 pm](https://cloud.githubusercontent.com/assets/4663357/25678304/48a79bee-3017-11e7-899a-5daa9f38c4d9.png)

**Comment by gam5** [comment]
Deployed on Sandbox

**Comment by elizoller** [comment]
Was it a config or a JS fix?

**Comment by gam5** [comment]
JS, based on this code: https://github.com/muratseyhan/primo-explore-section-ordering

**Comment by gam5** [comment]
Deployed in Production.
