### ISSUE TITLE
Hide Tags Feature

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#310]
READ agreed that we want to hide all things Tags in Primo. 

According to a very long Alma-L thread (May release and Tags). EXL advised this method for hiding the tags feature in the May release. 

After investigation i have found that the tags can be disabled by: 
1. Tags main menu link is removable vi the BO views wizard. 
2. Use the following CSS to hide the Tags section and button on the full record: 

#tags {display:none;} 
button[aria-label="Tags"]{display:none;}

**Comment by gam5** [comment]
Tags have been hidden in staging.
