### ISSUE TITLE
Adding a chat widget tab

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#311]
Add a chat widget tab to the page similar to this page on the dev site
https://librarydev.neu.edu/get-help/ask-a-librarian

![screen shot 2017-05-25 at 12 26 00 pm](https://cloud.githubusercontent.com/assets/2442078/26459754/85f8f242-4145-11e7-8dff-6369ede7f355.png)

There are options for different color tabs.  See
http://www.textalibrarian.com/tabsgallery.php

To log in to mosio for the script, contact me and I'll give you Snell's  credentials.

**Comment by elizoller** [comment]
Are you wanting this on every page?

**Comment by kmerguerian** [comment]
I will check with Nicole and Brian and get back to you.  What are the options or categories of pages that can be selected?

**Comment by winthropo** [comment]
@kmerguerian what is the latest with this?

**Comment by kmerguerian** [comment]
I’ll ask Evan what his vision for chat widgets is going forward.
Karen

**Comment by winthropo** [comment]
Is there an update on Evan's vision?

**Comment by kmerguerian** [comment]
I can ask, I have a meeting with him tomorrow morning.

Karen Merguerian
Northeastern University Libraries


On Aug 8, 2017, at 8:38 AM, "Scott Carlisle" <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there an update on Evan's vision?

**Comment by kmerguerian** [comment]
Update: I’ve been invited to a meeting to discuss the future of chat on the 23rd of August. Hope to flesh out Research and Learning’s vision at that time.

Karen


From: "Merguerian, Gayane Karen" <g.merguerian@northeastern.edu>
Date: Tuesday, August 8, 2017 at 9:07 AM
To: NEU-Libraries/scholar-onesearch <reply@reply.github.com>
Subject: Re: [NEU-Libraries/scholar-onesearch] Adding a chat widget tab (#311)

I can ask, I have a meeting with him tomorrow morning.

Karen Merguerian
Northeastern University Libraries



On Aug 8, 2017, at 8:38 AM, "Scott Carlisle" <notifications@github.com<mailto:notifications@github.com>> wrote:

Is there an update on Evan's vision?

**Comment by winthropo** [comment]
Is there an update @kmerguerian ?

**Comment by kmerguerian** [comment]
I have the impression Evan is not ready to support a chat widget until we are fully staffed in R&I and have a better sense of what it would take to support local chat service.

Karen

On Aug 29, 2017, at 10:59 AM, Scott Carlisle <notifications@github.com<mailto:notifications@github.com>> wrote:


Is there an update @kmerguerian<https://github.com/kmerguerian> ?
