### ISSUE TITLE
Browse search & journal search 'dead ends'

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#313]
Once you start using the browse search, or the journal search, it seems as though you get 'stuck' there - there doesn't seem to be an intuitive way to switch to a different method of searching.  

The basic search offers a link to advanced search (and vice versa).  Should we consider adding a similar link to basic search to browse search and journal search, or are we okay with it as is?

**Comment by winthropo** [comment]
I think I understand your point. 

You can click on Scholar One Search in upper left hand corner to return to basic search. Is that not intuitive? It is to me. But maybe I'm not normal?

**Comment by jasf-** [comment]
It feels buggy to me, especially since we currently offer an option to return to basic search from browse.

![now](https://cloud.githubusercontent.com/assets/4661920/26645970/e92df256-4607-11e7-95a8-c917fe3fb1fe.png)

But if READ thinks it's NBD, that's okay with me.

**Comment by winthropo** [comment]
Maybe something like in the staging clean view?

http://northeastern-primostaging.hosted.exlibrisgroup.com/primo-explore/search?vid=NU_CLEAN

![screen shot 2017-05-31 at 2 01 51 pm](https://cloud.githubusercontent.com/assets/4663357/26646480/c7793e02-4609-11e7-8ed1-5910bbd73be6.png)

**Comment by winthropo** [comment]
I like how they labeled it "New Search."

![screen shot 2017-05-31 at 2 07 32 pm](https://cloud.githubusercontent.com/assets/4663357/26646710/9eb24d1e-460a-11e7-9793-58b8255bae99.png)

**Comment by jasf-** [comment]
👍

**Comment by winthropo** [comment]
Hey @gam5 since I'm seeing this in the clean ... can you work your magic and reveal the Library Search link in Staging vid=NU?

**Comment by winthropo** [comment]
OK. Made the change in staging. Give it a try. We could also have it open in a new tab if you prefer. 

http://northeastern-primostaging.hosted.exlibrisgroup.com/primo-explore/search?vid=NU

![screen shot 2017-05-31 at 2 39 04 pm](https://cloud.githubusercontent.com/assets/4663357/26647961/f39da9a0-460e-11e7-9544-94283a2f6f15.png)

**Comment by jasf-** [comment]
Super.  Thanks.

**Comment by winthropo** [comment]
I made the change in production.

**Comment by jasf-** [comment]
I think we can close this now, yeah?  Feel free to reopen if need be.
