### ISSUE TITLE
Rename facet 'creation date' --> 'date'?

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#314]
This would be consistent with the label in our current SOS instance.  Yay/nay?

**Comment by winthropo** [comment]
Hey @gam5 could you look at this in the back office and fix in prod and staging? I'm a little bit confused by what I'm seeing.

**Comment by gam5** [comment]
I'll take a look.

**Comment by winthropo** [comment]
I filed a case too. 

https://exlibrisgroup--c.na26.visual.force.com/apex/VF_Case_WithoutJira?id=5003200001DJ8yGAAT

These label and text discrepancies between the two UIs are frustrating.

**Comment by winthropo** [comment]
Fixed.
