### ISSUE TITLE
Remove Facets on the left customization

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#318]
In Staging. Please remove our customization that moved the facets to the left side. And then you can, or I can, switch the new button in the views wizard that is used to accomplish this in the May release. Thanks. 

![screen shot 2017-06-05 at 9 54 52 am](https://cloud.githubusercontent.com/assets/4663357/26786579/17b0699e-49d5-11e7-8040-4880969135bb.png)
According to the May release highlights:
_The default of the new interface is to present the facets at the right side of the results. In customer usability tests, users found this logical and intuitive. However, we know that some libraries prefer to present facets at the left side of the results, so we have added an easy option to configure this without the need for customization. If you have already implemented such a customization, we recommend that you remove it in order to use the new configuration._

**Comment by elizoller** [comment]
Lines 1-15 are the only lines affecting this so they can just be removed in favor of the back office config

**Comment by elizoller** [comment]
I'm actually not satisfied with EXL implementation of facets on the left.
I chose to align the facets the search box. EXL chose to align the facets to the left side of the page but that makes the results not line up with the search box which (in my opinion) causes too much misalignment of content.
NU implementation:
![screen shot 2017-06-05 at 2 45 21 pm](https://cloud.githubusercontent.com/assets/5439169/26798208/a2855976-49fd-11e7-9f5f-dd37eb4730bb.png)
EXL Implementation:
![screen shot 2017-06-05 at 2 45 14 pm](https://cloud.githubusercontent.com/assets/5439169/26798210/a434e840-49fd-11e7-8c53-06fb5b48684e.png)

**Comment by elizoller** [comment]
@winthropo pointed out that the EXL implementation provides more width for the facet text which is a definite bonus. If I'm the only one feeling so strongly about the alignment then I'm good to just leave it with the EXL way. It would also make it easier for upgrades and one less customization to maintain.

**Comment by winthropo** [comment]
I like going the EXL way for the reasons you list. OK to do this now that prod is upgraded to May.

**Comment by gam5** [comment]
Done.
