### ISSUE TITLE
Search box in 'my account' looks wonky in Chrome

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#32]
![searchmyaccount](https://f.cloud.github.com/assets/4661920/633680/1ea2c4a8-d207-11e2-9dd0-1649deda1843.png)

URL:  http://northeastern-primostaging.hosted.exlibrisgroup.com:1701/primo_library/libweb/action/myAccountMenu.do?vid=NU

Browser/OS:  Chrome 27, Mac

Description:  Might just be something unique to my setup, but the search box looks wonky

Priority:  low

**Comment by bassettsj** [comment]
Still is wonky, but I am working on it.
Looks like this now:

![screen shot 2013-06-12 at 4 30 49 pm](https://f.cloud.github.com/assets/1218420/645169/fcfcd0de-d39e-11e2-9319-72738f784307.png)
