### ISSUE TITLE
Permalink Labels

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#320]
Should we label them something else since we know they aren't really permanent? 

One suggestion is “Copy record link” or something like that. Please leave a comment if you have a suggestion for READ to discuss. I don't think the label should be too long. I think no more than two words would be best -- one word better. 

There are few places in the code table to make this update. 

![screen shot 2017-06-05 at 11 37 21 am](https://cloud.githubusercontent.com/assets/4663357/26790891/5b8cbbe6-49e3-11e7-8545-48a9b0a5350e.png)

**Comment by jasf-** [comment]
"Direct link"?

**Comment by RPagani** [comment]
I kinda like "record link" - in the case of articles, it really does only take you to the record link and not a permalink for the actual article.

**Comment by kmerguerian** [comment]
Maybe "Get a link" (used in sharepoint/onedrive) or Get Shareable Link (that's what Google Drive uses)

**Comment by winthropo** [comment]
I don't have a strong opinion on what we label this. But please keep in mind how crowded this area already is in certain places. Something like "Get Shareable Link" might be awkward in some places. Like here:

![screen shot 2017-06-05 at 12 59 54 pm](https://cloud.githubusercontent.com/assets/4663357/26794256/f6c84d18-49ee-11e7-87db-18636f41cfa5.png)

**Comment by kmerguerian** [comment]
Makes sense, so just "Get a link" might work better.

**Comment by RPagani** [comment]
I like having the action word before link - "get a link" "copy link" "share link"

**Comment by kmerguerian** [comment]
I'm in favor of any of those action words options.

**Comment by winthropo** [comment]
We agreed to "Link"

**Comment by winthropo** [comment]
I made the label change to the new UI. Since our old UI has some customizations in that area @elizoller would have to make the name change there. Since we are so close to dropping the old UI I told Eli only update the old UI if it is easy to do.

**Comment by elizoller** [comment]
Should be easy to do. Will push up tomorrow morning.

**Comment by elizoller** [comment]
Deployed
