### ISSUE TITLE
Report a Problem not working on full record view

### ISSUE THREAD

**Issue by gam5** [NEU-Libraries/scholar-onesearch#321]
On both production and sandbox, the Report a Problem link does not seem to be working in the full record view. Works fine in brief results list. 

Seeing this error in the JS console:
Error: vm.prmActionCtrl.onToggle is undefined

It doesn't work at all on sandbox, but does seem to generally work on the second click on prod.

**Comment by elizoller** [comment]
I'll take a look. Sometimes they change the names of functions and/or change the JS code so the customizations I made may need to be updated.

**Comment by elizoller** [comment]
Note: this is fixed on dev only. The function moved on the newest version. So once prod is updated and the updated code is deployed to prod, this will be fixed. For now the second click is the only way it works on prod.
