### ISSUE TITLE
Direct login to my account

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#323]
On the library website, we have URL http://library.northeastern.edu/myaccount

that redirects to the login page for SoS Primo. 

When the new UI is implemented, this will have to point to a new URL. From another library on the Primo listserv, I came up with this:

http://onesearch.northeastern.edu/primo-explore/login?vid=NU&targetURL=http://onesearch.northeastern.edu/primo-explore/favorites?vid=NU&section=items

I've tried successfully in Chrome and Firefox on the Mac and it seems OK. Please test this URL in your browser and let me know if you can log in successfully!

**Comment by jasf-** [comment]
Yep, works for me!  🎉

**Comment by kmerguerian** [comment]
Great thanks!

**Comment by winthropo** [comment]
going to close this but reopen if needed.
