### ISSUE TITLE
Browse List Label Order

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#324]
From the feedback form on Friday. 

_Browse search default should be title. Users won't realize "subject" means subject headings and will use a keyword search, "well, that's my subject."_

This is easy to do. Should the order be:

Title (default)
Author
Subject
LC

Something else?

**Comment by winthropo** [comment]
doesn't appear to be much interest in this one. closing the ticket.

**Comment by winthropo** [comment]
There seems to be some interest in this so I'm going to open it up.

**Comment by jasf-** [comment]
I agree that subject is not an ideal default and I like your suggested order.

**Comment by winthropo** [comment]
It is now:

Title (default)
Author
Subject
LC

Closing.

**Comment by kmerguerian** [comment]
Thank you Scott!
