### ISSUE TITLE
Add link to new acq list to SOS

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#329]
There was a response to Karen’s post about the new SOS UI, asking for a new titles list. Karen responded and pointed the individual to our new titles list.  Got Patrick and Amira to wonder if there should be a link on SOS for this?  It currently seems buried in the Research tab.

Thoughts on where to put this link?

**Comment by winthropo** [comment]
How 'bout between E-Journal Finder and Databases?

![screen shot 2017-07-10 at 10 07 15 am](https://user-images.githubusercontent.com/4663357/28021956-a840619c-6557-11e7-977c-a08d7f4f7526.png)

**Comment by kmerguerian** [comment]
If the new title list is going to continue to function, let's do a monthly blog post or revolving feature each time there's an update, that way it can show up on the home page also.

Karen Merguerian
User Services
Northeastern University Libraries


On Jul 10, 2017, at 9:55 AM, "Scott Carlisle" <notifications@github.com<mailto:notifications@github.com>> wrote:


There was a response to Karen’s post about the new SOS UI, asking for a new titles list. Karen responded and pointed the individual to our new titles list. Got Patrick and Amira to wonder if there should be a link on SOS for this? It currently seems buried in the Research tab.

Thoughts on where to put this link?

**Comment by winthropo** [comment]
As far as I know its going to continue to function. Unless you've heard something. 

Any thoughts on the original post's question? Where to put the link?

**Comment by jasf-** [comment]
I would vote for *not* between e-journal finder & databases, mostly because those seem to me to belong near each other (as does the DRS, to some degree).   What about after the DRS, or near the browse?

That menu is getting pretty dense.  But if we need a link in SOS to new titles, that's the spot for it.

**Comment by winthropo** [comment]
I'm fine with either of those proposals.  

I agree it is getting dense, but I don't think we have the option of not putting a link somewhere.

**Comment by winthropo** [comment]
Set it up in staging to see how crowded it would look. I think if we were to label the link "Selected New Acquisitions List" it might look ridiculous. So I removed "Selected." 

I also assume we want it to open in a NEW window. 

![screen shot 2017-07-10 at 10 51 39 am](https://user-images.githubusercontent.com/4663357/28024178-f07aeba2-655d-11e7-808c-744e7c926beb.png)

**Comment by winthropo** [comment]
It hides the Browse link. The limit looks to be 6 links.

**Comment by jasf-** [comment]
Curious - is it possible to see stats on how often those various links are used?

**Comment by winthropo** [comment]
READ approved. closing.
