### ISSUE TITLE
"Send to" menu is partially invisible 

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/scholar-onesearch#33]
- URL: http://northeastern-primostaging.hosted.exlibrisgroup.com:1701/primo_library/libweb/action/basket.do?fn=display&fromUserArea=true&vid=NU&fromPreferences=false
- Browser: Chrome on iPad
- Description: 
  I clicked Send To from the View Online tab, and the drop down is partially invisible/obscured.
  In the Details and Related Links tab the drop down looks fine.
  It also looks fine in the Recommendations tab.

![image](https://f.cloud.github.com/assets/4663073/633803/bd9c3e2a-d209-11e2-9199-2ba9ff502e57.jpg)

**Comment by bassettsj** [comment]
Still working on this one. It is difficult to resolve, but I will try!
