### ISSUE TITLE
SOS search box in LibGuides

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#333]
First two SOS search boxes I checked in Libguides are broken. Perhaps more?

Advanced Writing in the Disciplines (AWD) : Academic Research is broken. 

American Sign Language (ASL): Find Books + Media is broken.

Brings user to here:

![screen shot 2017-07-11 at 12 53 45 pm](https://user-images.githubusercontent.com/4663357/28079971-4e8b3028-6638-11e7-8cc0-1bf50172ebe3.png)

**Comment by winthropo** [comment]
I think @kmerguerian fixed these. Reopen if I have that wrong. Thanks Karen.

**Comment by kmerguerian** [comment]
I believe the search boxes are now pointing to the new UI correctly.  I sent around a note asking editors to let me know if they notice errors.
