### ISSUE TITLE
URL for e-journals?

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#334]
Verifying: this is the new ejournal finder URL?

http://onesearch.library.neu.edu/primo_library/libweb/action/dlSearch.do?institution=NEU&vid=NU&query=facet_atoz%2cexact%2cA&indx=1&bulkSize=30&dym=false&loc=local%2cscope%3a(AZNEU)&fn=goAlmaAz&sortField=stitle&almaAzSearch=true&azSearch=true&selectedAzAlmaLetter=A&_ga=2.94511388.1027074939.1499778336-1565093838.1496699445

Is there a direct URL for the journal title search in the Advanced Search?

**Comment by gam5** [comment]
This would be better for the ejournal finder: http://onesearch.library.neu.edu/primo-explore/jsearch?vid=NU&lang=en_US

**Comment by kmerguerian** [comment]
Great, thanks!!!!

**Comment by gam5** [comment]
There is no direct url for the Journal Title Search. That is purely a JavaScript trick.

**Comment by kmerguerian** [comment]
OK to use this for the catalog-only scope

http://onesearch.library.northeastern.edu/primo-explore/search?vid=NU&search_scope=nu_scope2

**Comment by gam5** [comment]
Looks good.
