### ISSUE TITLE
Home page search box: catalog scope

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#335]
When you do a "library catalogs" search from the library home page, it does not scope the search to the catalog. (Reported by a professor, at the ref desk.)

In the libguides, I'm adding 
<input name="search_scope" type="hidden" value="nu_scope2" />
to the search box widget forms.  It seems to work. Not sure if that helps with the drupal search box coding.

**Comment by kmerguerian** [comment]
Sorry, this is what I'm adding, did not escape those angle brackets correctly in markdown. 

&lt;input name="search_scope" type="hidden" value="nu_scope2" /&gt;

**Comment by gam5** [comment]
Updated the Catalog scope to nu_scope2.
