### ISSUE TITLE
Course reserves facet in new release

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#342]
We have a course reserves facet now, which is pretty nifty!   The display is confusing, though.  There's actually just one item on course reserves that surfaces using this search term (epigenetics), but it appears in three ways, including my personal favorite, 'null'.
 
![nullcoursereserves](https://user-images.githubusercontent.com/4661920/29275713-0340dd04-80da-11e7-8f47-8ddeabeab3a0.png)

**Comment by winthropo** [comment]
Even if this was working in staging. I wonder if we should hide this facet since we already have a crowded facet area and a Course Reserve search scope.

**Comment by jasf-** [comment]
I'd actually be more inclined to kill the search scope in favor of the facet, thinking that it would attract more attention/use there.  But I take your point about the crowdedness of the facet area.

**Comment by winthropo** [comment]
If we can't fix this facet by September I hope it would be OK to hide it until we can resolve and move forward with the August release.

**Comment by RPagani** [comment]
I'm in favor of the search scope, but I remember this facet being available in the old UI and in our current production... maybe we can discuss it with Erin to see how she directs users?

**Comment by winthropo** [comment]
Yes, the course reserves facet is enabled, right now, in production.

**Comment by winthropo** [comment]
Nicole is investigating the Null value shenanigans.

**Comment by winthropo** [comment]
Closed due to inactivity. I'll reopen if there is an update to share.
