### ISSUE TITLE
Reset filters, also buggy

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#344]
When you lock a facet (or a group of facets), clicking on "reset filters" doesn't actually reset the filters. 

Maybe this is deliberate? If you have a combination of sticky and non-sticky filters it clears the non-sticky ones only. 

So what does "reset filters" really mean?  Just clears non-sticky filters? this is a very subtle distinction and when you click and nothing happens your system seems buggy.  If it says reset filters it should reset filters.

**Comment by winthropo** [comment]
After looking at the documentation. My take - it is deliberate. Not defending it or taking a stand though. 

They want users to be able to reset the non-sticky filters while keeping the sticky filters locked. You have to first use the lock icon to do anything with the sticky. 

I don't know enough about UI/UX/design to comment more on this. But I think you should close this GitHub issue unless you can identify a configuration setting in the back office for us to fix this. 

You can do a combination of the following things. Let me know if you want to discuss further. 

1. Put this on Ideas Exchange
2. We push it through the very slow NERS process 
3. You file a case with EXL and try to convince them that it is a bug. With a clear proposal for how you think this should be designed.

**Comment by kmerguerian** [comment]
Actually for this I may write in to the Primo listserv just to see if there’s a consensus of opinion.  One person raised it as a possible bug early on, but I don’t know if others don’t agree or just not everyone has this release yet and has messed around with this feature.

Karen

**Comment by winthropo** [comment]
That's a great idea. If you can get a ton of folks to complain along with you. You you might get something from them.

**Comment by winthropo** [comment]
I'm going to close this because I don't think there is anything we can do right now in the back office to fix this. Please reopen if you think we should.

**Comment by winthropo** [comment]
You could put something in Ideas Exchange and then reference that in your email. Good way to get votes.
