### ISSUE TITLE
Availability of mail-to in SoS

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#345]
Often when helping users I like to look at the full record together so we can see the details or contents, and if it's suitable, email the citation to the user.  That's also how I send e-books.  It would be great if there were an email option in the record display modal. 

I realize I can go back to the results list, but sometimes I lose my place in that list and don't know which article I was looking at.  Especially if they all have similar titles.  It would be nice to have an email button in the full record so I could email right when I know I'm looking at the right thing. 

Another way I work with students is to pin records to my favorites, and then email all the favorites. But I have to email favorites one by one, and the user receives multiple emails.  It would be great if the pinned list expansion also included an email option so I could email a batch the same way I can download an RIS file of a batch. 
![screen shot 2017-09-06 at 4 59 32 pm](https://user-images.githubusercontent.com/2442078/30134522-64a99330-9325-11e7-987b-cac9030a1d1e.png)

**Comment by kmerguerian** [comment]
(above is a picture of the "push to" button on the my favorites page.)

**Comment by winthropo** [comment]
Yeah. Jen has mentioned this to me before. I'll investigate. Thanks.

________________________________

**Comment by winthropo** [comment]
Fixed. Closing issue. Reopen if you see any funny business. 
-------

![emailthing](https://user-images.githubusercontent.com/4663357/30165081-c4837988-93ac-11e7-8bf7-aa67dd630762.png)

-------

![screen shot 2017-09-07 at 9 11 27 am](https://user-images.githubusercontent.com/4663357/30165084-c6a4a20a-93ac-11e7-901a-b742f278779f.png)

**Comment by jasf-** [comment]
This is very helpful, thanks.  Also, I approve of your new search string.

**Comment by kmerguerian** [comment]
I think the permalink got lost in the shuffle somehow.

**Comment by winthropo** [comment]
Yeah, there is a limit of 9 I think. I've returned it back to the way it was. 

I'll see if there is data on what is used. And if the citation management people on READ could have a discussion to see if we really need all of these:

Export Bibtex
RIS
Refworks
Endnote Web
Easybib

And keep in mind that at some point Zotero support will be a thing. I've heard first half of 2018.

**Comment by winthropo** [comment]
Let me know if I should schedule a 2 hour meeting for READ to discuss.

**Comment by winthropo** [comment]
Since we went live with new UI:

![screen shot 2017-09-07 at 11 38 47 am](https://user-images.githubusercontent.com/4663357/30171891-26f29e8c-93c1-11e7-95c5-231b0d464ef5.png)

**Comment by kmerguerian** [comment]
AFAIK the library does not support Endnote Web or Easybib, but I would defer to Regina? If we got rid of both we could add the mail and Zotero.

Karen

**Comment by jasf-** [comment]
I floated the idea of removing the Easybib option a couple of months ago (#316) - READ consensus was to leave it.  But the space constraints for the 'group of 9' could be a new wrinkle.

**Comment by winthropo** [comment]
Yep. 

I hesitated on removing EasyBib - a topic I usually don't have an opinion on - because during our usability testing many of our students told us they use Easybib. Do I have that right @kmerguerian ?

The usage data I posted above isn't that helpful because it only dates back to July 10. Would it be fare to look at data from the old UI?

**Comment by kmerguerian** [comment]
Yes, two of the undergrads used it.  But that is such a small sample… it would be good to have some better data on this.

https://docs.google.com/spreadsheets/d/1WccQ-TWtdVARCLx46iBDqMxNboTrRBbbZamhuTQ1ke4/edit?usp=sharing

Karen

**Comment by winthropo** [comment]
This is for all of 2017. Were all of these available to users in 2017? 

![screen shot 2017-09-07 at 3 26 15 pm](https://user-images.githubusercontent.com/4663357/30181358-f74f3896-93e0-11e7-9d77-ad178fb6bfe4.png)

**Comment by jasf-** [comment]
I believe Easybib was new with the new UI.

**Comment by winthropo** [comment]
@kmerguerian if it is ok with you. I assigned this to you. If you don't mind being the one to follow up on a decision. Let me know if you can't.

**Comment by winthropo** [comment]
@gam5 is the report-a-problem customization preventing us from seeing this arrow? This screenshot from the EXL documentation makes me think we might not be limited to a set amount of actions. 

![gamquestion](https://user-images.githubusercontent.com/4663357/30215853-4b3198f2-947f-11e7-9a14-220c66307dd6.png)

**Comment by gam5** [comment]
Quite possibly. I'll take a look.

**Comment by winthropo** [comment]
I get this type of link in my search results email:

http://onesearch.library.northeastern.edu/primo-explore/fulldisplay?docid=TN_crossref10.1161/ATVBAHA.117.309326&context=PC&vid=NU

actions menu can be scrolled horizontally.

**Comment by winthropo** [comment]
OH yeah. PEBCAK. That scrolling behavior is odd IMHO, but yeah it is there. That's good.

**Comment by kmerguerian** [comment]
Meanwhile:

1. Regina has suggested polling R&I about removing EasyBib

2. At some point soon we are going to want to add Zotero to the list of options on this screen. 

With that in mind, can we remove Report-a-problem? After all, it's already available for each record in the list.  

The icons needed at the top of the MyFavorites are the ones that are most useful for the batch processing of selected records in the list.  Maybe Report-a-problem isn't needed there as long as it's available for each individual listed item. 

![screen shot 2017-09-21 at 11 18 14 am](https://user-images.githubusercontent.com/2442078/30704142-c15e3f18-9ebf-11e7-9a29-4e3f40657355.png)

After all, it's been there for years and no one has used it in that way...I suspect no one would notice if we removed it from that spot.

**Comment by winthropo** [comment]
@kmerguerian has R&I been polled about removing EasyBib?

**Comment by RPagani** [comment]
@kmerguerian @winthropo I'll be sending out a poll this week to R&I. I'll report back in once I get the responses.

**Comment by winthropo** [comment]
Today I filed a case with EXL to see if it is possible to have more than 9 actions in the brief display. Could be something I can't figure out but is possible...

Some updated Actions usage. From September '17 -> present. 

![screen shot 2017-11-27 at 2 07 57 pm](https://user-images.githubusercontent.com/4663357/33284262-784d22c0-d37c-11e7-81f1-d4878dd17a2a.png)
