### ISSUE TITLE
Back to search results

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#346]
After I go to My Favorites, there's no way to go back to my search.  The only option is to click the search button to repeat the search, but then you are starting all over at the top of the list.  It would be nice if there were a "back to search" button on the My Favorites page.  I realize this may be an enhancement request for Ex Libris.

**Comment by winthropo** [comment]
Thanks for reporting. Are you going to determine if it is an enhancement? Or would you prefer I do that...

If it is an enhancement it would go to Ideas Exchange. Link here: http://ideas.exlibrisgroup.com/

If it is a configuration issue it would be helpful to tag it as such.

**Comment by kmerguerian** [comment]
I might file it as a ticket first just to see if its a currently supported configuration. Is that allowed?

Karen Merguerian
Northeastern University Libraries


On Sep 7, 2017, at 8:28 AM, "Scott Carlisle" <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for reporting. Are you going to determine if it is an enhancement? Or would you prefer I do that...

If it is an enhancement it would go to Ideas Exchange. Link here: http://ideas.exlibrisgroup.com/

If it is a configuration issue it would be helpful to tag it as such.

**Comment by winthropo** [comment]
I would look at the documentation a bit first. And the back office. But sure.

________________________________

**Comment by winthropo** [comment]
The Search History feature helps this issue. I'm going to close this @kmerguerian but feel free to reopen if you submitted a case to Ex LIbris that is pending/development.
