### ISSUE TITLE
Report a Problem button in BrowZine?

### ISSUE THREAD

**Issue by rmcnally** [NEU-Libraries/scholar-onesearch#347]
Would we want a Report a Problem button in BrowZine? It seems like most trouble spots will loop back to SOS so the option isn't too far, but it could be a good idea for unforeseen problems.

I asked their support if it was possible and they said they are rolling out that functionality in a few days. We would need to discuss placement and wording.

Their e-mail:
"Not this moment, but we actually have a feature coming out in a few days which will create a library-configurable spot in the header where you can put whatever text you'd like (i.e. "Report a Problem") and have it link to wherever you want as well!

I'll touch base with you in a few days once this ships to production.

In advance though, can you spell out exactly the wording and the link you'd like it go to?  I can then just set this up for you!"

**Comment by winthropo** [comment]
POG decided against adding a report-a-problem link to Browzine.
