### ISSUE TITLE
Display Name and URL text

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#348]
Questions for @RPagani and @kmerguerian:

Do you want to use URL Text? If so, how do you specifically want me to set it up for these examples. I assume you don't want to duplicate the Resource Type label and the Display Name label. Exhibit A. 

If we don't use URL Text then the Display Name (required) is used by default as URL Text. Exhibit B. 

Exhibit A. 

![historyguide](https://user-images.githubusercontent.com/4663357/30607791-34bcc588-9d44-11e7-8185-1584130bf4db.png)

Exhibit B:

![screen shot 2017-09-19 at 2 08 49 pm](https://user-images.githubusercontent.com/4663357/30607795-39a8c61e-9d44-11e7-967f-c5458c77a829.png)

**Comment by RPagani** [comment]
I like Exhibit B with the Display Name as the linked URL; cleaner, more concise.

**Comment by kmerguerian** [comment]
Agreed!

**Comment by winthropo** [comment]
OK. I'll close it out if READ has no concerns.
