### ISSUE TITLE
Search icon next to search box on iPad 

### ISSUE THREAD

**Issue by treinhart** [NEU-Libraries/scholar-onesearch#35]
- URL: is.gd/staging
- Browser: Chrome on iPad 3
- Description: it looks like there is a search icon that just shows up on the iPad (not seeing it on laptop browsers) to the left of the search box.  It's a little misleading as another link to click on to do a search.
  ![image](https://f.cloud.github.com/assets/4664352/633831/7951432c-d20a-11e2-8526-fa23d3553d7c.jpg)

**Comment by bassettsj** [comment]
Yeah. Sorry. I removed the icon all together.
