### ISSUE TITLE
angular CSS adjustment to accommodate mobile on MainPage

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#350]
Noticed that max-width for that page is wonky. and doesn't size to device due to hard max-width set to 60% and 40%  ... if there is a 100% selector that can be assigned or if the max-width can be changed to 100% provided it isn't used elsewhere that would affect styling adversely
BEFORE:

![screenshot 2017-09-22 10 34 00](https://user-images.githubusercontent.com/2441612/30749635-fd674672-9f81-11e7-93bb-c90b34fafe60.png)

AFTER:

![screenshot 2017-09-22 10 22 41](https://user-images.githubusercontent.com/2441612/30749901-da3a3ea6-9f82-11e7-9189-22367c902ff0.png)

**Comment by nestochan** [comment]
@gam I think the best thing to do is assign flex-100 to these columns if possible. messing around with the other 2 may not be the best approach in the long run. 🃏

**Comment by winthropo** [comment]
What is the latest with this @gam5 / @nestochan ?  If I remember...@nestochan did a temporary fix, but I'm not seeing that fix in place anymore.

**Comment by gam5** [comment]
Updated CSS on Sandbox. Seems to work and not break anything.

**Comment by winthropo** [comment]
👍  I say go for it. Make it so in production.

**Comment by gam5** [comment]
Moved to production.
