### ISSUE TITLE
Tooltip interfering with Up/Down buttons in Browse

### ISSUE THREAD

**Issue by rmcnally** [NEU-Libraries/scholar-onesearch#352]
Raised in Report a Problem #3134

When in Browse and trying to click the up or down buttons, a Go to Next Page or Go to Previous Page tooltip sometimes pops up that interferes with the buttons working.

(Using Chrome on Windows)

![browseissue](https://user-images.githubusercontent.com/25803683/32295852-d9a0416c-bf20-11e7-9f3c-6d4cfb279416.jpg)

**Comment by winthropo** [comment]
I'm not seeing this at other sites with up/down on the left. I think Eli moved it to the right with a customization and not a configuration. I think this is the customization:https://github.com/NEU-Libraries/scholar-onesearch/commit/a30a65a9acf4c67229c5962095068224cc99875a

@gam5 can you take a look?

**Comment by winthropo** [comment]
Looks like this is being report again [QID:2632507](http://northeastern.libanswers.com/answer.php?qid=2632507).

**Comment by gam5** [comment]
Looks like this fix stops working on screens that are too narrow (i.e., mobile devices). I'll see what we can do.

**Comment by gam5** [comment]
Fix in place on sandbox. Browser cache clear is necessary. 

Will do more testing and if things look ok, we'll put into place early next week.

**Comment by winthropo** [comment]
👍

**Comment by gam5** [comment]
Fix has been implemented in production. Clearing browser cache will probably be necessary to view the change.
