### ISSUE TITLE
Remove Subject Guides from brief results

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#353]
I just added our Research Subject Guides to the Resource Recommender in SOS production.
 
Please remove them from the brief results page and stop the previous process of ingesting them.Thanks.
![screen shot 2017-11-21 at 11 44 02 am](https://user-images.githubusercontent.com/4663357/33085142-cfaa2aec-ceb1-11e7-9148-7b1db1cf581c.png)

**Comment by jasf-** [comment]
Nice!  🎆

**Comment by winthropo** [comment]
RIP animated beaker GIF 😢
