### ISSUE TITLE
Logo gets washed out on sign-in

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#354]
I just noticed that when signing in, the library logo gets washed out by the switch to black in that area of the page.  Happening in staging and production.  

Worth addressing?  Not sure, but I thought I'd memorialize it in any case.

Before
![purtylogo](https://user-images.githubusercontent.com/4661920/33277821-ae4ef93a-d367-11e7-9bb2-d28f6d0c345d.png)

After
![logo washout](https://user-images.githubusercontent.com/4661920/33277832-b3c309e2-d367-11e7-8aa3-350dff85a4f9.png)

**Comment by winthropo** [comment]
I don't see this issue anymore. OK to close?

**Comment by jasf-** [comment]
Ditto.  Closing.
