### ISSUE TITLE
Action Bar

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#357]
This is related to #345 

Right now in PRODUCTION. The "My Favorites" action bar displays these in order:

1. Bibtex
2. RIS
3. RefWorks
4. Endnote
5. EasyBib
6. Print
7. Report A Problem

And in Production. The Brief Record action bar displays these in order:
1. Bibtex
2. RIS
3. RefWorks
4. Endnote
5. EasyBib
6. Citation
7. Link
8. Print
9. Report A Problem

And I can't display more than 7 actions in My Favorites and not more than 9 in Brief Record. 

This morning in STAGING, vid=NU_CLEAN, I was able to display 8 in My Favorites and 10 in Brief Record. We are confident our Report A Problem customization is imposing these limits. 

**Let's see if we can get, in STAGING, these to display in both the My Favorites and Brief Record action list.** 

1. Bibtex
2. RIS
3. RefWorks
4. Endnote
5. EasyBib
6. Citation
7. Link
8. Print
9. Email
10. Report A Problem

**Comment by gam5** [comment]
It actually makes sense that "Citation" and "Link" are missing from the Favorites action bar. That area is meant to be used on multiple selected items and citation and link only make sense when you are working with one item.

**Comment by gam5** [comment]
In fact, Report a Problem is kind of wonky in this context.

**Comment by winthropo** [comment]
@gam5 made some changes to the Report A Problem customization. Now displaying this Brief Record action list in Production.

1. Bibtex
2. RIS
3. RefWorks
4. Endnote
5. EasyBib
6. Citation
7. Link
8. Print
9. Email **(new)**
10. Report A Problem

And we are displaying this for the My Favorites action list:

1. Bibtex
2. RIS
3. RefWorks
4. Endnote
5. EasyBib
6. Print
7. Email **(new)**
8. Report A Problem

I guess I agree that "Citation" and "Link" might not belong in the My Favorites action list. 

And I agree that Report A Problem should be removed from the My Favorites action list. That doesn't make sense.

**Comment by winthropo** [comment]
I'm going to close this case and open up another ticket for the Repot A Problem issue. Thanks @gam5

**Comment by winthropo** [comment]
@gam5 I can't seem to add an 11th action item to the brief record. We want to do something like this:

1. Bibtex
2. RIS
3. RefWorks
4. Endnote
5. EasyBib
6. Citation
7. Link
8. Print
9. Email 
10. Leganto **(New)**
11. Report A Problem

POG hasn't approved the addition of the Leganto action link yet. 

Can you check if the report-a-problem customization needs to be adjusted to accommodate an 11th action? If I remember right you did something to help us get 10 up there.

**Comment by gam5** [comment]
It should just be an update the the javascript that controls the report-a-problem. I'll tweak on the sandbox.

**Comment by winthropo** [comment]
Cool. I'm working on this in production because I don't want to point Primo sandbox to Alma production. Leganto is production only.

**Comment by winthropo** [comment]
This is done. Closing the ticket.
