### ISSUE TITLE
Report-A-Problem link in My Favorites action list

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#358]
@gam5 pointed out that it doesn't quite make sense to have the Report-A-Problem link in the My Favorites action list because:

A) these actions are really meant to work with more than one record at a time. Batch emailing, printing, etc. 

B) It doesn't work with multiple records right now. 

Individual records in the My Favorites area would still have a Report-A-Problem link. 

Permission to remove Report-A-Problem from this particular place? 

![screen shot 2018-01-17 at 3 33 57 pm](https://user-images.githubusercontent.com/4663357/35065689-fb829606-fb9b-11e7-9515-04d4c2facecd.png)

**Comment by rmcnally** [comment]
Seems reasonable to me.

**Comment by jasf-** [comment]
👍

**Comment by kmerguerian** [comment]
Agree

**Comment by tomhohenstein** [comment]
👍

**Comment by RPagani** [comment]
removing it works for me!

**Comment by winthropo** [comment]
@gam5 when you have a moment you can remove it from prod and sandbox. Thanks!

**Comment by gam5** [comment]
I'm working on it. It's a bit more complicated than it would seem.

**Comment by winthropo** [comment]
@gam5 Is there an update on this? Not a high priority.

**Comment by winthropo** [comment]
@nestochan recommended closing this ticket. We can revisit later if we want. Closing.
