### ISSUE TITLE
Deploy TLS security on custom Primo Domains

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#359]
Work with EXL to deploy TLS security certificate to cover all customized SOS domains.

## **.neu.edu**
- [x] onesearch
- [ ] onesearch-test

## **.library.neu.edu**
- [x] onesearch
- [ ] onesearch-test 

## **.northeastern.edu**
- [x] onesearch
- [ ] onesearch-test

## **.library.northeastern.edu**
- [x] onesearch
- [ ] onesearch-test

**Comment by nestochan** [comment]
some link normalization required. in 4 months major browsers will flag as insecure -- mixed or non encrypted sites.

**Comment by winthropo** [comment]
Can this be closed?

**Comment by nestochan** [comment]
@winthropo we haven’t done test — but if you want to close it you can go ahead.

-e
