### ISSUE TITLE
Dropdown not lined up with searchbox

### ISSUE THREAD

**Issue by primo-testing** [NEU-Libraries/scholar-onesearch#36]
Browser: Firefox 21 in Windows 7

Description: dropdown is not lined up with search box window

Screenshot
https://dl.dropboxusercontent.com/u/15646125/lineup.PNG

**Comment by bassettsj** [comment]
Perfect. I will test that out.

**Comment by bassettsj** [comment]
Fixed. Should work on redoing the "simple search box".
