### ISSUE TITLE
Worldcat passthrough in Internet Explorer

### ISSUE THREAD

**Issue by rmcnally** [NEU-Libraries/scholar-onesearch#361]
Found this testing the Nov 2017 release but it appears to be the case in both staging and production on IE. I can't get the 'Search Other Libraries' button to show at all:
![image](https://user-images.githubusercontent.com/25803683/36161738-6fe325b2-10b2-11e8-8325-0e59a375af48.png)

Same search in Chrome:
![image](https://user-images.githubusercontent.com/25803683/36161945-0373769c-10b3-11e8-8646-ecc5d8ab7d50.png)

**Comment by winthropo** [comment]
@nestochan and @winthropo discussed. Windows 10 ships with Edge browser. Not an issue with Edge. POG should start testing releases with Edge.
