### ISSUE TITLE
Link to the SOS tutorials from the SOS landing page

### ISSUE THREAD

**Issue by RPagani** [NEU-Libraries/scholar-onesearch#362]
Add a link to the [Scholar OneSearch Tutorial guide](http://subjectguides.lib.neu.edu/scholaronesearch) under the “Where can I get help?” section on the [SOS landing page](http://onesearch.northeastern.edu/primo-explore/search?vid=NU&sortby=rank&lang=en_US). The text for the link would be “Scholar OneSearch Tutorials” and would be most appropriate as the top link (above Ask a Librarian).
<img width="527" alt="sos tutorials" src="https://user-images.githubusercontent.com/25326379/36595718-491cd362-1871-11e8-8fca-cf36aae8a406.png">

**Comment by gam5** [comment]
Done.
