### ISSUE TITLE
RIS export options (RefWorks, EndNote, etc) in Send To Actions list don't work on services page

### ISSUE THREAD

**Issue by rmcnally** [NEU-Libraries/scholar-onesearch#363]
Send To Actions that use RIS for citation exports (RIS, RefWorks, EndNote Web, EasyBib) don't work from the services page/OpenURL pages. They don't have any PNX so SOS sends an unusable file.

Example:
http://onesearch.library.northeastern.edu/primo-explore/openurl?url_ver=Z39.88-2004&rft_val_fmt=info:ofi%2Ffmt:kev:mtx:journal&genre=article&sid=ProQ:ProQ:socscijournals&atitle=Faeces%20and%20the%20Old%20Sole%20of%20a%20Shoe:%20Remedies%20of%20the%20Dreckapotheke&title=Schweizerische%20Gesellschaft%20fu%CC%88r%20Asienkunde.%20Asiatische%20Studien&issn=14206854&date=2018-10-01&volume=71&issue=4&spage=1247&au=Maurer,%20Petra&isbn=&jtitle=Schweizerische%20Gesellschaft%20fu%CC%88r%20Asienkunde.%20Asiatische%20Studien&btitle=&rft_id=info:eric%2F&rft_id=info:doi%2F10.1515%2Fasia-2017-0050&vid=NU&institution=NEU&url_ctx_val=&url_ctx_fmt=null&isSerivcesPage=true&lang=en_US

It turns out this is a known issue that several libraries have brought up to Ex Libris and they're working on it. We now also have a case that has been moved to Development:
https://exlibrisgroup.my.salesforce.com/5000e00001K6TFgAAN

If it is possible to hide those icons from the services page with CSS or other programming, that could be an option.

**Comment by winthropo** [comment]
@nestochan is going to look at this.

**Comment by rmcnally** [comment]
Ex Libris hasn't updated my case, but it looks like OpenURL pages now have an ad hoc PNX and a few tests exporting to EndNote, RefWorks, and EasyBib worked for me fine, so this can probably be closed.
