### ISSUE TITLE
'Streamaudio' material type in staging

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#367]
Howdy POGgers,

While testing I came across an interesting material type in staging:

![streamaudiomattype](https://user-images.githubusercontent.com/4661920/42472726-6155d7a0-8390-11e8-8144-85fe230d6720.png)

Same record in production:

![notstreamaudioprod](https://user-images.githubusercontent.com/4661920/42472741-6d3cd424-8390-11e8-9802-0ffa84b68c0b.png)

From spot-checking it seems as though there are a number of Naxos items with material type 'streamaudio' in staging - but some Naxos items have material type 'audio'.

**Comment by kflachs** [comment]
Earlier, in the year, I was experimenting with a streaming audio type in the sandbox, but was having trouble getting it to work consistently.

I suspect this is left over from that attempt, since it is only in the sandbox.

-Kristin

**Comment by jasf-** [comment]
Aha!  Funny that it surfaced in testing.
