### ISSUE TITLE
Titles partially obscured in high contrast mode (accessibility issue)

### ISSUE THREAD

**Issue by rmcnally** [NEU-Libraries/scholar-onesearch#368]
Search terms in titles, usually underlined in yellow, will not be visible in the results list in certain browsers if the monitor is in high contrast mode. This is a problem in Firefox and Internet Explorer/Edge. (Chrome works a little differently and the Google high contrast extension doesn't show the same problem.)

![image](https://user-images.githubusercontent.com/25803683/42823342-4f1fc2be-89ab-11e8-8a76-f65febe27697.png)

![image](https://user-images.githubusercontent.com/25803683/42823479-a557fa84-89ab-11e8-86bf-c79ac01e9fe9.png)

A user reported this through LibAnswers.

**Comment by winthropo** [comment]
This might get fixed on Monday when we see the May release in prod. Let's check on Monday. Or I guess we could check staging now.....

**Comment by winthropo** [comment]
I can't replicate this problem in FF, Chrome or Safari. @rmcnally are you still seeing this? Thought the May upgrade might've fixed.....

**Comment by winthropo** [comment]
I'm going to close this case. Please reopen if you see the problem again.
