### ISSUE TITLE
Search help link

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#369]
@RPagani and I discussed the possibility of adding a link to this [page](http://subjectguides.lib.neu.edu/scholaronesearch) in the tiles section at the top of SOS. I'm putting this in staging so we don't forget about the idea. If you have any thoughts on this please let us know what you think! It does push more links to the "show more" area, but I think it would be nice to advertise that help page more. 

![screen shot 2018-09-05 at 3 12 22 pm](https://user-images.githubusercontent.com/4663357/45115622-69628680-b11e-11e8-90ec-c1fd362eab9d.png)

**Comment by jasf-** [comment]
Love it!  💯

**Comment by winthropo** [comment]
@RPagani and I discussed one last time. Added the Search Help link to production. Going to close this.
