### ISSUE TITLE
Squished text in the Locations and Status tab

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/scholar-onesearch#37]
- Browser: Chrome 27 on Linux (Android)
- Description: Locations and Status tab has some text that runs together when viewing OneSearch on my phone (Location <--> Snell Library / Available <--> 1 Copy)
  ![2013-06-10 15 41 30](https://f.cloud.github.com/assets/4663073/634879/c6c6b63e-d22b-11e2-922f-d9b722e595ed.png)

**Comment by bassettsj** [comment]
There is nothing I can do about this since the CSS again lives where I cannot access it. It is in the `mashup.css` file that I cannot access.

![screen shot 2013-06-12 at 3 07 54 pm](https://f.cloud.github.com/assets/1218420/644697/7c522340-d393-11e2-9ccc-98991288b90b.png)
