### ISSUE TITLE
Sign in text color

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#370]
Suggestion from Hillary C. to change the color of the sign in. Others have pointed this out. Maybe it could be red like the other accent colors on the page...Hillary suggests....

<img width="161" alt="unknown" src="https://user-images.githubusercontent.com/4663357/45630331-7e1c1400-ba66-11e8-9e60-30b85b88a266.png">

**Comment by gam5** [comment]
Updated on sandbox. Changed it to match other elements in the header. Let me know if you do want red.

**Comment by winthropo** [comment]
👍 I like what you have going on in staging now. I say make that change in production now and if later on we want to change to red or another color we can. 
![screen shot 2018-09-17 at 11 08 27 am](https://user-images.githubusercontent.com/4663357/45631925-15cf3180-ba6a-11e8-9678-c7a4988b8e85.png)

**Comment by gam5** [comment]
Now in Production.
