### ISSUE TITLE
Primo Google Book Preview

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#371]
Amira would like us to look into this feature because it is especially important for the Annex books. I can only find documentation for v.3 of Primo [here](https://knowledge.exlibrisgroup.com/Primo/Knowledge_Articles/How_does_the_link_to_Google_books_work).

@gam5 can you take a look at how feasible this is?

Thanks,
Scott

**Comment by winthropo** [comment]
@gam5 are you able to look into this? I think it uses GBS Viewability API.

**Comment by winthropo** [comment]
@winthropo is going to file a case with Ex Libris to see how to do this.

**Comment by winthropo** [comment]
I have this working in staging, but found out admin wants the link here. Asked EXL in a ticket. 

![GBS](https://user-images.githubusercontent.com/4663357/54928573-7b551c80-4eea-11e9-8f34-a57e32440aa5.png)

**Comment by gam5** [comment]
I think I can do the with Javascript. Maybe.

**Comment by nestochan** [comment]
cool

**Comment by winthropo** [comment]
There is a non-js solution in place in staging. example [here](http://onesearch-test.library.northeastern.edu/primo-explore/fulldisplay?docid=NEU_ALMA21159816380001401&context=L&vid=NU&search_scope=default_scope&tab=default_tab&lang=en_US).

![Screen Shot 2019-03-27 at 11 39 55 AM](https://user-images.githubusercontent.com/4663357/55090206-12ee7280-5085-11e9-9d06-dc928bcdfe1c.png)

**Comment by winthropo** [comment]
If the Javascript solution is easy to do and won't clash too much with release updates I say we go with that.

**Comment by winthropo** [comment]
Admin decided to go with the non-JS solution. I made those changes in production - closing this one.
