### ISSUE TITLE
Unpaywall links

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#372]
We have been asked by Library Administration to investigate adding unpaywall links to SOS.

Ryan has done this in staging: https://developers.exlibrisgroup.com/blog/Adding-an-oadoi-dot-org-GES-link-to-Primo

@gam5 is looking at this: https://github.com/bulib/primo-explore-bu/blob/e5f2ed5bf001c7894c34f622b870a37714adc88e/custom/BU/js/unpaywall.module.js

Example here: 
https://buprimo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=TN_sciversesciencedirect_elsevierS1076-6332(12)00336-4&context=PC&vid=BU&search_scope=default_scope&tab=default_tab&lang=en_US

**Comment by winthropo** [comment]
Here is a link to an example in SOS test.

http://northeastern-primostaging.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=TN_sage_s10_5301_jva_5000118&context=PC&vid=NU&search_scope=default_scope&tab=default_tab&lang=en_US

![screen shot 2018-10-31 at 3 14 23 pm](https://user-images.githubusercontent.com/4663357/47812810-b712fe00-dd1f-11e8-9f1e-14422313dbd7.png)

But the link currently just takes you to the article we don’t have access to. My understanding is that the javascript @gam5 is going to adapt from BU will make it so that the link only appears when we do.

**Comment by winthropo** [comment]
@gam5  chatter about this on the listserv recently.

A different angular customization here? Checks for the existence of an Open Access resource, and only displays upon success:

https://github.com/alliance-pcsg/primo-explore-oadoi-link

Worth looking into?

**Comment by gam5** [comment]
I'll take a look.

**Comment by kmerguerian** [comment]
I don't know if there's a subscription change but I can actually get to the PDF of that article above.  I can report to library-help, maybe there should be a holdings update. 

Here's an example of an OA article that Unpaywall can link to.  But I can't find it in staging.  Maybe it's too new. 
https://onesearch.library.northeastern.edu/primo-explore/fulldisplay?docid=TN_crossref10.1159/000490360&context=PC&vid=NU&search_scope=default_scope&tab=default_tab&lang=en_US

If we DO have proxied access, AND there's an open access option that Unpaywall can find, that would be helpful for alumni and other guests using SoS.  These two articles are both OA but I don't think Unpaywall can find them unfortunately. 

http://northeastern-primostaging.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=TN_sciversesciencedirect_elsevierS1875-3892(12)00315-X&context=PC&vid=NU&search_scope=default_scope&tab=default_tab&lang=en_US

http://northeastern-primostaging.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=TN_proquest35079820&context=PC&vid=NU&search_scope=default_scope&tab=default_tab&lang=en_US


Honestly it's hard to find an OA article that Primo doesn't already supply an open access link to that Unpaywall can find.  We may not appreciate the extent to which Primo/SoS is already overlapping with the same OA content as Unpaywall whether commercial like Springer Open or repository like arXiv or DOAJ.  Primo also has a facet for limiting searches to open access and seems to be surfacing it more and more.   Maybe we should be advertising this more...including to internal stakeholders?

**Comment by winthropo** [comment]
I discussed with admin. They want us to close this one. Thanks @gam5 for the work on this.
