### ISSUE TITLE
SOS Report-A-Problem record links not working in staging

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#379]
Record links in Report-A-Problem ticket id #3432217 and id #3432081 don't work. 

![screen shot 2018-12-06 at 4 07 23 pm](https://user-images.githubusercontent.com/4663357/49611888-0973ba00-f971-11e8-85f7-8521d1f62e96.png)

I don't think this is related to the new November release in staging. Do you? What is going on here @gam5 ?

**Comment by winthropo** [comment]
Also an issue in prod.

**Comment by gam5** [comment]
The R-A-P links had the wrong search_scope (should be "default_scope"). Fixed in both Prod and Sandbox.
