### ISSUE TITLE
Save Query page doesn't scale on a small screen

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/scholar-onesearch#38]
- Browser: Chrome 27 on Linux (Android)
- Description: After I logged in, at bottom of the results page is a link to "Save query". The page I am taken to when I click on "Save query" doesn't seem to scale as nicely as the other pages on the site do. I have to zoom in quite a bit to fill out the form.
  ![2013-06-10 20 18 59](https://f.cloud.github.com/assets/4663073/634891/1b23f51a-d22d-11e2-8846-1432cf38c655.png)
  ![2013-06-10 15 52 34](https://f.cloud.github.com/assets/4663073/634892/204fa5de-d22d-11e2-8ea2-b9be8f530d12.png)

**Comment by bassettsj** [comment]
Thanks. That is exactly the type of feedback that will help me get this design tighter.

**Comment by bassettsj** [comment]
I will need to fix this in a later version. Should be in a quick update, sorry about that!

**Comment by bassettsj** [comment]
Won't fix turns out this is an issue with the vendors markup...

This should be reported to Ex Libris as something to fix.
They are missing the viewport meta tag to allow the design to respond...

``` html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

``` html
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">


  <!-- cssAdder.jsp begin -->
<!-- taglibsIncludeAll.jspf begin -->
<!-- taglibsIncludeAll.jspf end --><!--  css: http://primo-dev.mine.nu/scholar-onesearch/dist/css/legacy.css;http://primo-dev.mine.nu/scholar-onesearch/dist/css/style.css dontadddefault: true -->
<link rel="stylesheet" type="text/css" href="http://primo-dev.mine.nu/scholar-onesearch/dist/css/legacy.css">
            <link rel="stylesheet" type="text/css" href="http://primo-dev.mine.nu/scholar-onesearch/dist/css/style.css">
            <!-- begin resolveLocale.jsp -->
<!-- taglibsIncludeAll.jspf begin -->
<!-- taglibsIncludeAll.jspf end --><!-- locale=en_US -->

<!-- end resolveLocale.jsp -->
<link rel="stylesheet" type="text/css" href="../locale/en_US/css/Primo_Locale.css">
<!-- cssAdder.jsp end -->
<link rel="stylesheet" type="text/css" href="../css/temp.css">
<script type="text/javascript" src="../javascript/init.js"></script>
<title>
    Primo by Ex Libris</title>
</head>
```
