### ISSUE TITLE
Default scope spelling -- Feb 2019 release

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#381]
The default scope in the Feb 2019 release has gone British on us 🇬🇧 

![testingcatalogues](https://user-images.githubusercontent.com/4661920/53747005-5849c680-3e70-11e9-9f95-4124dc9f3447.png)

The scope below it in the dropdown is 'library catalogs' USA-style. 🇺🇸 

All scopes in production use US-style 'catalog' 

![catalogsprod](https://user-images.githubusercontent.com/4661920/53747010-5c75e400-3e70-11e9-96c4-8ab6115b4bba.png)

Should probably rename default scope in Feb 2019 release to 'library catalogs + articles' for consistency.

**Comment by winthropo** [comment]
Fixed. A victory for America! 🇺🇸 Closing case.
