### ISSUE TITLE
Loans Tab - remove "Pick up" row from loans details page

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#386]
Hi @gam5 

Could you remove the "Pick up" row from the loan details page by adding this code to the custom1.css file in the Customization package? Librarians think the pick up line is confusing in the loans tab and I don’t disagree. I've removed some other unnecessary and confusing lines from that screen using the BO. 

```
/*Remove from full display*/ 
p.normal-text:nth-child(2) { 
display:none; 
} 
```

![Screen Shot 2019-08-19 at 11 48 56 AM](https://user-images.githubusercontent.com/4663357/63382451-c1fb5580-c368-11e9-951f-a92af9183226.png)

**Comment by gam5** [comment]
All set.
