### ISSUE TITLE
Report A Problem Form

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#387]
Form is not auto-populating with URL or Permalink.

**Comment by gam5** [comment]
Looks to be a problem on the Springshare side. OUr javascript is no longer being rendered on the page. See here for details on how this is implemented: https://github.com/NEU-Libraries/scholar-onesearch/wiki/Primo---LibAnswers-=-Report-a-Problem

**Comment by nestochan** [comment]
This is fixed —- somehow the default group was set to not allow scripts which affected our settings. This is now fixed.
