### ISSUE TITLE
Citation Trails

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#388]
I enabled citation trails in test. Documentation on it [here](https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/End_User_Help/Using_Citation_Trails). 

Please share your thoughts here or send me an email. If we think it has improved we could enable it in production. 

Thanks.

**Comment by jasf-** [comment]
Much improved IMHO!  Nice visual representation of where the user is in the trail.

![CitationTrail](https://user-images.githubusercontent.com/4661920/70348801-72ff0080-1831-11ea-8850-1b949f22c5be.png)

**Comment by winthropo** [comment]
Enabled in production.
