### ISSUE TITLE
Request options: another orange search box 

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#39]
Browser/OS:  Chrome 27, Mac

Description:  Now that we finally have request options appearing, another orange search box has appeared.  To replicate, find a checked out item - click 'location and status' - click request link next to 'request options' - orange request box

Importance:  Medium

![moreorange](https://f.cloud.github.com/assets/4661920/636646/a4b733d4-d28a-11e2-9752-2c5bfa569e5d.png)

**Comment by bassettsj** [comment]
I would consider this definitely low importance, there isn't much blocking someone from being able to use this. I might be able to get to it after July 1st.
