### ISSUE TITLE
Scopes drop down is obscured on iPad

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/scholar-onesearch#40]
- URL: http://onesearch.neu.edu:1701/
- Browser: Chrome on iPad
- Description: The scopes drop down on the main OneSearch main page falls behind the Scholar OneSearch hero unit and the text to the right.
- Screenshot: 
  ![2013-06-11 08 58 01](https://f.cloud.github.com/assets/4663073/637004/be88eab6-d297-11e2-974e-ab7652bd6eb8.png)

**Comment by sarahjeansweeney** [comment]
This is happening on the results page, too:
![2013-06-11 11 11 05](https://f.cloud.github.com/assets/4663073/639048/5ab63f96-d2cb-11e2-8f37-e0292db1de15.png)

**Comment by bassettsj** [comment]
![ios simulator screen shot jun 12 2013 9 53 34 am](https://f.cloud.github.com/assets/1218420/642808/7c392d94-d367-11e2-8422-fb8e0d8b99cd.png)
