### ISSUE TITLE
Primo VE Display Language sort

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#400]
VE's Display Language list is sorted by the language code instead of the language name and currently there is no option to sort this list of languages. However, this request can be achieved as a workaround using the customization package. For example, this list can be reordered using CSS code:

prm-language-selection md-list-item[value="ar"]{ order: 0 !important; }
prm-language-selection md-list-item[value="zh"]{ order: 1 !important; }
prm-language-selection md-list-item[value="en"]{ order: 2 !important; }
prm-language-selection md-list-item[value="fr"]{ order: 3 !important; }
prm-language-selection md-list-item[value="de"]{ order: 4 !important; }
prm-language-selection md-list-item[value="he"]{ order: 5 !important; }
prm-language-selection md-list-item[value="it"]{ order: 6 !important; }
prm-language-selection md-list-item[value="ja"]{ order: 7 !important; }
prm-language-selection md-list-item[value="ko"]{ order: 8 !important; }
prm-language-selection md-list-item[value="pt"]{ order: 9 !important; }
prm-language-selection md-list-item[value="ru"]{ order: 10 !important; }
prm-language-selection md-list-item[value="es"]{ order: 11 !important; }

This code should be added at the end of your current custom1.css file.

**Comment by gam5** [comment]
Added to VE css file. Does not seem to work. continuing to investigate.

**Comment by gam5** [comment]
Actually, it does seem to work. Is this the order we want?

**Comment by winthropo** [comment]
Yeah! Looks good. Thanks.

**Comment by nestochan** [comment]
motoring!
