### ISSUE TITLE
CSS change needed to hide 'Held by Library' in 'Show Only' section

### ISSUE THREAD

**Issue by rmcnally** [NEU-Libraries/scholar-onesearch#401]
To remove the 'Held by Library' option here, we need to add some lines to the CSS.

![image](https://user-images.githubusercontent.com/25803683/131027999-9bde854e-5db5-42a1-a6d8-bb629113fd71.png)

Around Line 264 in custom1, add:

/* Hide facet Held by library */
[data-facet-value="tlevel-available_p"] {
display:none !important;}

https://knowledge.exlibrisgroup.com/Primo/Product_Documentation/020Primo_VE/Primo_VE_(English)/050Display_Configuration/010Configuring_Discovery_Views_for_Primo_VE#Configuring_the_Brief_Results_Page

**Comment by gam5** [comment]
This is just for VE?

**Comment by rmcnally** [comment]
Yeah, no rush.

**Comment by gam5** [comment]
Done
