### ISSUE TITLE
Menu link

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#403]
The link to the menu in the upper-right hand corner is difficult to read. It would be nice to tweak it ahead of go-live or earlier because it is also an issue in BO.

![menu](https://user-images.githubusercontent.com/4663357/136033140-0c34f78b-1d94-4e5e-b071-92c9f411e4c7.png)

**Comment by gam5** [comment]
Added this to the custom css:
`/* menu button colors */
prm-user-area-expandable .md-button.button-with-menu-arrow:not(.button-with-icon) {
  color: #666;
}
/* end menu button colors */
`
seems to have done the trick

**Comment by nestochan** [comment]
ok so now that menu is viewable -- it makes the sign in button not so awful --e
