### ISSUE TITLE
Orbis Worldcat customization

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#409]
I think we may have a display problem, especially in mobile, caused by or related to, our Worldcat passthrough customization. See #405 

I stumbled upon what I think is a more elegant solution at Adelphi: https://adelphi.primo.exlibrisgroup.com/discovery/search?vid=01ADELPHI_INST:01ADELPHI_INST&lang=en

@gam5 is going to try to get it up and working in our sandbox for us to evaluate. 

![Screen Shot 2022-02-15 at 10 58 13 AM](https://user-images.githubusercontent.com/4663357/154100606-42fe2743-cc2d-4b6c-97c5-f6d7ed438f54.png)

**Comment by winthropo** [comment]
R&I change requests so far:

1. Change language at the top of the widget from "Repeat my search in" to "Search other libraries in"

2. Remove Google Scholar link

Will receive final verdict in a week or so.

**Comment by winthropo** [comment]
Another minor change. I confirmed that it is "WorldCat." Right now it is "Worldcat" in SOS. That should be changed I think.

**Comment by gam5** [comment]
Changes have been made.

**Comment by winthropo** [comment]
We received approval from Karen and Alissa to make the change in production. Here is link to the details:https://github.com/alliance-pcsg/primo-explore-external-search

**Comment by gam5** [comment]
All set.
