### ISSUE TITLE
Hide Oakland view's virtual browse

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#410]
vid=01NEU_INST:NU_Olin

**Comment by gam5** [comment]
Hidden via CSS. 

`/* hide virtual browse for Mills */
div#virtualBrowse {
    display:none !important;
}
/* end hide virtual browse for Mills */`

**Comment by winthropo** [comment]
Thanks! That was fast. Closing case.

**Comment by gam5** [comment]
Updated in production. However, "Virtual Browse" still shows up as an item in the navigation menu. Let's leave this open and I will investigate our options.

**Comment by gam5** [comment]
Menu item hidden
