### ISSUE TITLE
Changes to Mills view homepage in sandbox

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#411]
Please add _Mills College at Northeastern University_ below Welcome to Scholar OneSearch

![Screen Shot 2022-07-21 at 9 25 48 AM](https://user-images.githubusercontent.com/4663357/180225978-968d7bae-4c8f-4886-a05b-b1eaf992229a.png)

Change second paragraph language from:
Looking only for books, e-books, or videos located at Snell Library, the Law Library, and the John D. O’Bryant African American Institute? Limit your search by choosing "Library Catalogs” in the dropdown menu.

To:
Looking only for books, e-books, or videos located at F. W. Olin Library? Limit your search by choosing "Mills Catalog” in the dropdown menu. And replace screenshot with this:

![Screen Shot 2022-07-21 at 9 33 11 AM](https://user-images.githubusercontent.com/4663357/180226298-3000b45d-a0b3-4681-9f51-9279c26e5eda.png)

**Comment by winthropo** [comment]
Also. Please adjust the WorldCat passthrough customization for Mills.

**Comment by gam5** [comment]
Should be all set. Let me know if anything seems amiss.

**Comment by gam5** [comment]
Updated in production

**Comment by winthropo** [comment]
![Screen Shot 2022-07-29 at 2 42 14 PM](https://user-images.githubusercontent.com/4663357/181824243-40cb0bec-d865-410c-9711-c2d4d08346f3.png)
Please replace with updated 'oakland' naming.

**Comment by gam5** [comment]
Changes in place. Please take a look and close this ticket if things look ok.

**Comment by gam5** [comment]
This appears to be all set
