### ISSUE TITLE
Advanced Search Page box size/arrow placement issue

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/scholar-onesearch#42]
- URL: http://onesearch.neu.edu:1701/primo_library/libweb/action/search.do?mode=Advanced&ct=AdvancedSearch&dscnt=0&dstmp=1370978245048&vid=NU
- Browser: Chrome on iPad & Chrome 27 on Windows
- Description: The search boxes on the Advanced Search page do not appear to fit. On the iPad, the dropdowns for Keyword Anywhere & contains don't align with the text box . On my desktop and on the iPad, the "GO!" arrow is in the bottom left hand corner of the box.
- Screenshot:
  iPad:
  ![2013-06-11 11 07 32](https://f.cloud.github.com/assets/4663073/639075/f28040c4-d2cb-11e2-973c-e412db90b74b.png)
  Desktop:
  ![2013-06-11_1520](https://f.cloud.github.com/assets/4663073/639081/058dd974-d2cc-11e2-80a2-bc8573db2f65.png)

**Comment by bassettsj** [comment]
Thanks for the feed back. I have moved the submit button over the the right. and added a little bottom margin for the selects and inputs on this form.
