### ISSUE TITLE
SOS Homepage Revised Wording & Links (US)

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#421]
**Welcome to Scholar OneSearch**
 
Scholar OneSearch provides simple, one-stop searching for e-books, videos, articles, digital media, and more.

**What am I searching?**
 
· E-books
· Scholarly and Peer-Reviewed Articles
· Newspaper Articles
· Journals
· Video and Audio
· Government Documents

And more from a variety of licensed and open source [databases and resources](https://library.northeastern.edu/get-help/tech-support/about-the-home-page-search/databases-and-resources-in-scholar-onesearch).

**Why should I sign in?**

Sign in with your Northeastern username and password in order to:

· Save results in My Favorites
· Request materials from other libraries via Interlibrary Loan (ILL)
· View full search results (Some databases, like Web of Science, only show results when you’re signed in)

**Where can I get help?**
 
· [Scholar OneSearch Tutorials](https://subjectguides.lib.neu.edu/researchtutorials/scholarone)
· [Ask a librarian ](https://library.northeastern.edu/get-help/ask-a-librarian)
· [Research subject guides](https://subjectguides.lib.neu.edu/)

Help | Library Home | Contact Us | Ask A Librarian | Northeastern Home

**Comment by winthropo** [comment]
All links remain the same except the Scholar OneSearch tutorials link should point here instead:https://subjectguides.lib.neu.edu/researchtutorials/scholarone

**Comment by gam5** [comment]
Homepage updated.

**Comment by gam5** [comment]
Where should "And more from a variety of licensed and open source databases and resources" link to?

**Comment by winthropo** [comment]
I'm not aware of that page existing in the new environment so please remove it. Thanks.
