### ISSUE TITLE
SOS homepage links to Drupal

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#427]
'What am I searching?' links to this: https://library.northeastern.edu/get-help/tech-support/about-the-home-page-search/databases-and-resources-in-scholar-onesearch

'Where can I get help; Ask a librarian' links to this: https://library.northeastern.edu/get-help/ask-a-librarian and should be changed to this: https://nupdlibrary.wpengine.com/research_instruction/ask-a-librarian/

These should be updated with new WP links.

**Comment by gam5** [comment]
I think this is all set?
