### ISSUE TITLE
Location and Status:  Hey, another orange search box!

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#43]
![orangelocationandstatus](https://f.cloud.github.com/assets/4661920/643246/cc3afd8a-d372-11e2-9d03-49839cf8a0d3.png)

URL:  one example shown above; here's another:  http://bit.ly/11zc9dt
Browser/OS:  Chrome 27, Mac
Description:  Another orange search box.  This one's tricky to surface because it doesn't show up all the time.  In order for it to appear, you have to find a physical item available in the library for which the list of holdings is so long a 'filter' option is offered.  (Long runs of a journal are most likely to be fruitful)

**Comment by bassettsj** [comment]
Thanks, that is great to know.

**Comment by bassettsj** [comment]
Okay that is really helpful. Thank you. I think I can actually fix this.

**Comment by jasf-** [comment]
Excellent.  Thanks again so much for your efforts!  It's looking great.

On Jun 12, 2013, at 9:21 PM, "Steven Bassett" <notifications@github.com<mailto:notifications@github.com>> wrote:

Okay that is really helpful. Thank you. I think I can actually fix this.

**Comment by bassettsj** [comment]
No go, this is a post July 1st issue, I cannot change this since it is in that dang mashup.css file.
