### ISSUE TITLE
SOS search boxes link change

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#430]
For library homepage SOS box and each portal page box please change 'Books & E-Books' link label to 'E-Book Collections.' 

![Screen Shot 2023-01-12 at 12 30 56 PM](https://user-images.githubusercontent.com/4663357/212138048-8179101d-9714-4f86-afc9-a5ebf932aecc.png)

**Comment by gam5** [comment]
I believe J9 has taken care of this one.
