### ISSUE TITLE
SOS Journal Finder link

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#432]
Broken link. Can we create a new WP page and update for all four views?

<img width="684" alt="Screen Shot 2023-01-17 at 12 34 16 PM" src="https://user-images.githubusercontent.com/4663357/212970960-f833604b-7dd8-457f-8466-f814afe60087.png">

**Comment by winthropo** [comment]
You can use the language at the top of the A-Z databases page .https://subjectguides.lib.neu.edu/az.php

**Comment by gam5** [comment]
Page created. Same url as before.

**Comment by winthropo** [comment]
Thanks!
