### ISSUE TITLE
NCH > Northeastern University London

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#433]
'NCH' should be changed to 'Northeastern University London' on these SOS homepages: Boston, International, Oakland. We don't have this note in the US view which I suppose makes sense. 

I updated the yellow sign in banner. I can't think of any other NCH mentions in SOS, but if you do let me know.

**Comment by winthropo** [comment]
Reading through my emails with Lindley about this. Not sure where this fell off but only the international homepage view needs the Northeastern University London note. So, please remove it from Boston and Oakland views. Thank you.

**Comment by gam5** [comment]
Done.
