### ISSUE TITLE
Increase Sign in link contrast

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#438]
Difficult to read the Sign in link in upper-right-corner of SOS. Possible to improve this for all views?

![Screenshot 2023-06-07 at 12 08 47 PM](https://github.com/NEU-Libraries/scholar-onesearch/assets/4663357/bb7ca563-6690-4308-857a-a81867577fec)

**Comment by gam5** [comment]
Updated CSS for SB Boston view. Let me know what you think. https://northeastern-psb.primo.exlibrisgroup.com/discovery/search?vid=01NEU_INST:NU

**Comment by winthropo** [comment]
Perfect! I say do it in production for all views. Thank you!

**Comment by gam5** [comment]
In place for all views in production.
