### ISSUE TITLE
Remove/hide yellow sign in banner from all views

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#439]
POG decided on 6/15/23 to hide the sign in banner from all four views.

![Screenshot 2023-06-15 at 4 12 31 PM](https://github.com/NEU-Libraries/scholar-onesearch/assets/4663357/3d6687bb-32aa-4cde-99d7-201a02e4582b)

**Comment by gam5** [comment]
Banner hidden from all views in production.
