### ISSUE TITLE
Facet plus drops down below facet heading

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/scholar-onesearch#44]
- URL: http://northeastern-primostaging.hosted.exlibrisgroup.com/primo_library/libweb/action/search.do?dscnt=3&fromLogin=true&frbg=&scp.scps=scope%3A%28%22NEU%22%29%2Cprimo_central_multiple_fe&dstmp=1371062143128&vl(freeText0)=anything&fn=search&vid=NU&fromLogin=true
- Browser: Chrome 27 on Windows
- Description: After I limited a search using the facets, the plus to expand the facets on the left dropped down below the facet heading.
- Screenshot:
  ![2013-06-12_1440](https://f.cloud.github.com/assets/4663073/644552/0740bf2e-d390-11e2-93b9-332773bd4485.png)

**Comment by bassettsj** [comment]
Fixed!
