### ISSUE TITLE
Missing header images in IE

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/scholar-onesearch#47]
- URL: http://onesearch.neu.edu:1701/primo_library/libweb/action/search.do
- Browser: Internet Explorer 8 on Windows
- Description: NU/Scholar OneSearch header images do not display. Page also has two error messages:

Message 1:
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; InfoPath.3; MS-RTC LM 8; .NET4.0E)
Timestamp: Mon, 24 Jun 2013 15:34:22 UTC

Message: Syntax error, unrecognized expression: unsupported pseudo: first-of-type
Line: 2
Char: 59313
Code: 0
URI: http://onesearch.neu.edu:1701/primo_library/libweb/javascript/jquery/jquery-1.8.3.min.js

Message: Script error
Line: 0
Char: 0
Code: 0
URI: http://liblab.neu.edu/primo-frontend/js/nulib.min.js

Message 2:
Webpage error details

User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; InfoPath.3; MS-RTC LM 8; .NET4.0E)
Timestamp: Mon, 24 Jun 2013 15:34:52 UTC

Message: Syntax error, unrecognized expression: unsupported pseudo: first-of-type
Line: 2
Char: 59313
Code: 0
URI: http://onesearch.neu.edu:1701/primo_library/libweb/javascript/jquery/jquery-1.8.3.min.js

Message: Script error
Line: 0
Char: 0
Code: 0
URI: http://liblab.neu.edu/primo-frontend/js/nulib.min.js
- Screenshot: 
  ![2013-06-24_1136](https://f.cloud.github.com/assets/4663073/696330/e13624a6-dce3-11e2-9d50-9ebaa00668e7.png)

**Comment by nestochan** [comment]
Steve,

This info might help take care of this error. for IE: 6-8

> :first-of-type is not a jQuery selector. :first-of-type only works in browsers which natively support this selector.
> 
> For other browsers, extend the selector set ($.expr[':']). Have a look at this project. jquery-extra-selectors.js adds > > support for several pseudo-class selectors.

https://github.com/keithclark/JQuery-Extended-Selectors

#jQuery Extra Selectors#

This jQuery "plugin" adds support for the following CSS3 pseudo-class selectors to jQuery:
- :first-of-type
- :last-of-type
- :only-of-type
- :nth-of-type
- :nth-last-of-type

The project was written to service the needs of **selectivizr** users but it can be used in any project based on the jQuery library.

##Using the script##

Before using the script you'll need to include it in your page (shown below). Make sure you add it **after** the main jQuery script. Once included, you'll be able to use the selectors above in your jQuery statements.

```
<script src="{path}/jquery.js"></script>
<script src="{path}/jquery-extended-selectors.js"></script>
```

###Examples###

```
$("div:only-of-type").css("background", "red");
$("p:first-of-type").css("color", "red");
```

##Note for selectivizr users##

If you are using this script purely to extend jQuery's support for selectivizr then you'll only need to include this script for IE6-8. The best way to do that is, add it to the same conditional comment as the selectivizr script. This will prevent browsers that already support these selectors from downloading this plugin.
