### ISSUE TITLE
Report a problem icon in IE

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/scholar-onesearch#48]
- URL: http://onesearch.neu.edu:1701/primo_library/libweb/action/search.do?dscnt=0&frbg=&scp.scps=scope%3A%28NEU%29&tab=default_tab&dstmp=1372089352686&srt=rank&ct=search&mode=Basic&dum=true&indx=1&vl(freeText0)=seals&fn=search&vid=NU
- Browser: Internet Explorer 9 on Windows
- Description: The Report a problem icon displays three times, once as the orange link and twice as unclickable black and white icons.
- Screenshot: 
  ![2013-06-24_1156](https://f.cloud.github.com/assets/4663073/696497/6fb71ec6-dce7-11e2-8714-f2ae60648da5.png)

**Comment by jasf-** [comment]
@bassettsj and/or @sarahjeansweeney, can this one be closed?

**Comment by bassettsj** [comment]
sure
