### ISSUE TITLE
Sign-in button persists after login.

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#52]
1.       Upon accessing the service from the portal, I have noticed that there is a prominent “Sign In” button being displayed on the page although with the SSO in place between Luminis and Primo (see screen shot below), this is not necessary as you are already signed in. I had several individuals walk through this and every person selected the “Sign In” option although it does result in any change or is even necessary. The impression left was there is something broken. Is there any reason why this was placed on the landing page after a successful sign-on?
   (From Kevin Legget) IS-IDM dept head

![persistent-sign-in_button](https://f.cloud.github.com/assets/2441612/783160/2ed250e6-ea49-11e2-91ef-017b0cf24eb6.png)

**Comment by bassettsj** [comment]
It is static HTML. All I can do is remove the sign in all together. I can do that.  It is up to the primo group.

**Comment by nestochan** [comment]
Dunno, to my thinking... if we can't make it more dynamic ie: have it
switch to <sign-out> when logged-in --- the confusion it causes by
persisting is enough to warrant it's removal.

other solutions may be to alter what it says and not present it as a
clickable-button...but more of a note...

-e

**Comment by bassettsj** [comment]
Well I am saying that button is just "Dumb" `<a href="` so it can't easily tell what the context is of the user too reliably. It isn't really provided by Primo is the user is logged in. The only thing I could do would cause the button to disappear everything the user is logged in after the DOM has loaded. It adds a bit more to our already large DOM minipulation. So I propose to simply by removing the link if it is not helpful for the user.

**Comment by bassettsj** [comment]
Thanks @nestochan for using the issue queue. My email thanks you :smile:

**Comment by bassettsj** [comment]
from @JenF

> Just thinking out loud here:  what if not only the sign in button, but also the jumbotron (I think that's the right word) it sits in on the landing page was removed altogether?
> Removing it would take care of persistent 'sign in' button issue (that appears even when signed in);
> Would also address one of Karen's suggestions:  that the Scholar OneSearch logo appears twice on the main page, once in banner and once in jumbo;
> Additional bonus, the explanatory text bit "How does this work?" etc. might be then able to utilize more of the real estate below the red banner (?), making it appear less lengthy/more scannable.
> 
> I think it was good that we started out with very prominent branding / sign in reminder there (nicely executed by Steven).  I think the situation has evolved (Scott would say it's become more fluid) since we made the choice to put the huge sign in button on the main page.  We do still have to push the idea to users that they'll need to sign in, but Shib helps with that, as does the fact that with Alma underneath now patrons have to sign in to do things like look at loans and place requests anyway.

**Comment by bassettsj** [comment]
From Karen

> Steven, if you remove the “sign in,” I assume it will it only be gone in this particular situation that is, it would appear when the user is not signed in?  Sorry if this is a stupid question, I just don’t know what options are available. 
> 
> Assuming the appearance of that link is sensitive to the signed-in/out state, I would then replace it with “Signed in as: Merguerian” or “Welcome, Karen” or even “You are signed in” if the individual name cannot be made to appear.(Also while I feel it’s a little buggy, I’m not sure whether I agree with Kevin it seems “broken”, or whether I think it’s more important than other issues…)

**Comment by bassettsj** [comment]
issue #60 resolves this.
