### ISSUE TITLE
GetIt tab location/call number customization?

### ISSUE THREAD

**Issue by sarahjeansweeney** [NEU-Libraries/scholar-onesearch#53]
- URL: http://onesearch.neu.edu:1701/primo_library/libweb/action/search.do?dscnt=0&frbg=&scp.scps=scope%3A%28NEU%29&tab=default_tab&dstmp=1374517994624&srt=rank&ct=search&mode=Basic&dum=true&indx=1&vl(freeText0)=kentucky%202010&fn=search&vid=NU
  - Browser: Chrome 28 on Windows
  - Description: I have no idea if this is possible with CSS, but I think it would be nice if the location and call number fell on their own separate lines. For most location/call number combinations, a single line is enough. But in the screenshot example the location name is rather long, and the government document call number is long, causing the call number to break after the first letter.
  - Screenshot:
    ![2013-07-24_0933](https://f.cloud.github.com/assets/4663073/848657/c91091ce-f465-11e2-9cd0-ab2a6455a305.png)

**Comment by jasf-** [comment]
READ decided to table this for future release.

**Comment by jasf-** [comment]
Just noting for the record a few possibilities discussed at READ 1/8/14:

bold the call # (in RTA statement and/or within location & status tab)
suppress barcode in location & status tab - move elsewhere?
include location map or at least general info ('P-Z are on 4th floor')

**Comment by jasf-** [comment]
Related to #61

**Comment by nestochan** [comment]
closing: :closed_book:  much of this call has been incorporated in issue #61 considering a duplicate :two_women_holding_hands:
