### ISSUE TITLE
Customizations impacting SOS records sent to print

### ISSUE THREAD

**Issue by jasf-** [NEU-Libraries/scholar-onesearch#54]
Howdy,

It looks as though display customizations are mangling output of records - specifically links within records - when sent to print.

Example record sent to print from production Scholar OneSearch:
![sendtoprintsos](https://f.cloud.github.com/assets/4661920/855945/efb94f3c-f532-11e2-9717-ab6387227bb5.png)

Same record sent to print from the 'debug' view of SOS: (http://onesearch.neu.edu/primo_library/libweb/action/search.do?vid=NUdbg)
![sendtoprintvanillasos](https://f.cloud.github.com/assets/4661920/855949/0776a246-f533-11e2-8062-6546e5a40e13.png)

Cheers,
J

**Comment by bassettsj** [comment]
- [ ] Remove the print styles for urls to be shown after links.
