### ISSUE TITLE
configuring/styling of AlmaServices window in Primo (NEU CSS Services Page)

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#58]
## Re-Configuration of Alma Services Link

In: _Primo Home > Ongoing Configuration Wizards > Institution Wizard > Alma Services Page URL_
- Exclude port 1701 from link to allow access through nuwave-guest, 
- Change view code to system default view NU in order to achieve desired styling.
       View- code kept the same : vid=neu_services_page -- assigned NU Libraries Frontend CSS to the view to           achieve styling.

**Comment by nestochan** [comment]
assignment of NU Libraries Front end CSS to achieve styling is ok in the short-term, but with that styling comes a lot of un-needed extras (for eg: the searchbox, - is not needed)  example of simpler version here:

![screen_shot_2_2013-09-05_at_2 45 49_pm](https://f.cloud.github.com/assets/2441612/1152196/39a5ca40-1f08-11e3-834e-52c0bb5dc66b.png)

 that will require a bit more customization. R.E.A.D committee will discuss what the final styling requests will be and will get back with requests and scheduling.

**Comment by bassettsj** [comment]
@nestochan can I put this one on hold?

**Comment by nestochan** [comment]
is this the one where they like the styling, but not the search box?

**Comment by bassettsj** [comment]
@nestochan Thanks for the reply! :+1: 

This is the one that:

> assignment of NU Libraries Front end CSS to achieve styling is ok in the short-term, but with that styling comes a lot of un-needed extras (for eg: the searchbox, - is not needed)

**Comment by nestochan** [comment]
we believe this to be a duplicate for #111 and we are closing...
