### ISSUE TITLE
Request for addition of Worldcat pass-thru search based on Notre Dame javascript and CSS mods

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#59]
#### Request: That a Worldcat Badge appear on all search result pages that can be clicked on to pass the search on to our WCL instance <northeastern.worldcat.org>

**Link to Notre Dame supplied Info:**
https://www.dropbox.com/s/z4guppz2hfnxjju/worldcat-link-passthrough-Javascript.zip

**Javascript and CSS will probably need slight modification to work with our customizations since it is based on standard EXL CSS.**

-e

**Comment by nestochan** [comment]
Steve, this has been pushed up a bit in importance due to faculty complaints
about ILL options is SOS. Let me know how things are looking task-wise so we can fit it in.

-e

**Comment by bassettsj** [comment]
### Update

Made some updates to the navbar to make room for the world cat link. Need to tweak it a bit more.

![screen shot 2013-10-09 at 12 48 28 pm](https://f.cloud.github.com/assets/1218420/1299455/af52e870-3102-11e3-9d89-a7220dd323ac.png)

**Comment by nestochan** [comment]
thanks Steve looking good.

**Comment by bassettsj** [comment]
This is what I am proposing as a solution.

![screen shot 2013-10-09 at 2 41 04 pm](https://f.cloud.github.com/assets/1218420/1300469/6642f962-3112-11e3-895e-f7c6eb923d43.png)

**Comment by bassettsj** [comment]
@nestochan @kmerguerian: I am assuming this should take users to the http://northeastern.worldcat.org/ site instead of the normal worldcat site, correct?

**Comment by nestochan** [comment]
yup, correct, we want it to go  our instance of worldcat.

**Comment by bassettsj** [comment]
I am going to close this for now, will let REED work out the language and UX stuff

**Comment by kmerguerian** [comment]
And no exproxying please, we don't have the need for login block.

Karen Merguerian
User Services
Northeastern University Libraries

On Oct 9, 2013, at 5:15 PM, "nestochan" <notifications@github.com<mailto:notifications@github.com>> wrote:

yup, correct, we want it to go our instance of worldcat.

**Comment by nestochan** [comment]
thanks Steve, this works pretty well... Thanks for turning this around for everyone, now it's up to ReAD to finalize, and work towards deployment. @kmerguerian can you bring this to ReAD. thanks.
