### ISSUE TITLE
Improve call number visibility in Location and Status tab

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#61]
Users need to know that the call number is the relevant information they need to identify and locate an item.   Suggestions are to 
1) Wrap the call number itself on a second line ---> first reported - #53
2 ) Precede it with the label "Call Number"
3) Inside the box, update the style somehow to increase visibility of the call number

**Comment by bassettsj** [comment]
@kmerguerian Can you please provide a screen shot as an example?

**Comment by bassettsj** [comment]
@kmerguerian Can you show me the element itself?

**Comment by bassettsj** [comment]
![screen shot 2013-09-25 at 4 03 54 pm](https://f.cloud.github.com/assets/1218420/1212755/b2b6eb3c-261d-11e3-88a5-5c08e0ace12c.png)

**Comment by bassettsj** [comment]
Ask @nestochan about accessing the GetIt tab front end styles.

**Comment by nestochan** [comment]
##### Much of this can be styled with the VCU customizations.
2. Not sure about the adding a label.(is this what you mean? in the browse list? (this may require some .js to do.
   ![screen shot 2014-02-04 at 11 21 15 pm](https://f.cloud.github.com/assets/2441612/2084287/16a16c1e-8e1d-11e3-948c-a076267ebce0.png)
3. the barcode column can also be removed and the barcode can me modified by 
   .width60 to something higher 80 or so or unlinking that attribute-- this will move the hide details link down a line and prevent the call number from breaking in most cases. see #53 (this can be done via VCUcss customiztion method

https://gist.github.com/nestochan/b3045c346dbe6f41d2bd
https://gist.github.com/nestochan/555253362e64e1e614cc
