### ISSUE TITLE
Advanced search page, styling

### ISSUE THREAD

**Issue by kmerguerian** [NEU-Libraries/scholar-onesearch#62]
Adjust style so that the search box itself is not so prominent on the results page, and more results appear in the default view without scrolling.   

Specific suggestions would be to reduce the neutral space and box size, use red more judiciously (maybe as the box border rather than background color).  

Compare the advanced search results page in SoS with a more typical implementation. 

![sosresults](https://f.cloud.github.com/assets/2442078/1174455/d26b9f66-2147-11e3-998f-94f552d85cbc.PNG)
![defaultadv](https://f.cloud.github.com/assets/2442078/1174456/d96c2510-2147-11e3-841d-93bdefe50956.PNG)

**Comment by bassettsj** [comment]
Working on this issue now :+1: 

Definitely could see this being a major issue. I am trying to make the inputs a little smaller and more compact. Not done yet but soon.

![screen shot 2013-09-26 at 9 53 11 am](https://f.cloud.github.com/assets/1218420/1217986/3379d05a-26b3-11e3-84db-8564352a2ad5.png)

**Comment by bassettsj** [comment]
@nestochan Do you know if there is a way to move this fields?

![screenshot](https://f.cloud.github.com/assets/1218420/1218090/2f700982-26b5-11e3-84b1-fde95afe1770.png)

**Comment by bassettsj** [comment]
![screen shot 2013-09-26 at 5 11 06 pm](https://f.cloud.github.com/assets/1218420/1226060/25887a70-2779-11e3-99dc-2306c3e10806.png)

Getting closer. It is taking longer than expected :frowning:

**Comment by bassettsj** [comment]
## Feedback Requested

Will leave this issue closed for the time being but wanted to get your comments on [this design on redpen.io](http://redpen.io/4z3s92). Please take a few moments to leave :+1: or :-1:

**Comment by kmerguerian** [comment]
Steven, thanks for this, just wanted to ask if you have been able to test this on an iPad and laptop, just to make sure results on those devices are likely to appear above the fold?  Karen
