### ISSUE TITLE
Citation linker looks wonky in Firefox 24.0

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#81]
![screen shot 2013-10-21 at 11 00 18 am](https://f.cloud.github.com/assets/4663357/1373389/87313b22-3a61-11e3-8d85-1161c40ce1a9.png)

Reported by Amira.

**Comment by bassettsj** [comment]
We did not agree to add support for the citation linker in this release, won't fix this bug now.

**Comment by nestochan** [comment]
added to  :cool: Future Development Holder(Milestone) :pushpin:
