### ISSUE TITLE
View all versions and FRBR  actions 

### ISSUE THREAD

**Issue by bassettsj** [NEU-Libraries/scholar-onesearch#84]
Without using JS to move the button once the page loads, this is how it would look.
![screen shot 2013-10-22 at 2 18 05 pm](https://f.cloud.github.com/assets/1218420/1383960/565d2da4-3b46-11e3-824f-43a2fa9f74c9.png)

If this is acceptable, I think I would suggest leaving it as it is otherwise, I can use JS to move the button (which adds more complexity to the project :-1: )

My second questions is to check and make sure the buttons (as pictured below) will open a new page with just one result, this doesn't seem like the desired action we wanted.
![screen shot 2013-10-22 at 2 23 36 pm](https://f.cloud.github.com/assets/1218420/1384012/1b28a2b2-3b47-11e3-9cfc-5e5b756e1d30.png)

**Comment by nestochan** [comment]
Steve, if still in effect the FRBR button is moved via custom script in the add-on directory... check this out if it's interfering with anything or if it will make moving the button easier if required.
