### ISSUE TITLE
Return the dropdown arrow on the scopelist

### ISSUE THREAD

**Issue by bassettsj** [NEU-Libraries/scholar-onesearch#86]
![screen shot 2013-10-23 at 4 51 51 pm](https://f.cloud.github.com/assets/1218420/1394166/f4e49b22-3c24-11e3-8c37-fce9b3577902.png)

**Comment by bassettsj** [comment]
e3aae65 fixed this issue.

**Comment by nestochan** [comment]
brilliant!  thanks Steve.

----- Reply message -----
