### ISSUE TITLE
SOS test - CSS-related cosmetic issues viewing eshelf in Safari

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#87]
# SOS test - CSS-related cosmetic issues viewing eshelf in Safari
## Submitted on Thursday, October 31, 2013 - 16:06

> First name: Jen
> Last name: Ferguson
> Email: j.ferguson@neu.edu
> NU affiliation: staff or researcher
>  SOS test - CSS-related cosmetic issues viewing eshelf in Safari
> Type of problem: Other
> Describe the problem:
> 
> Cosmetic issues affecting display of onesearch-test e-shelf in Safari.  See
> attached.
> 
> http://library.northeastern.edu/sites/default/files/public/webform/report_a_problem/testeshelfsafarivchrome.pdf
> 
> Browser: safari
> Operating system: MacOSX  - Windows7
> ![testeshelfsafarivchrome](https://f.cloud.github.com/assets/2441612/1454353/7a42c4d6-4307-11e3-8f92-0db7b7cb24c9.png)

**Comment by bassettsj** [comment]
![Sreen shot of Safari with the eshelf](https://f.cloud.github.com/assets/1218420/1485362/cddbb192-4713-11e3-8370-6033b388639d.png)
