### ISSUE TITLE
SOS - CSS customizations interfering w/ print outputs (production & test)

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#88]
## Submitted on Thursday, October 31, 2013 - 16:34
# SOS - CSS customizations interfering w/ print outputs (production & test)

> First name: Jen
> Last name: Ferguson
> Email: j.ferguson@neu.edu
> NU affiliation: staff or researcher
> SOS - CSS customizations interfering w/ print outputs (production & test)
> Type of problem: Other
> Describe the problem:
> 
> Noting for the record that printing ouput is still borked in both SOS
> production and onesearch-test (example attached - note how links are
> rendered).
> 
> This looks fine in our 'vanilla' SOS view so I'm assuming this issue is
> related to our custom CSS.
> Upload a screenshot (optional):
> http://library.northeastern.edu/sites/default/files/public/webform/report_a_problem/preview_of_scholar_onesearch_-_nu_libraries.pdf
> My location: on campus using Resnet or NUNet
> Browser:
> - chrome
> - safari
>   Operating system: MacOSX X-Platform

![preview_of_scholar_onesearch_-_nu_libraries](https://f.cloud.github.com/assets/2441612/1455572/659a0606-431c-11e3-8cba-6ef7fcebfbfb.png)

**Comment by nestochan** [comment]
commit 879e220 -- fixes this on onesearch-test...

**Comment by bassettsj** [comment]
Thanks @nestochan

On Friday, November 1, 2013, nestochan wrote:

> commit 879e220https://github.com/NEU-Libraries/scholar-onesearch/commit/879e220-- fixes this on onesearch-test...
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/NEU-Libraries/scholar-onesearch/issues/88#issuecomment-27584403
> .

## 

Steven J. Bassett

**Comment by bassettsj** [comment]
@nestochan Can I close this issue?
