### ISSUE TITLE
Should the recommendations tab be hidden?

### ISSUE THREAD

**Issue by bassettsj** [NEU-Libraries/scholar-onesearch#92]
![screen shot 2013-11-06 at 11 55 49 am](https://f.cloud.github.com/assets/1218420/1484246/563d0c30-4704-11e3-8e8b-94aec0f85262.png)
@nestochan Does READ want this tab to be shown? If so, do I need to hide this with CSS or could it be done with configuration?

**Comment by jasf-** [comment]
Let's keep it visible.  Thanks - Jen
