### ISSUE TITLE
Inconsistent pop-up window scrollbar behavior using IE10

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#93]
IE10's (Windows 7) vertical scrollbar doesn't scroll the new 'show more options' facets feature pop-up window--instead it scrolls the background.  I have to use the keyboard arrow buttons or page-down buttons to scroll to the end of the facet refine box.  This isn't the case for other pop-up windows like the 'personalize your results' so it confused me for a second. To get to the continue/cancel options on a long list like the 'show more facet options' you need to be able to scroll. Can you help us fix this scrollbar issue before the next release on December 10?

To see this in action:

Using IE10. Do a search for 'art' and try to refine the source facet. Notice you can't use the scrollbar.

**Comment by nestochan** [comment]
Scrollbar for foregrounded pop-out panel hidden behind SB for main panel.

![sos-sb](https://f.cloud.github.com/assets/2441612/1591220/ebe0189a-529e-11e3-8b85-9432a27966da.png)

**Comment by bassettsj** [comment]
So I found a nice solution to this problem by adding just a small override function to the javascript function that opens and closes these modal / lightboxes in primo.

``` js

var oldPrimoLightBox =  openPrimoLightBox;
    openPrimoLightBox = function() {
      var result = oldPrimoLightBox.apply(this, arguments);
      $('body').addClass('modal-open');
      return result;
    };
    var oldhideLightBox = hideLightBox;
    hideLightBox = function(){
      var result = oldhideLightBox.apply(this, arguments);
      $('body').removeClass('modal-open');
      return result;
    }
```

Now this will cause the body to hide instead of scroll any of the overflow on the body element.

**Comment by bassettsj** [comment]
@nestochan Want to check this one and close it if you determine that is is fixed?

**Comment by nestochan** [comment]
@winthropo 

> Want to check  :mag:  this one and determine that it's fixed/ (working better)?
> try a shift :leftwards_arrow_with_hook:  refresh  or cache clear before checking.

**Comment by winthropo** [comment]
@nestochan  Working. Thanks.
