### ISSUE TITLE
adding .EXLResultFourthLine

### ISSUE THREAD

**Issue by nestochan** [NEU-Libraries/scholar-onesearch#97]
![screen shot 2013-11-22 at 3 20 08 pm](https://f.cloud.github.com/assets/2441612/1604024/641ebb10-53b5-11e3-829d-0a06b04a762c.png)

please allow for display of publisher/year info as controlled by .EXLResultFourthLine CSS element... from above

``` CSS
.EXLResultFourthLine {
  font-size:12px;
  font-weight:300;
  line-height:1.3;
  margin-top:5px;
}
```

to something similar to this:

![screen shot 2013-11-22 at 3 41 20 pm](https://f.cloud.github.com/assets/2441612/1604095/b49676e0-53b6-11e3-91a5-546b54930673.png)

::Incoming email::

> In staging I removed and re-added publisher info to the third line of the brief display 
> for the NU view and it still doesn’t display after the view was deployed.
> You pointed out that publisher info also wasn’t displaying in NU_CLEAN. I checked 
> the settings for that view and the publisher information wasn’t set up to display at all. I added publisher and date, and now that information displays in the third line for brief  
> results in staging under the NU_CLEAN view.
> I’m not sure what else could be at play here, so it’s possible the third line is being
> hidden by CSS.

**Comment by bassettsj** [comment]
https://github.com/NEU-Libraries/scholar-onesearch/commit/08383249dda71c9003409e34991150e4f51c0106

**Comment by nestochan** [comment]
:cake: 

Thanks!
