### ISSUE TITLE
Journal view/scope

### ISSUE THREAD

**Issue by winthropo** [NEU-Libraries/scholar-onesearch#98]
At the Dec. 4th READ meeting we started to discuss the pros and cons of implementing a journal view/scope like the one at BU. Let’s add this to the growing list of enhancement ideas floating around and put it to a vote eventually. 

The BU example:

http://buprimo.hosted.exlibrisgroup.com:1701/primo_library/libweb/action/search.do

**Comment by sarahjeansweeney** [comment]
I created a new view for an Advanced search for Journals, similar to BU's search:

http://onesearch-test.neu.edu/primo_library/libweb/action/search.do?mode=Advanced&ct=AdvancedSearch&dscnt=0&dstmp=1392153816094&vid=NU_JOURNALS

Naturally, some styling would need to be addressed if we want to implement it. Also, the dropdowns can be edited to remove or rearrange the other options.

**Comment by elizoller** [comment]
Styling should be fixed by 4ecee9c and 447d203
See http://onesearch-test.neu.edu/primo_library/libweb/action/search.do?mode=Advanced&ct=AdvancedSearch&dscnt=0&dstmp=1414674180133&vid=NU_JOURNALS

**Comment by elizoller** [comment]
Where should the link go to this view?

**Comment by winthropo** [comment]
We think the link should go on the advanced search page. Do you have a recommendation on where you think it should go on that page? We can also discuss at our meeting on Friday.

**Comment by elizoller** [comment]
Perhaps over/under Simple Search?
![screen shot 2014-11-06 at 12 58 56 pm](https://cloud.githubusercontent.com/assets/5439169/4940881/a1a537ac-65de-11e4-85ba-24d4803cec2a.png)

Could it make sense on the E-Journal Finder page?

**Comment by winthropo** [comment]
Yeah. Let's try it out there... could you change it to "journal title search"? Thanks!

**Comment by elizoller** [comment]
added with fc7f3676e359ba95f3759bc8dd337aac708deafd

**Comment by elizoller** [comment]
I adjusted the styling on the journal title search link so the red box doesn't get quite so big. 47eb741536c97cd80c7fb04dadaf6a297e49aadc
The only thing is that Simple Search and Journal Title Search are pushed higher before a search is run (after a search the Search Other Libraries link fills that space).
Still trying to think of a way around this.
Before search:
![screen shot 2014-11-07 at 4 12 41 pm](https://cloud.githubusercontent.com/assets/5439169/4960427/dd803602-66c2-11e4-9a5b-1fef1087ddb5.png)
After search:
![screen shot 2014-11-07 at 4 12 53 pm](https://cloud.githubusercontent.com/assets/5439169/4960428/e233419e-66c2-11e4-9ff0-48db1646924f.png)

**Comment by elizoller** [comment]
Second Option - push links to bottom of red box all the time (only changes view before search is run)
(on NUdev view)
![screen shot 2014-11-12 at 1 05 59 pm](https://cloud.githubusercontent.com/assets/5439169/5015544/af2634f2-6a6c-11e4-93c0-008df4e16830.png)

![screen shot 2014-11-12 at 1 04 27 pm](https://cloud.githubusercontent.com/assets/5439169/5015536/98f27574-6a6c-11e4-816f-f6a47f65a9c0.png)

**Comment by elizoller** [comment]
Going with second option for now 6f703af477d237e36d57455a6675f08c1f96563d
